### ISSUE TITLE
Picture for Windows 8 / IE 10 tile is not declared.

### ISSUE THREAD

**Issue by Didier77** [RealFaviconGenerator/realfavicongenerator#10]
Hello,

First thanks for your excellent site for generating favicon.

I have followed all steps described in http://realfavicongenerator.net and checked in FAQ but I have error "Picture for Windows 8 / IE 10 tile is not declared" when checking my web site http://lamourduprochain.org/.
I have checked also in the page source code that all data are present.

Did I miss something?

Thanks,
Didier

**Comment by phbernard** [comment]
Hi Didier,

Thank you for your message!

I reviewed the code of your homepage. The "favicon" section is not what I expected, for two reasons:
- The 2 or 5 last lines should be "meta" markups, dedicated to Windows 8 tiles. In your code I can see only "link" markups (8 "apple-touch-icon" and 5 "icon" as expected).
- The URL used in the code specify the domain name. Although this is correct, this is not what RFG should have generated. Did you modified the code afterward?

If you think you copied/pasted the whole code without altering it, could you tell me if something particular happened during the generation?

Regards,
Philippe

PS: ... et merci de l'avoir fait en Anglais, comme ça tout le monde peut en profiter :)

**Comment by Didier77** [comment]
Hi Philippe,

It seems that I was using a small picture (BTW: there is no indication in your web site that a png image is required) and therefore the additional Windows 8 "meta" markup. I have rebuild the html and the "msapplication-square...x...logo" have been added:
<meta name="msapplication-square70x70logo" content="http://lamourduprochain.org/mstile-70x70.png" />
<meta name="msapplication-square144x144logo" content="http://lamourduprochain.org/mstile-144x144.png" />
<meta name="msapplication-square150x150logo" content="http://lamourduprochain.org/mstile-150x150.png" />
<meta name="msapplication-square310x310logo" content="http://lamourduprochain.org/mstile-310x310.png" />
<meta name="msapplication-wide310x150logo" content="http://lamourduprochain.org/mstile-310x150.png" />

Even with the Windows 8 "meta" markup added, I still have a "Picture for Windows 8 / IE 10 tile is not declared." error.

BTW: I have put "http://lamourduprochain.org" in the place of favicons. 

Regards,
Didier

French Version:
Bonjour Philippe,

J'ai du utilisé la première fois une image trop petite. Par conséquent, les marqueurs "meta" pour Windows 8 étaient manquants.
Remarque: Rien n'indique sur votre site que le format png est requis.

J'ai régénéré le html et les "msapplication-square...x...logo" ont été ajoutés:
<meta name="msapplication-square70x70logo" content="http://lamourduprochain.org/mstile-70x70.png" />
<meta name="msapplication-square144x144logo" content="http://lamourduprochain.org/mstile-144x144.png" />
<meta name="msapplication-square150x150logo" content="http://lamourduprochain.org/mstile-150x150.png" />
<meta name="msapplication-square310x310logo" content="http://lamourduprochain.org/mstile-310x310.png" />
<meta name="msapplication-wide310x150logo" content="http://lamourduprochain.org/mstile-310x150.png" />

Même si les marqueurs "meta" Windows 8 ont été ajoutés, j'ai toujours l'erreur "Picture for Windows 8 / IE 10 tile is not declared.".

Remarque: J'ai mis  "http://lamourduprochain.org" comme place des favicons. 

Cordialement,
Didier

**Comment by phbernard** [comment]
Hi Didier,

You say that the site does not mention that a PNG picture is required. I supposed this is to oppose to JPG picture, right? As far as I know, JPG pictures are supported. Did you encounter an issue?

I've just checked the code of your home page. The meta markup related to Win 8 / IE 10 has a small typo. It says "msapplication-tileimage" whereas "msapplication-TileImage" is expected. There is a similar mistake with the color. I think fixing these two typos should close the case.

Regards,
Philippe

PS : It seems that we are both fluent. Let's do it the hard way, in full English :)

**Comment by phbernard** [comment]
About JPG pictures: I was reported a similar issue and realized only ".jpg" extension was allowed but not ".jpeg". It's fixed.

**Comment by Didier77** [comment]
Hi Philippe,

I have found that the "Head Cleaner" plugin (http://wordpress.org/plugins/head-cleaner/) set all meta values in lowercase.

But according to http://www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#standard-metadata-names: Names are case-insensitive, and must be compared in an ASCII case-insensitive manner.

Therefore, there is no error in my header but a limitation in your favicon checking that does not allow lowercase meta values.

Thanks,
Didier

**Comment by phbernard** [comment]
I didn't knew this! Thank you for reporting.

I have downcased msapplication-TileColor and msapplication-TileImage and tried to access a sample web page with my Surface 2 (Windows 8.1 RTM). The tile color is not recognized. I have no feedback for msapplication-TileImage, since it was replaced by new, lowcase names in Windows 8.1 (msapplication-square70x70logo and friends).

Yet another example of standard that is not strictly followed... In the end, I keep the checker as it is.

I'm going to notify Header Cleaner devs, they might want to know the plugin might break things with Win8/IE11.

**Comment by phbernard** [comment]
Header Cleaner notified, see http://wordpress.org/support/topic/turning-meta-names-to-lower-case-disrupts-ie11-tiles?replies=1

**Comment by Didier77** [comment]
You're right, see http://msdn.microsoft.com/en-us/library/ie/dn255024%28v=vs.85%29.aspx#msapplication-TileColor: Be aware that preset values are case-sensitive and must be specified using the case shown.

Header Cleaner breaks non-standard Microsoft (pleonasm ?) behavior!

Thanks for your effort and prompt answer. I think we can close this ticket.

Regards,
Didier

**Comment by phbernard** [comment]
Ah! I reviewed this page and even didn't notice the "case sensitive issue" was explicitly mentioned.

Thank you for closing the ticket.
