### ISSUE TITLE
Add support for theme-color

### ISSUE THREAD

**Issue by instanceofme** [RealFaviconGenerator/realfavicongenerator#108]
Chrome 39 / Android Lolipop [will support a `theme-color` meta tag](http://updates.html5rocks.com/2014/11/Support-for-theme-color-in-Chrome-39-for-Android). It would be nice to add it in the generator.

**Comment by phbernard** [comment]
Hey great! I didn't notice this. Thanks the suggestion!

**Comment by instanceofme** [comment]
You're welcome, thank you for this very handy tool.

**Comment by phbernard** [comment]
Two steps:
- Non-interactive API: implemented and deployed a minute ago (http://realfavicongenerator.net/api/non_interactive_api).
- UI: Todo later.

**Comment by phbernard** [comment]
Will be implemented as part of issue #99. Thus this issue is not "duplicated" but rather "merged".

**Comment by phbernard** [comment]
Done and deployed a minute ago.

![image](https://cloud.githubusercontent.com/assets/423852/5896818/36cfe952-a53c-11e4-8643-8e7204e2f13b.png)

**Comment by phbernard** [comment]
Done and deployed earlier today!
