### ISSUE TITLE
Favicon Checker - One website OK, One with many errors

### ISSUE THREAD

**Issue by Ronald11103** [RealFaviconGenerator/realfavicongenerator#109]
I'm webmaster for two non-profit organizations. I used RealFaviconGenerator to generate the various favicons for both sites. Using Favicon Checker, one website checks perfect (www.amervoyassoc.org) and the other (www.lakecreekcamp.com) shows many errors, yet all of the files exist in the root directory. Amervoyassoc is hosted at Hostmonster.com and lakecreekcamp is hosted at Godaddy.com, if that makes any difference. I recreated the favicons and uploaded the new ones (which look identical to the originals) and still get the errors with the checker on lakecreekcamp.com. I have no idea what to do next??

**Comment by phbernard** [comment]
Hi Ronald,

Wow, I'm very sorry for this late answer... :-/

I've just run the test against both sites: perfect, full green! So I suppose you found the solution?

**Comment by phbernard** [comment]
Let's suppose "no news is good news" :) Don't hesitate to reopen if the issue is not fixed.

**Comment by Ronald11103** [comment]
Thanks for the reply phbernard and I'm sorry about taking so long to get back to you. I was (am) getting so many emails daily from realfavicongenerator via github on so many subjects I didn't know what was going on. Think I've got it figured out. And yes, the icon tests are working fine. Thank you!
