### ISSUE TITLE
Output html5 tags instead of incorrect xhtml

### ISSUE THREAD

**Issue by tahajahangir** [RealFaviconGenerator/realfavicongenerator#11]
Current html output of realfavicongenerator is as follows:

```
<link rel="shortcut icon" href=".../favicon.ico">
<link rel="apple-touch-icon" sizes="57x57" href=".../apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="114x114" href=".../apple-touch-icon-114x114.png" />
```

The first tag is not self-closing, but others are.
There is better not to use self-closing tags at all, browsers are parsing response as xhtml, only if it's `Content-Type` be `application/xhtml+xml` (which is very rare). If the content type be `text/html`, the document shoud be HTML not XHTML.

see: http://www.w3.org/TR/xhtml-media-types/#application-xhtml-xml

**Comment by phbernard** [comment]
You're right, this is a bit messy and not accurate. Thank you for reporting!

The update is easy, testing will require more time. I will address this next week.

**Comment by phbernard** [comment]
Done and deployed. See http://realfavicongenerator.net/change_log
