### ISSUE TITLE
Chrome dev summit news

### ISSUE THREAD

**Issue by dvorapa** [RealFaviconGenerator/realfavicongenerator#111]
According to the chrome dev summit, the optimal favicon size is 192x192 for icon like `<link rel="icon" sizes="192x192" href="highres.png">` to show it in chrome mobile (and maybe also in chrome desktop) perfectly. And the website can change mobile chrome theme color (heading with tabs and address bar) by `<meta name="theme-color" content="#0D6AB7">`. Just saying :-)

**Comment by phbernard** [comment]
Thanks for reporting!

The theme thing is already addressed in issue #108. Plus there is a new manifest for Android Chrome M39, that's issue #99.

I'm surprised you mention the 192x192 icon, because it is already generated. Did you spot something wrong in the package generated by RFG?

**Comment by dvorapa** [comment]
I haven't found any bug or issue in the package yet. The whole RFG is really amazing tool. I just wrote what I note down from the extract from that summit. And if it is already implemented or if it is not implemented, but already listed in the issue tracker, feel free to close this issue immediately ;-)

**Comment by phbernard** [comment]
Wow! I'm usually faster at closing issues :)

Ok great, come back in a few days (well, weeks), everything should be available!
