### ISSUE TITLE
No HTML returned when open_graph included.

### ISSUE THREAD

**Issue by johncook** [RealFaviconGenerator/realfavicongenerator#113]
When I add an open_graph section to the non-interaction API request, I get `"html_code": null` returned.

Partial request code:
`"open_graph": {
                "picture_aspect": "background_and_margin",
                "background_color": "#00aba9",
                "margin": "8%",
                "ratio": "1.91:1"
            },`

When I remove this section, the html returns as expected.

**Comment by phbernard** [comment]
Thank you for spotting this one.

The reason why it fails is (probably) that you submit a picture that is too small. Open Graph picture is expected to be quite big and RFG does not generate anything below 300x300. This case was just not anticipated and you caught a bug.

There are different ways to fix this issue:
- Raise an error. After all, you want an icon and RFG won't generate it. This is the easiest way to deal with such case.
- Do as if nothing happened. The package doesn't contain the icon, the HTML doesn't declare it. There are certainly cases where this behavior is interesting.
- Add a parameter to the JSON request so the caller can choose a behavior or the other.

I will probably probably let the user choose. That should be ready in a few days. In the meantime, you can submit a larger picture just for the sake of making it work.

**Comment by phbernard** [comment]
Fixed and deployed a few hours ago. Use the <a href="http://realfavicongenerator.net/api/non_interactive_api">`error_on_image_too_small`</a> setting to switch from a behavior to the other.
