### ISSUE TITLE
message: oops, something went wrong wth the compression 

### ISSUE THREAD

**Issue by mialally** [RealFaviconGenerator/realfavicongenerator#114]
Using the plugin in Wordpress, after selecting a 260x260 image from my computer, I got the following message "oops, something went wrong with the compression ". 

this is the image:

![favicon260x260](https://cloud.githubusercontent.com/assets/10028960/5247140/ddcc1fa8-793d-11e4-9c7c-01aa232065f6.jpg)

**Comment by phbernard** [comment]
I have a feeling of déjà vu, did we meet somewhere else? :)

Issue fixed yesterday. Thanks again for reporting it!
