### ISSUE TITLE
WordPress Error

### ISSUE THREAD

**Issue by Quasar-QSO** [RealFaviconGenerator/realfavicongenerator#115]
An error occured: Cannot download JSON file at http://realfavicongenerator.net/files/15937ab2fbb2a46916712e2f41cdf6a6e03bc5d3/json_result.json: couldn't connect to host

I keep getting this message at the end of the setup process in WordPress. I can get the file directly from the URL if I put it in the browser address bar but then I have no idea what to do with it. 

What should I do to fix this?

**Comment by phbernard** [comment]
Sorry for the inconvenience.

This is strange... My hypothesis is that your WP host is not allowed to connect to RealFaviconGenerator for some reasons. How is your WP site hosted? I suppose it is not self-hosted?

**Comment by Quasar-QSO** [comment]
No, it's not self-hosted. I have a company I pay for hosting. Is there another way to get the files in the correct location so I can get the favicons to work?

**Comment by phbernard** [comment]
Well, as a workaround, you can use RealFaviconGenerator.net as a standalone service, without the WP plugin. Follow the <a href="http://codex.wordpress.org/Creating_a_Favicon">WP Codex</a> for instructions (obviously, replace the sample code of the Codex by the code delivered by RFG).

If you are still willing to use the plugin:
- Do you have some security plugins of some kind? One of them might prevent the other plugins from establishing outgoing connections. If so, try to disable this option.
- Your hosting server may prevent outgoing connections. Unlikely, but it's worth asking.
- Can someone watch the Apache error log while you are reproducing the error? I wouldn't pay someone to do this, but if the support is included in your package, again, it's worth trying.

**Comment by phbernard** [comment]
Did you want to investigate this issue or can I close it?

**Comment by phbernard** [comment]
I close the issue. However, don't hesitate to reopen it if you get additional feedback.
