### ISSUE TITLE
Favicon Checker reports missing icons even after using RealFaviconGenerator

### ISSUE THREAD

**Issue by designerdean** [RealFaviconGenerator/realfavicongenerator#117]
I used the Real Favicon Generator to create the icon images, deployed them to my website, and ran the Favicon Checker. Multiple checks come back as negative.

![screen shot 2014-12-07 at 9 39 24 am](https://cloud.githubusercontent.com/assets/729893/5331735/f61e365c-7df4-11e4-8b35-98a38281d0a8.png)
![screen shot 2014-12-07 at 9 39 18 am](https://cloud.githubusercontent.com/assets/729893/5331737/fa159e62-7df4-11e4-9110-cac35b08a66f.png)

**Comment by phbernard** [comment]
Hi Josh,

Can you give me your web site URL for review? You can mail it to me at philippe@realfavicongenerator.net if you don't want to disclose it here.

**Comment by designerdean** [comment]
Yes, I'll email it to you right now. Thanks!

**Comment by phbernard** [comment]
(you sent me the URL, I reviewed the site)

Apparently, the picture files generated by RFG were changed. For example: `apple-touch-icon-57x57.png` was renamed to `apple-touch-icon-57x57-15797a5e.png`. The HTML code was updated accordingly, so this is fine.

However, the `browserconfig.xml` file also contains references to the pictures, and this file should have been updated, too. If you fix the names in that file, everything should work.

**Comment by nemezisik** [comment]
same thing right here. generated icons from Real Favicon Generator cant be verified by Favicon Checker. check this url http://bitrix.otdelochnik.biz

**Comment by designerdean** [comment]
@phbernard Thanks for looking into it! Adding those cache-buster filenames is a feature of the static site generator I'm using (Middleman). I'll have to look into seeing how it can update those references on build as well. Thanks again!

**Comment by phbernard** [comment]
You're welcome @designerdean!

@nemezisik, I've checked your web site. Everything looks fine, but the parsing of your homepage fails. I think this is due to the encoding (I admit I didn't really tested the checker against Cyrillic characters). On my local instance of RFG on my laptop, the check passes: everything is green. Lovely. So it needs further investigations. On my TODO list for the next week.

**Comment by phbernard** [comment]
Ok I'm really behind schedule... I'll try to address this early in January.

**Comment by TrackerSB** [comment]
My website is traunviertler-traunwalchen.de. I´ve got the same issue.
I generated favicons with a 400pxx400px-picture. And I wanted to "joy the green report" (See your FAQ) and it isn´t.
Is it causing trouble to generate the generated sourcecode auf realfavicongenerator.net over js? But most entries are still green.

**Comment by rbashish** [comment]
My site is giving 2 favicon, one used with www and other with non-www. The www gives original favicon but non-www gives google favicon. What is the problem with my site? Any help would be highly appreciated. Thanks.

**Comment by tariqkhan-co-uk** [comment]
The generator doesn't seem to be working? Used it only a week ago?

**Comment by cbdavide** [comment]
Hi!!
I have a question, does the Favicon Checker works on Github Pages ?

**Comment by phbernard** [comment]
@EvalTracker The checker itself doesn't deal with JS. From its point of view, this is as if you didn't have any markup related to favicon. I really don't know if browsers support this JS trick. However, your favicon will often work because you put all the files in the root directory. So IE will find `/favicon.ico`, iOS will find `/apple-touch-icon.png`, etc.

@rbashish What is the URL of your site?

@tariqkhan-co-uk Oops! As far as I know, it works well. What happens on your side?

@cbdavide Nope. Plain old self-hosting.

**Comment by rbashish** [comment]
I have **solved** my problem @phbernard. Thanks for Asking.

**Comment by Tathanen** [comment]
Hey @phbernard, bumping old issue here, but seemed the most appropriate.  When I run my site through the checker (https://wall.vokal.io/) it comes back as basically nothing being correct.  It's got a pretty stock installation from realfavicongenerator running on it, and the icons show up when I actually use the site, etc.  But the checker hates it.  Any ideas?

**Comment by phbernard** [comment]
@Tathanen Apparently your server always returns gzip-encoded data (ie. `Content-Encoding: gzip` in the headers), even when the client doesn't indicate `accept-encoding: gzip` in the request. Although this is harmless with modern browsers, the lib used by the checker can't deal with this and processes the gzipped content as it was raw HTML. Errors ensued.

I won't fix this right now, but at least you know what's going on.

**Comment by Tathanen** [comment]
Aha!  Well that's good to know, thanks.

**Comment by sandebert** [comment]
Hi @phbernard, I gave RFG a go and did all according to the instructions and yet I did not get the joy of the green test. I'll send you an email with my URL.

**Reported errors:**
- Generic favicon: Missing some sizes
- iOS favicon: Some PNGs missing
- Windows 8 favicon: Pic for Win8 / IE tile not declared

**Comment by phbernard** [comment]
This is because your homepage has no favicon markups, unlike your login page which is "full green". Maybe you didn't update your homepage layout or something?

**Comment by sandebert** [comment]
Ugh... Yes, that's it. Thanks for helping out. :)

**Comment by phbernard** [comment]
You're welcome!

**Comment by GeorgeWL** [comment]
I seem to be having this issue too. Drupal installation using https://www.drupal.org/project/responsive_favicons 

When I look in the head in inspector however, the files do seem to appear.

www.mtmllp.co.uk if you would like to see if you can solve?

**Comment by phbernard** [comment]
I can't see the icon declarations anywhere in the code of your homepage, so I suppose the Drupal plugin didn't inject the code properly. I'm not part of this project, so I suggest you report this to the responsive_favicons's team.

**Comment by GeorgeWL** [comment]
Weirdness, guessing it's a odd behaviour of Drupal, but they decided to load in the next day, as in on check again, they're all there.

**Comment by phbernard** [comment]
I've just ran the checker and got the same positive result. I definitely don't know what happened.

**Comment by phbernard** [comment]
This issue has been opened for a while and was used to address several different problems. I close it and expect future, similar problems to be submitted as new issues.
