### ISSUE TITLE
Add Query Params to Path

### ISSUE THREAD

**Issue by hyyan** [RealFaviconGenerator/realfavicongenerator#118]
It would be nice if we could add query params to the final path for example `?ver=1.0` .

Thanks

**Comment by phbernard** [comment]
Hi Hyyan,

Thanks for the suggestion. You mean something like #116?

**Comment by hyyan** [comment]
@phbernard  Hi , thanks for replay , that's right , this is what I mean . It just would be great to have such a feature

**Comment by phbernard** [comment]
Alright! I close this one.

**Comment by phbernard** [comment]
Done!

**Comment by hyyan** [comment]
@phbernard  Great , I've been waiting for such a feature , thanks for the great work :smile:
