### ISSUE TITLE
Icons generated from a .svg file do not match the original.

### ISSUE THREAD

**Issue by dgbutterworth** [RealFaviconGenerator/realfavicongenerator#119]
Thanks for a terrific asset.  When I submitted a .png file, it worked perfectly.  Thanks also for your write up and explanation of the subject at http://stackoverflow.com/questions/2268204/favicon-dimensions - found in my search to check on the proper size.  Now I have all the proper sizes, and code.  Wonderful!! (particular because this is not what I ussually do, so it takes me forever to get through it.)  I attach the original .png and an example of the excellent resulting .ico files.

But a headsup:  I first submitted my icon file as an .svg file, generated in Inkscape.  The generated icons did not resemble my painstaking art(?)work in any common sense of precision.  I attach my original and one of the generated icons.

[It won't accept the .svg file - but my .png and the 2d_better_favicon.png show what it looks like.]

![dgb-icon-blknblu_260x](https://cloud.githubusercontent.com/assets/1182819/5425706/6022c752-82f0-11e4-85b2-471cf67ebd6d.png)
![first-from-svg_favicon-192x192 copy](https://cloud.githubusercontent.com/assets/1182819/5425714/b0511ae4-82f0-11e4-94a0-1cea51097479.png)
![2d_better_favicon-192x192](https://cloud.githubusercontent.com/assets/1182819/5425716/d59e1e28-82f0-11e4-8d4c-8b9329857dcc.png)

**Comment by phbernard** [comment]
Thank you for your feedback!!

Currently, RFG relies on ImageMagick to process SVG pictures. Not sure this is the right choice. Maybe Inkscape as a command line tool might produce better results.

Could you send me your SVG picture at philippe@realfavicongenerator.net?

**Comment by phbernard** [comment]
Did you have the opportunity to mail me the picture? I don't think I received it.

**Comment by dgbutterworth** [comment]
Sorry, holidays and other stuff have kept me away.  Other stuff includes installing and learning linux (Mint 17.1 - migrating from WinXP).  And in my deep exploration of Mint, I have broken it several times, including right now.  (Only the cursor displays - very strange but I've actually been here before.  But last time I was "learning" about video drivers/config - so the break was not unexcpected.  This time, I didn't make any big changes - a few minor tweaks to cinnamon settings.  But I'll learn more as I puzzle this one out. And as soon as I do, I'll send on the SVG pics.
Happy New Year!

**Comment by phbernard** [comment]
(already discussed by email but...)

Just to let you know that RFG switched to Inkscape. I hope that fixes everything at once.

**Comment by rugk** [comment]
So is this actually fixed? Can it be closed?

**Comment by phbernard** [comment]
I guess so. I have had several issues with SVG in the past so I wanted to keep it open just in case. More than a year later, I guess we can take this hard decision :)
