### ISSUE TITLE
Changing the picture for Windows 8 changes generic and iOS pictures too

### ISSUE THREAD

**Issue by MoonSweep** [RealFaviconGenerator/realfavicongenerator#123]
Hi,

I'm not sure if this is specific to the WordPress plugin or if it happens without it too.

I have a very simple white on black favicon, but I want to use only the white region for WIndows 8. So I created a specific picture with all black regions changed to transparent, and selected it only for Windows 8, but when I generate the favicons, the transparent one is used for iOS and generic favicon too.

![capture-favicon generator - generate favicon pictures and html - iceweasel](https://cloud.githubusercontent.com/assets/8300411/5557259/e013bf24-8cf6-11e4-91fb-af962d505917.png)
![capture-favicon le blog de raph wordpress - iceweasel-1](https://cloud.githubusercontent.com/assets/8300411/5557264/40b5f2f2-8cf7-11e4-893f-73475d578728.png)

Is it a bug or expected behavior ?

**Comment by phbernard** [comment]
Damn. Definitely a bug. Thank you for reporting this bad boy.

I reproduced the issue. It occurs only:
- With the interactive API (ie. WordPress), not with the regular interface.
- By submitting a picture from the WordPress plugin (not by picking the picture once on RFG)
- By choosing to use a dedicated picture for W8 or (ie. simply uploading a dedicated picture then choosing another option, such as "white silhouette", does not trigger the bug).

The bug also occurs with iOS, it's not specific to Windows.

I'm running out of time for today, but I'll definitely fix this soon.

**Comment by phbernard** [comment]
Ok, I found the culprit and fixed it. But I now need to do some testing to make sure nothing is broken.

**Comment by MoonSweep** [comment]
Wow ! I didn't think you'd fix it so fast. If I can help with the tests, feel free to ping :)

**Comment by phbernard** [comment]
The fix was deployed a minute ago. All tests are passing on my side. Could you retry?

(the fix is server-side; no need to update the plugin or whatever)

**Comment by MoonSweep** [comment]
It works perfectly. Thank you for fixing it so quickly !
![capture-favicon le blog de raph wordpress - iceweasel](https://cloud.githubusercontent.com/assets/8300411/5561827/52a08726-8df5-11e4-979e-ff3b75ea91db.png)

**Comment by phbernard** [comment]
You're welcome! I'm the one who need to thank you: this issue was here from day 1. Without your report, it could have been here for long.
