### ISSUE TITLE
Invalid Circle, "Keep in circle", 60x60 Firefox OS icon

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#126]
The following master picture leads to an invalid 60x60 Firefox OS icon. This happens when creating a "Circle" icon with the "Keep in circle" option.

The master picture:

![full-logo](https://cloud.githubusercontent.com/assets/423852/5677941/38f92524-97ed-11e4-8d10-4340225fcc8a.png)

128x128 icon (correct):

![firefox_app_128x128](https://cloud.githubusercontent.com/assets/423852/5677965/841469e2-97ed-11e4-8c78-40dfd2a41c3a.png)

60x60 icon (wrong):

![firefox_app_60x60](https://cloud.githubusercontent.com/assets/423852/5677968/905c280c-97ed-11e4-9f3b-4f720c2f1f2d.png)

The issue appears when masking the master picture in order to keep it within the circle. For some reasons, that works well with 128x128 icon but not with 60x60. Apparently, <a href="http://www.imagemagick.org/Usage/bugs/composite_mask/">IM has known issues with masking with transparency</a>.

**Comment by phbernard** [comment]
Reported by @haydenbleasel

**Comment by phbernard** [comment]
Fixed and deployed a minute ago.

The "fix" is clearly not satisfying: the 60x60 icon is not generated anymore, replaced by a new 256x256 icon. Unfortunately, there is a risk that the issue will happen again with another master picture and another icon size.

The <a href="https://github.com/RealFaviconGenerator/realfavicongenerator-api-test-suite">API test suite</a> was updated and a verification test was added in `FirefoxAppTest#test_issue126`.

As specified, <a href="https://developer.mozilla.org/en-US/Apps/Build/Manifest">an icon sized 128×128 required for all app manifests and icon sized 512×512 recommended for all app manifests</a>, a sign that the 60x60 is not that useful. In addition, after some experiments with the Firefox OS Simulator, the manifest does not support more than 3 icons (the manifest is declard invalid when more icons are presented).

@haydenbleasel, could you retry to make sure everything is fine on your side?

**Comment by haydenbleasel** [comment]
Hey mate,

60x60 is no longer produced but I'm afraid this happens with 128x128 as well. Also, not sure what the styling is meant to be like but you can see what's happening on the larger ones.

Note: This could be due to the [default configuration](https://github.com/haydenbleasel/favicons/blob/node/index.js#L174) on Favicons.

![firefox_app_128x128](https://cloud.githubusercontent.com/assets/4142719/5678654/c0336062-9848-11e4-9eb4-bb5c1e38861d.png)
![firefox_app_256x256](https://cloud.githubusercontent.com/assets/4142719/5678656/c10cf4d0-9848-11e4-96e9-53f96ba44e68.png)
![firefox_app_512x512](https://cloud.githubusercontent.com/assets/4142719/5678657/c10e78a0-9848-11e4-8adf-784c3fd76b3a.png)

**Comment by phbernard** [comment]
Wow, this one was really annoying. The bug showed up with `circle_inner_margin` to `5` but with `3`... I updated the verification test.

I think I have a winner. The verification test passes and I also tested close values.

And the 60x60 icon is back, whereas the 256x256 disappeared.

**Comment by haydenbleasel** [comment]
Awesome! Assuming the effect is correct then I think we're good!

![firefox_app_60x60](https://cloud.githubusercontent.com/assets/4142719/5689612/d4938dec-98bc-11e4-9349-1e37b4e00365.png)
![firefox_app_128x128](https://cloud.githubusercontent.com/assets/4142719/5689613/d4be9f0a-98bc-11e4-9d71-9c8b8e18969a.png)
![firefox_app_512x512](https://cloud.githubusercontent.com/assets/4142719/5689614/d4c049d6-98bc-11e4-8751-31f893a91269.png)

**Comment by phbernard** [comment]
Great! The bliss of closing an issue before going to sleep :)
