### ISSUE TITLE
iOS startup image support in API

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#127]
RFG should support the iOS startup picture in API.

See https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html and https://gist.github.com/tfausak/2222823

**Comment by phbernard** [comment]
Done and deployed yesterday.

Thank you @tfausak for https://gist.github.com/tfausak/2222823, that was very helpful!

**Comment by tfausak** [comment]
:+1: I'm glad it helped!
