### ISSUE TITLE
Windows8.1 tile background is not set correctly

### ISSUE THREAD

**Issue by yaroslavya** [RealFaviconGenerator/realfavicongenerator#129]
I`ve created a test website, using the RealFaviconGenerator: http://yaroslavya.github.io/w8tile/
When I check if everything is ok, regarding the windows 8.1 it says that tile background is set correctly. When I try to add the site to the tiles the background is different (usually set some gray one or the one that is used by default). Is there anything I miss here?

**Comment by yaroslavya** [comment]
Some update on the behavior I see:
The background that I set seem to be ignored and the color that is defined by the image is taken instead.
By defined by the image I mean some intermediate color that look close to the image color, but still its not even close to the color I set in the msapplication-TileColor meta tag.
Also, I tried examples from the http://pinnedsitedemo.cloudapp.net/testdrive/index.aspx
and they show the exact same behavior I described above. Also tried theverge.com, which was referenced by Scott Hanselmann as the site that implements windows 8.1 tiles and it ignores the tile color in the same way(color is based on the image).

One more thing: msApplication notification urls doesnt work as well. I also checked the Scott Hanselmanns blog. And could not get any notification updates from it.

**Comment by phbernard** [comment]
Hi Yaroslav,

Hum... strange. First thing first: which kind of device are you using to test the icon? I personally use a Microsoft Surface 2 with Windows RTM 8.1. Although I didn't run any test today (its batery is low right now), it usually works fine: the background color is used as specified.

I couldn't find anything at http://yaroslavya.github.io/w8tile : neither favicon code nor downloadable package. Did I miss something?

Something else: during your experiments, I suppose you played with the code generated by RFG. Did you use only an HTML markup (eg. `<meta name="msapplication-TileColor" content="#ffc40d">`) or did you combine it with a `browserconfig.xml` file (eg. `<TileColor>#ffc40d</TileColor>`)?

**Comment by yaroslavya** [comment]
Hi, Philippe!

I use dell xps 15 notebook with Windows 8.1 and IE11 and Samsung NP700G7CT02RU with Windows 8.1 and IE11.

Just tried to access http://yaroslavya.github.io/w8tile/favicon.ico and it gave the favicon for me.
Just an example from http://theverge.com - here is their metatag: <meta name="msapplication-TileColor" content="#000000">
and the tile color is nothing like black.

Also, if you open this example from: http://pinnedsitedemo.cloudapp.net/testdrive/index.aspx?6=6
the tile color in meta is set to some kind of gray color. But when I add it I have a green tile.
Do you have other results? What device are you using?

And I dont see any tile updates on any of the sites, including theverge.com. Do I need to turn them on somewhere?

UPDATE: Just went to shop and checked their windows surface. Added the verge website and there were no updates for it. So just a static tile.

**Comment by phbernard** [comment]
I'm using a Microsoft Surface 2. It run W8.1 RT. I insist on the "RT": this is really the "tablet" experience, not the crappy Start-menu-is-back-but-all-you-get-is-that-silly-desktop-you-can't-really-use-with-a-mouse-anyway.

With the Surface, everything works as expected:

When pinning RealFaviconGenerator, its specified background color is used:

![image](https://cloud.githubusercontent.com/assets/423852/5998654/17c1b2fa-aaca-11e4-8ada-40a882e4d7a0.png)

When pinning TheVerge.com, I get a suitable background color:

![image](https://cloud.githubusercontent.com/assets/423852/5998672/3d9737de-aaca-11e4-9be3-6b8b66df35e0.png)

And the created tile is dynamic:

![image](https://cloud.githubusercontent.com/assets/423852/5998679/52c969a6-aaca-11e4-9b8d-f8f07cd8f317.png)

Regarding the dynamic tiles, I really can't help. I'm only an icon guy :)

And regarding the color, maybe that comes from your device. Does it have a touch screen, or is it a classic mouse & keyboard PC? I know MS failed to unified the classic desktop and tablet experiences in this settings.

**Comment by yaroslavya** [comment]
Philippe, just figured it out!
Two things:
1. IE should be the browser by default to make live tiles work.
2. You should pin from the IE that is in metro mode, not in the desktop mode.

With these two it works, I see the background and the live tiles. If I miss any of these I either dont have a background or live tiles or both. So the issue can be closed. Hope will be helpfull for anyone who have the same issues. Probably its just that I dont use metro, even if I have Windows 8.1 and touch screen device.

**Comment by phbernard** [comment]
Okay, now I get it. I think my Surface 2, is Metro by default, which perfectly makes sense with this tablet product. Whereas Desktop mode is probably more suitable with your PC.

I was completely unaware of all this so thank you very much for the investigations!
