### ISSUE TITLE
Generator is broken

### ISSUE THREAD

**Issue by bryanbatcher** [RealFaviconGenerator/realfavicongenerator#133]
When I generate my favicon, it doesn't always work in my browser and there are places it doesn't work. When I use the "check your favicon" tool, I get error messages for all favicons except ios. This started with the new update.
![screenshot 2015-02-04 02 13 40](https://cloud.githubusercontent.com/assets/10844264/6036496/b992b88c-ac13-11e4-9c20-2a22dfa9b884.png)
![screenshot 2015-02-04 02 13 49](https://cloud.githubusercontent.com/assets/10844264/6036497/b9964d58-ac13-11e4-9d82-5e3c691b11a1.png)
![screenshot 2015-02-04 02 14 00](https://cloud.githubusercontent.com/assets/10844264/6036498/b998f454-ac13-11e4-9e17-af89169a44dc.png)

**Comment by phbernard** [comment]
Do you have issues when generating your favicon? Or only when using the checker? In the first case, can you describe what happens?

Regarding the checker, could you give me the URL of your site for review? If you don't want to disclose your URL here, you can mail it to me at philippe@realfavicongenerator.net

**Comment by bryanbatcher** [comment]
http://www.zordonsboy.com

The generator works fine when I use it, but the favicon sometimes doesn't show in my browser and it doesn't show up on youtube where custom links are. It used to.

**Comment by phbernard** [comment]
I see your site is under development. Do you use a kind of "coming soon" WordPress plugin that hides your site to regular visitors like me? If so this is the likely cause of your issues: everyone (me, RFG's checker, YouTube...) just see a nearly empty page, which doesn't contain the markups generated by RFG.

**Comment by bryanbatcher** [comment]
Ha, whoops. Forgot that was on. It's off now.

**Comment by phbernard** [comment]
Full green! :)

http://realfavicongenerator.net/favicon_checker?site=http%3A%2F%2Fwww.zordonsboy.com%2F&ignore_root_issues=on
