### ISSUE TITLE
Cannot type colour for Android Chrome favicon

### ISSUE THREAD

**Issue by ChrisPhilpot** [RealFaviconGenerator/realfavicongenerator#139]
When I try to enter the background colour for the Android Chrome favicon by typing in a hex code, it does not update the preview. You can only change the colour by dragging your mouse, which is not particularly accurate.

**Comment by OnkelTem** [comment]
I confirm this.
Example:
![06d960e90a1caec6658728365fd290ec](https://cloud.githubusercontent.com/assets/114060/6424728/7b898b6e-bf15-11e4-9e64-9d1f8186de95.png)
Background color is set to red (#ff0000) by manually typing digits, while preview is not updated and is still white.
At that, picking color from color map does work.

**Comment by phbernard** [comment]
That's right!

Fixed and deployed a minute ago.
