### ISSUE TITLE
The FAQ does not tells what the manifest.json file is for

### ISSUE THREAD

**Issue by oliverpool** [RealFaviconGenerator/realfavicongenerator#148]
Maybe you could simply add:

**What is `manifest.json` ?**
[Android uses `manifest.json`](https://developer.chrome.com/multidevice/android/installtohomescreen#supporting)...

---

Just like the `browserconfig.xml` explanation, but linking to https://developer.chrome.com/multidevice/android/installtohomescreen#supporting

**Comment by phbernard** [comment]
That's right. Thanks for reporting!

Added and deployed a minute ago.
