### ISSUE TITLE
Add 180x180 version for iPhone 6 Plus

### ISSUE THREAD

**Issue by realityking** [RealFaviconGenerator/realfavicongenerator#150]
I haven't tested it yet, but according to Apple for the iPhone 6 Plus an Icon with 180x180 pixel is needed.

Source: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27

**Comment by realityking** [comment]
Never mind, I see it's already being generated.

Sorry for the noise.

**Comment by phbernard** [comment]
Hey, you didn't let me write my answer! :)

That was added in September 2014, not long after the release of the iPhone 6.
