### ISSUE TITLE
Generated Favicon but not appearing and getting errors

### ISSUE THREAD

**Issue by smapke** [RealFaviconGenerator/realfavicongenerator#152]
Hi, I've generated the favicon and added it to my website but I am still getting errors when checking it and the favicons are not showing up. I looked at the FAQ and I used the correct master image size and it is in the root directory. Do you have any ideas as to what may be the issue? I can give the url privately. 

Generic Favicon
favicon.ico seems corrupted or not in ICO format.

Some picture(s) are missing in favicon.ico:
16x16 picture
32x32 picture
48x48 picture
Learn more

Some recommended PNG favicons are missing (or their sizes attribute is not set):
16x16 picture
32x32 picture
96x96 picture
192x192 picture

iOS Favicon
Some iOS pictures are not declared:
114x114 picture
72x72 picture
144x144 picture
60x60 picture
120x120 picture
76x76 picture
152x152 picture
180x180 picture

Windows 8 Favicon
Picture for Windows 8 / IE 10 tile is not declared.

**Comment by phbernard** [comment]
Sure, please mail me the URL at philippe@realfavicongenerator.net

**Comment by smapke** [comment]
We solved the problem, it was on our end. For some reason when we access via https it does not work but it works when we go in through http so it is something wrong with our ssl sert. Thanks for looking into this!

**Comment by phbernard** [comment]
You're welcome! I guess I could have closed this issue earlier :)
