### ISSUE TITLE
manifest.webapp

### ISSUE THREAD

**Issue by saruman** [RealFaviconGenerator/realfavicongenerator#161]
Hello.
I noticed that the manifest.webapp doesn't come include on the html_code.html, can you add the meta tag for that? similar to manifest.json?

Why the other manifests are included and not firefox's manifest?

Thank you.

**Comment by phbernard** [comment]
This manifest is not for browsers but for the Firefox Markeplace only. You are supposed to declare it when you register your site to the store (by copying/pasting to a form; no HTML stuff here).

By the way, this is not the manifest not declared in the HTML code: `browserconfig.xml` is expected to be in the root directory. It is declared only when placed elsewhere.

**Comment by saruman** [comment]
Thank you for let me know that.
I got it.

**Comment by phbernard** [comment]
Welcome!
