### ISSUE TITLE
"Use existing" on Android and Firefox manifest override

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#162]
The non-interactive API allows user to submit an existing Android and Firefox manifest. When such manifest is submitted and there is a conflict between the this manifest and what RFG is about to do, the `error_on_override` guides the behavior. However, this parameter does not allow the user to keep an existing value from the existing manifest.

A new `on_override` parameter should be introduced. Possible values:
- `keep_existing`: keep the existing value. RFG's new value is ignored. This behavior is not possible at the moment.
- `use_new`: use the value provided by RFG and drop the existing one. Equivalent of `error_on_override` set to `false`.
- `error`: throw an error. Equivalent of `error_on_override` set to `true`.

**Comment by saruman** [comment]
When this new parameter will be avaiable?

**Comment by phbernard** [comment]
I'm working on it. Probably ready tomorrow.

**Comment by phbernard** [comment]
Done and deployed a minute ago.

The new parameter is called `on_conflict` and can be `raise_error`, `override` or `keep_existing` (the one you need). See http://realfavicongenerator.net/api/non_interactive_api for full doc.

**Comment by saruman** [comment]
Awesome, thank you!

**Comment by phbernard** [comment]
Great! That's one more closed issue :)
