### ISSUE TITLE
SVG and theme color support in Safari 9

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#169]
See https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW20

**Comment by realityking** [comment]
I'd hold off on that for a while. apparently it's still subject to change. See https://lists.w3.org/Archives/Public/public-whatwg-archive/2015Jun/0020.html

**Comment by phbernard** [comment]
Thank you for reporting the possible change in the declaration. Skimming through the conversation, I think the changes to be expected are mostly in the HTML part, which it not an issue: the generator can be updated in no time. The look-and-feel shouldn't change, and that's the most important for me, since changes in this part are much more demanding. So let's roll!

Step 1 of 2: the API. It's done. The new `safari_pinned_tab` entry let you design and generate the new SVG icon.

**Comment by phbernard** [comment]
Done!

![image](https://cloud.githubusercontent.com/assets/423852/10490009/4e50504a-729f-11e5-80a1-a6e1bf5aa74f.png)
