### ISSUE TITLE
Adding cross-origin resource sharing (CORS) headers to generated files

### ISSUE THREAD

**Issue by cdcarson** [RealFaviconGenerator/realfavicongenerator#170]
Hi,

Great service. Thanks. 

I'm developing an application in pure client side Javascript -- no server application code. 

I'd like to use the Interactive API to allow my users to use your service to create icons for their installations of my app. Unfortunately, I'm having trouble retrieving the generated assets from my client javascript -- the "same-origin" restriction means that I can't grab the zip file from your server. There are hacky ways around this, but...

Is there any way you can add CORS headers to the directories containing the generated assets? I think this is a relatively easy config in Apache or nginx, e.g., in Apache, adding the header to all files under `/files`...

```
<DirectoryMatch /files/*>
    <IfModule mod_headers.c>
        Header set Access-Control-Allow-Origin "*"
     </IfModule>
</DirectoryMatch>
```

Other examples are here... http://enable-cors.org/server.html

Let me know if this is possible.  Happy to help any way I can. Thanks,

Chris

**Comment by phbernard** [comment]
Done and deployed a minute ago.

I checked the headers, `Access-Control-Allow-Origin` is present as expected. Yet I wait for your feedback to close the issue.

If you build something with the API, please drop me an email. I'll be glad to advertise it!

**Comment by cdcarson** [comment]
This is perfect -- I've tested $.getting the files pretty extensively. Everything seems fine. Thanks!  

I'll shoot you a link to show how I'm using the API as soon as I get my product out -- a couple of weeks.

Thanks again.

**Comment by phbernard** [comment]
Great! I'm eager to try this!!
