### ISSUE TITLE
Text error on the main website

### ISSUE THREAD

**Issue by kevinvanrijn** [RealFaviconGenerator/realfavicongenerator#171]
Couldn't find a propper location to report errors on the main website so I'm doing it here.
Under Windows 8 Favicon, background is spelled as 'bakground'.

Image: https://imgur.com/zsCaaEI
Example: http://realfavicongenerator.net/favicon_checker?site=example.com#w8_tile_background_color

**Comment by phbernard** [comment]
Fixed and deployed a minute ago.

Yep, that was the right place for this. Thanks for reporting!
