### ISSUE TITLE
I had to delete your plugin manually via FTP as it broke my sites 

### ISSUE THREAD

**Issue by semmycom** [RealFaviconGenerator/realfavicongenerator#172]
Please check your update that you did today. I had to remove it as my sites were instantly defunct and displaying coding errors that your plugin causes a problem to load wordpress

**Comment by phbernard** [comment]
Damn! Thank you for reporting.

I didn't encounter any issue while testing the plugin. Which kind of error did you get?

**Comment by semmycom** [comment]
let me reinstall the plugin and make a screenshot

**Comment by semmycom** [comment]
I can't even install your plugin now anymore.

I get this error: Plugin could not be activated because it triggered a fatal error.

**Comment by semmycom** [comment]
I first noticed as I did upgrade your plugin via my InfiniteWP dashboard and all of a sudden my sites were no longer connected to InfiniteWP (an external wordpress management panel I use for years now, should not be the problem).

**Comment by semmycom** [comment]
I use the latest wordpress version, all other things are up to date.

**Comment by semmycom** [comment]
Here is the error that shows on the site now:

Parse error: syntax error, unexpected '[' in /home/semmy6/public_html/wp-content/plugins/favicon-by-realfavicongenerator/public/class-favicon-by-realfavicongenerator-common.php on line 190

**Comment by phbernard** [comment]
I think that should be fine now. I was reported the issue <a href="https://wordpress.org/support/topic/favicon-plugin-crashed-my-blog">here<a/> and It'e just released v1.3.1.

**Comment by phbernard** [comment]
Ok, this is the issue I've just fixed in v1.3.1. I would be glad if you could confirm the fix works for you.

**Comment by semmycom** [comment]
Great thanks for the quick response. It works now. Great. As I would not have liked to switch to another icon thing. What is your main website by the way, would like to learn what you are doing and able to program. Thanks. Have a good day!

**Comment by semmycom** [comment]
ah I see your site now, but its all in french, I forgot all my french (only had a few years in school). anyway if you have some information in english feel free to send me something via semmy.com I close the issue here now as solved :-)

**Comment by phbernard** [comment]
Great! What a relief! Thank VERY MUCH for your quick reaction. Such bad update is really a nightmare for plugin developers :(

What am I doing? My personal site is clearly outdated. My up-to-date resource is my LinkedIn profile: https://fr.linkedin.com/pub/philippe-bernard/1/47/828 . Let's connect!

**Comment by semmycom** [comment]
Thanks I do not have a professional linked in accountyou can add me finding me at
https://es.linkedin.com/in/semmycom

Semmy Stumpp
Your Internet Success In Your Hands
www.semmy.com

---- On Wed, 24 Jun 2015 11:20:22 +0100 Philippe Bernard&lt;notifications@github.com&gt; wrote ---- 

Great! What a relief! Thank VERY MUCH for your quick reaction. Such bad update is really a nightmare for plugin developers :(
 What am I doing? My personal site is clearly outdated. My up-to-date resource is my LinkedIn profile: https://fr.linkedin.com/pub/philippe-bernard/1/47/828 . Let's connect!

**Comment by phbernard** [comment]
Invitation sent!
