### ISSUE TITLE
Many errors, can't tell what I'm missing

### ISSUE THREAD

**Issue by rosedraws** [RealFaviconGenerator/realfavicongenerator#177]
I'm getting a lot of errors, but I can't see any solutions about how to fix them.

http://beechleafdesign.com/lafferty/

**Comment by jklegseth** [comment]
You have mapped all of your favicons to an invalid absolute path. For example:

```
<link rel="apple-touch-icon" sizes="57x57" href="/favicons/apple-touch-icon-57x57.png">
```

...resolves to:

```
http://beechleafdesign.com/favicons/apple-touch-icon-57x57.png
```

There's no such directory. Your website is under the `/lafferty` directory. So either use a relative path or change the absolute path to include that directory:

```
<link rel="apple-touch-icon" sizes="57x57" href="/lafferty/favicons/apple-touch-icon-57x57.png">
```

**Comment by phbernard** [comment]
Thank you @jklegseth for your support. I couldn't have been more accurate! :)

@rosedraws, I notice the issue is still present. Do you plan to fix it?

**Comment by phbernard** [comment]
The issue is quite old. I close it, but don't hesitate to post again if there is anything new.
