### ISSUE TITLE
App name should always be specified

### ISSUE THREAD

**Issue by daniel** [RealFaviconGenerator/realfavicongenerator#181]
It seems that "browser offers the page title by default" doesn't work on Android, because I get "My app" as suggested title when adding to home screen.
So maybe you should require the app name to be specified before generating favicons.

I'm using the latest Chrome browser (on a Google Nexus 5, Android 5.1.1)

**Comment by phbernard** [comment]
That's right. The field is not pre-filled anymore, so you have to provide a value.
