### ISSUE TITLE
remove Favicon

### ISSUE THREAD

**Issue by fcassad** [RealFaviconGenerator/realfavicongenerator#182]
I put in a new Favicon wanting to remove my old Favicon,however,the old is still there,I can't get the new one on.

**Comment by phbernard** [comment]
Sounds like a classic caching issue. Your browsers keeps displaying the old favicon, ignoring the new one.

If your site is new (nobody visited it, only you as a developer), there is nothing to do. Simply access your site with another browser to make sure the favicon update worked.

If your site is already in production, you should generated your favicon again. This time, take advantage of the "Version/Refresh" tab in the favicon options to make sure your returning visitors will get the new favicon.

Does this help?

**Comment by phbernard** [comment]
The topic is more than a month old so I close it. Don't hesitate to post again if there is anything new.
