### ISSUE TITLE
new icon for Safari pinned tabs

### ISSUE THREAD

**Issue by yomed** [RealFaviconGenerator/realfavicongenerator#186]
In Safari 9.0 there is a new type of icon for pinned tabs. Wasn't sure if you were interested in supporting it here. It might be more difficult since it requires an svg.

https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW20

**Comment by phbernard** [comment]
I am! This is issue #169. I will surely support this one.

**Comment by tigt** [comment]
Getting an SVG out of an uploaded bitmap would be tricky, but if you already have the silhouette for Windows 8, you could totally do something like [this pixel-art to SVG tool](http://www.drububu.com/tutorial/bitmaptovector.html).

**Comment by phbernard** [comment]
Thanks! I tried the tool and it works great! I looked for a Linux command line tool and apparently potrace is the most popular answer. #169 is on its way!

**Comment by tigt** [comment]
Potrace is pretty alright, just make sure you're using it [on a big version of the favicon](http://research.microsoft.com/en-us/um/people/kopf/pixelart/supplementary/comparison_potrace.html).

**Comment by phbernard** [comment]
And... it's done!

![image](https://cloud.githubusercontent.com/assets/423852/10490053/6224f878-729f-11e5-85fd-e899fd04e999.png)

Yep, potrace was definitely a winner. I didn't put a string requirement on the input picture size, but the editor let you see what the actual potrace job will be.
