### ISSUE TITLE
android bg is not transparent + favicon is distorting

### ISSUE THREAD

**Issue by propertunist** [RealFaviconGenerator/realfavicongenerator#187]
thanks for this great tool!
when i viewed the preview favicons prior to integrating them into my site, they looked fine. the android icon was shown with a transparent background and all was well.
after integrating the files and codes into my site, the outcome is that the android icon has a black background (my favicon file has transparent areas and was a large file - 512px).
also, the main favicon is being rendered in firefox in a distorted way. 
the favicon distortion in firefox was present even before using your tool here - despite it having been rendered just fine for years! (the problem must have appeared relatively recently).

if anyone can explain this and offer tips, i'd appreciate the assistance. the site url is www.ureka.org

**Comment by phbernard** [comment]
Thank you for your feedback!

I couldn't reproduce the issue. On my Galaxy S5 running Android 5 and Firefox 41.0, the result is similar with Firefox (left) and Chrome (right).

![image](https://cloud.githubusercontent.com/assets/423852/10275019/4099f99a-6b44-11e5-8334-6ccc605aa7c0.png)

Yet, I'm not especially surprised: FF is know for adding unwanted padding around icons when adding to homescreen. Apparently FF 41.0 fixes this, at least on my phone.

**Comment by propertunist** [comment]
ok thanks for letting me know.
after investigating this further, it appears that the distorted favicon is only appearing in my fedora 22 version of firefox, whereas in win 7 firefox it's ok.
the issue with the background in android was that it appeared black when i ran the tester that is part of the realfavicongenerator and i haven't tested it on real world devices, since i don't have any here.
if you are seeing it appear transparently, then that is good enough for me for now as i have more pressing issues to resolve!

**Comment by phbernard** [comment]
Great!
