### ISSUE TITLE
Favicon is not shown on Ipad Air Chrome

### ISSUE THREAD

**Issue by drieselliott** [RealFaviconGenerator/realfavicongenerator#190]
When opening a page in Chrome (version 45) on an Ipad Air the Favicon does not show in the tab bar. I added the icons to my root directory, added the generated HTML to my page.

I don't know if this impacts favicons, but I'm serving the site from a sub-domain.

**Comment by phbernard** [comment]
What do you observe when you visit http://test01-v0-11-attempt-1.test.realfavicongenerator.net/ ? (this page, too, is on a sub-domain)

**Comment by drieselliott** [comment]
When I open that page on an Ipad it does display the favicon.

**Comment by drieselliott** [comment]
Ok, because the test page does work, while it doesn't seemed to work for the site I set up, I started testing some more. 

I navigated to favicon.ico and apple-touch-icon-57x57 just to make sure the files were available. That seemed to be the case.

I then navigated back to the site itself and there it was. Looks like there was some kind of caching going on. I'll verify on another Ipad just to make sure.

**Comment by phbernard** [comment]
Browser laziness at its finest! This is a know problem with all browsers: once they figure out what the favicon is, they tend to ignore further declarations. I had the issue recently with Safari on Mac OS while testing pinned tabs.

Let me know if you have the same issue with another device.

**Comment by drieselliott** [comment]
I was able to reproduce this behavior on the second Ipad.

Navigate to the site - No favicon
Navigate to favicon.ico
Navigate to the site again - No favicon (so opening the favicon changes nothing)
Navigate to apple-touch-icon-57x57.png
Navigate to site again - Favicon shows up in tab bar correctly

**Comment by phbernard** [comment]
Weird. Do you have a URL so I can test this with my iPad Mini ?

**Comment by drieselliott** [comment]
I've sent you an email containing all the details. Maybe something related to the Basic Authentication I've set up for the site?

**Comment by phbernard** [comment]
I reproduce what you observe on my iPad Mini.

I never observed this before, and basic authentication is a likely suspect. Let's keep this issue open and repeat the process once the site is public.

**Comment by drieselliott** [comment]
Basic authentication was definitely the culprit. Thanks for helping out with this.

**Comment by amankm** [comment]
In my case also, it wasn't working due to network policies
