### ISSUE TITLE
Support for Android Chrome 47 splashscreen

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#194]
See http://blog.chromium.org/2015/10/chrome-47-beta-idle-time-work-splash.html and https://developers.google.com/web/updates/2015/10/splashscreen

**Comment by rugk** [comment]
Any news about this issue?

**Comment by phbernard** [comment]
Oh, but this one has been implemented! Thank you @rugk for cleaning this place :)
