### ISSUE TITLE
Unused apple-touch-icon size

### ISSUE THREAD

**Issue by joppuyo** [RealFaviconGenerator/realfavicongenerator#199]
RealFaviconGenerator generates whole lot of Apple touch icons but there is one that puzzles me:
- apple-touch-icon-60x60.png

This seems to be half if the iOS 7 retina 120x120px icon. The last iPhone without the retina display was iPhone 3gs, released in 2009 and it never got the iOS 7 update. Is this icon actually used anywhere?

**Comment by kevinvanrijn** [comment]
It's listed in the [FAQ](http://realfavicongenerator.net/faq#why_so_many_files) as:

apple-touch-icon-60x60.png

> Same as apple-touch-icon-57x57.png, for non-retina iPhone with iOS7.

Same as apple-touch-icon-57x57.png refers to:

> iPhone and iPad users can turn web pages into icons on their home screen. Such link appears as a regular iOS native application. When this happens, the device looks for a specific picture. The 57x57 resolution is convenient for non-retina iPhone with iOS6 or prior. Learn more in [Apple docs](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html).

I have no way of confirming if it's possible or not to have non-retina iOS7 but if it it's not possible you're correct that the image would never be used.

http://bendodson.com/weblog/2013/10/16/dropping-non-retina-support-in-ios7/ says that iOS7 just uses the retina versions of apps on non-retina iPads. It lists the iPad 2 and iPad Mini as examples. Perhaps they would use the favicon? Those are iPads though, not iPhones like the FAQ lists for 60x60. 57x57 it refers to does name iPads though. It's also just a difference in apps. I have no idea how or if it affects websites.

This issue needs some testing.

**Comment by phbernard** [comment]
Thank you for reporting. I never realized the 60x60 icon might be for ghost devices only!

I was never reported the usage of the 60x60 icon through the [compatibility test](https://realfavicongenerator.net/favicon_compatibility_test). But old iPhones must not be that common nowadays, especially among geeks.

Wikipedia says the first iPhone to have a Retina display is the iPhone 4 (https://en.wikipedia.org/wiki/Retina_Display). And apparently the iPhone 4 can be updated up to iOS 7 (http://www.everyi.com/by-capability/maximum-supported-ios-version-for-ipod-iphone-ipad.html). So theoretically, an up-to-date iPhone 4 would pick the 60x60 icons.

**Comment by kevinvanrijn** [comment]
What would an iPhone 4 pick if the 60x60 icon isn't available? I'm guessing there are pretty close to zero users going to land with it on any given site, so if it's able to pick an image close to what it's supposed to be and it doesn't look horrible in the UI there's no point in supporting such an old device imo. It could add some space for another icon. #200 for example.

Also, this is unrelated to this issue, but in the case this icon is getting removed, would it be feasible to put it under some kind of deprecated icons menu instead of completely removing it?

**Comment by joppuyo** [comment]
> Wikipedia says the first iPhone to have a Retina display is the iPhone 4. And apparently the iPhone 4 can be updated up to iOS 7. So theoretically, an up-to-date iPhone 4 would pick the 60x60 icons.

Iphone 4 is retina. That means it would pick a 120x120px icon.

I opened this issue because of the non-retina iOS 7 60x60 icon. There are no non-retina iOS 7 devices  (iPhone 3gs and older, except iPads, but those have their own icons.) because iPhone 3gs was never updated to iOS 7. That's why I'm guessing no device actually uses the 60x60 icon.

I hope this clears this up :smiley: 

> It could add some space for another icon. #200 for example.

I'm pretty sure the 44x44 icon is for toolbar icons [Like this](http://i.imgur.com/zUpHODF.jpg) and not application icons.

**Comment by kevinvanrijn** [comment]
Fair point on #200. I originally though that the number of icons was the problem, I must have skipped over the 'touch' part.

Removing this icon could still clear up space for it though, since it removes some stress from the generator and adds some space (in terms of file size) for a new icon. The file sizes aren't an issue yet though.

**Comment by phbernard** [comment]
And here's some stuff in favor of the 60x60 icon: it's explicitly mentioned in [Apple specs](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html). This doc is actually outdated and I don't trust it entirely. It's completely possible that the 60x60 resolution should be ignored.

I've just reviewed the logs of two of my web sites. The 60x60 icon has been requested by... IE 11 and Windows Chrome. This Touch icon thing is really a joke :)

**Comment by phbernard** [comment]
I've just created #211 to address the root issue: there are a lot of icons.

**Comment by phbernard** [comment]
With #211 closed, I think we can close this one too. Please let me know if you think there is something else to discuss.
