### ISSUE TITLE
JS error: Cannot get property 'threshold' of undefined

### ISSUE THREAD

**Issue by carolinecblaker** [RealFaviconGenerator/realfavicongenerator#201]
When the button to generate is clicked, and there are no errors, nothing happens and this error logs in the console.

**Comment by phbernard** [comment]
This issue was fixed a few days ago. As far as I know, it can't happen anymore.

Could you confirm?

**Comment by phbernard** [comment]
No news is good news :)

But please open the issue again if ever you encounter the bug one more time.
