### ISSUE TITLE
All mstile icons reported missing (even when they're not)

### ISSUE THREAD

**Issue by ghost** [RealFaviconGenerator/realfavicongenerator#202]
http://realfavicongenerator.net/favicon_checker?site=https%3A%2F%2Fwww.makoto.io#.VlBhZJgzZFQ

This is what is reported to me,
Some recommended pictures for Windows 8 / IE 11 are missing:
- 70x70 picture
- 150x150 picture
- 310x310 picture
- 310x150 picture

However, all of these are defined in the HTML document and are properly routed to the correct file when requested at the root level (just as other favicons are),
- https://www.makoto.io/mstile-70x70.png
- https://www.makoto.io/mstile-150x150.png
- https://www.makoto.io/mstile-310x310.png
- https://www.makoto.io/mstile-310x150.png

Any idea what's wrong here? It shouldn't be an issue with the favicons utilizing permanent redirects, right? Since that causes no problems with any of the other favicon sets.

**Comment by phbernard** [comment]
There is a problem with your `browserconfig.xml` file. For some reasons, all the content is embedded in a `xml` element: 

```
<?xml version="1.0"?>
<xml>
  <browserconfig>
    <msapplication>
    ...
```

The top-level `<xml>` is the culprit.

**Comment by ghost** [comment]
Thanks @phbernard !

I fixed the issue with the XML generator and now everything is returning successful.
