### ISSUE TITLE
Usage rights

### ISSUE THREAD

**Issue by sedrubal** [RealFaviconGenerator/realfavicongenerator#204]
Hi,

can you somehow specify the rights on the generated images, etc or give a statement for what I am allowed to use the favicons etc...

**Comment by phbernard** [comment]
That's right, terms don't say anything about this. I've just updated them: would you do a quick review?

**Comment by sedrubal** [comment]
I'm no jurist but that looks very good to me. Especially the examples are very useful. Thank you :+1:

**Comment by phbernard** [comment]
Great! Thanks for the feedback.
