### ISSUE TITLE
Add Twitter Card support

### ISSUE THREAD

**Issue by haydenbleasel** [RealFaviconGenerator/realfavicongenerator#206]
To keep track of things :)
- [ ] Add `<meta property='twitter:image' content='twitter.png'>`
- [ ] Create `twitter.png` (1400w x 750h)
- [ ] Remove `"meta[property='twitter:image']"`

**Comment by jacksonj04** [comment]
I personally feel this is well out of scope of the favicon generator, as a lot of sites vary Twitter Card and OpenGraph content page by page.

At the very least, this should be disabled by default.

**Comment by phbernard** [comment]
That's perfectly right: FB/OpenGraph and Twitter cards have nothing to do with favicons. And as you mention, many sites have a per-page OG/TC image policy.

But the feature make sense for sites with no plan for OG/TC (eg. ... RealFaviconGenerator itself). And the process of creating them is very similar to the favicon's: submit a picture, craft a bit, and get pictures and a few lines of HTML code. So integration in RFG should look good and consistent.

And now, my trump card: [people asked for it](https://realfavicongenerator.net/blog/rfg-needs-your-feedback-22/) :) OG and TC were more requested than the more legit pics for Yandex browser and Coast.

Sure, these pictures will be optional and disabled by default. Else, that will be painful for sites with per-page images.

**Comment by joppuyo** [comment]
Not sure how good idea it is to encourage people to use one Open Graph/Twitter Card image across all pages. This is what Facebook [documentation](https://developers.facebook.com/docs/sharing/best-practices) has to say about it

> **Bad Examples**
> _Generic Image_
> This is a generic image that will look the same for all stories. It is only 100px by 100px, which will not be usable on higher resolution displays.

And here's Twitter [documentation](https://dev.twitter.com/cards/types/summary)

> **twitter:image**
> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages.

Facebook and Twitter would rather like you to have per page/article images but of course this is not always possible due to lack of resources or not having a system like a CMS in place. So I think it's good to have a fallback logo rather than nothing. Maybe add some sort of help text about this?

**Comment by phbernard** [comment]
Absolutely, images should change from a page to another, and CMS make this a bliss. However, when you have no particular image to propose, I think it's great to have a default picture, probably built after the sites's logo.

RFG itself is a good example of this, and apparently I'm not the only one: https://dev.twitter.com/solutions/customer-service and https://dev.twitter.com/solutions/tell-great-stories share the same image (https://pbs.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3.png).

**Comment by ghost** [comment]
I personally am using the plugin [gulp-fancy-meta](https://github.com/luiguild/gulp-fancy-meta) to inject Twitter cards, Pinterest rich pins, Google's structured data and Facebook's Open Graph and other markups (into a one-page application website) while resorting to RealFaviconGenerator's gulp plugin to generate favicons, apple touch icons, ms tiles, etc. I am happy using different plugins for these two different tasks and I am not sure if it makes a lot of sense to bring them together (as gulp-fancy-meta does), but I can see the appeal of having all in one tool.

**Comment by phbernard** [comment]
Wait, there will be a Twitter Card support in the [social editor](https://realfavicongenerator.net/social) someday! :)
