### ISSUE TITLE
Wrong apple-touch-icon-precomposed transparency mask

### ISSUE THREAD

**Issue by CoobieXD** [RealFaviconGenerator/realfavicongenerator#212]
![report](https://cloud.githubusercontent.com/assets/10087968/12177926/73d8ee4c-b577-11e5-8a4d-a207568efab9.png)
All can be seen from the screenshot, see that blue lines on the left and right rounded corners.
I think you use a mask size of 182x182 px to picture size 180x180 px.

P.S. My English so bad, I know, and I apologize in advance for that с:

**Comment by kevinvanrijn** [comment]
The lines show that the edges of the image aren't being rounded at the same height.

Could this be caused by an image with an odd number as it's width? Or is something else going on?

@c00613 What is the original image you uploaded to RealFaviconGenerator?

**Comment by CoobieXD** [comment]
![favicon-192x192](https://cloud.githubusercontent.com/assets/10087968/12182382/99237bc2-b590-11e5-9b2f-8ac8f0b518d5.png)

Initially I uploaded an image without rounded edges.

This is exactly the bug of RFG.

**Comment by phbernard** [comment]
Thank you for spotting this one!

This is exactly what you suggested. The mask was created dynamically with a command such as

```
convert -size 192x192 xc:none -draw 'roundrectangle 0,0,192,192,24,24' some_mask.png
```

But what is the corner of a 192x192 image? (191;191), not (192;192). I should learn computer science.

The fix was deployed a minute ago.
