### ISSUE TITLE
Donation modal off edge of page

### ISSUE THREAD

**Issue by city41** [RealFaviconGenerator/realfavicongenerator#216]
In Chrome 47.0.2526.106, OSX, the donation modal is off the left edge

<img width="729" alt="screen shot 2016-01-17 at 7 44 28 pm" src="https://cloud.githubusercontent.com/assets/141159/12382802/efbfdefc-bd52-11e5-8ad1-32d6d3511646.png">

**Comment by phbernard** [comment]
I never saw that before. Then I got my new laptop two days ago and noticed the exact same thing. Damn!

I've just removed the popup. Thank you for reporting this!
