### ISSUE TITLE
HTML validation fails

### ISSUE THREAD

**Issue by terryally** [RealFaviconGenerator/realfavicongenerator#218]
The following link in your generated code is using a 'color' attribute in a link tag which is failing validation. If I remove this attribute, how does it affect the favicon display?

`<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">`

Thanks
Terry

**Comment by phbernard** [comment]
Unfortunately, Apple recently introduced this proprietary attribute.

Yes, you can remove this attribute (along with the `safari-pinned-tab.svg` file itself). By doing so, you won't have a dedicated icon for Safari pinned tabs, which is not critical (but so damn cool :) )

**Comment by tigt** [comment]
This [should be valid soon](https://github.com/validator/validator/issues/174).

**Comment by sideshowbarker** [comment]
https://checker.html5.org/ and https://validator.w3.org/nu/ now allow this
