### ISSUE TITLE
Additional/new icon size in Android Manifest

### ISSUE THREAD

**Issue by theperrygroup** [RealFaviconGenerator/realfavicongenerator#219]
[Google says to use](https://developers.google.com/web/updates/2015/10/splashscreen?hl=en):
- 192x192
- 256x256
- 384x384
- 512x512

192 is the smallest that it recommends. 

What they specifically say:

> High quality icons that will displayed in the center of the splash screen - ensure your icon is at least 192px

**Comment by phbernard** [comment]
Thank you for reporting! That's #194
