### ISSUE TITLE
SVG: Nicely asked to extend margins for non-squared, but error on adding IOS variant

### ISSUE THREAD

**Issue by michalfita** [RealFaviconGenerator/realfavicongenerator#223]
I generated my favicon set from and SVG file, which is dark. It looked bad on black IOS background, so I selected option to set another file as I have inverted variant of my SVG logo file (white). But then error about non-square picture has been reported and I'm not let to add this same nice way as the main graphics file.

**Comment by phbernard** [comment]
Could you attach your SVG image to this issue for review?

**Comment by phbernard** [comment]
Apparently, this issue is similar to #224, which was fixed. I'm so sure of this that I close the issue :) But please re-open it if I'm wrong.

**Comment by michalfita** [comment]
On GitHub I can't reopen the closed issue unless I'm a member of the project. Sorry for being late with that, but I just forgot about attaching the picture. The kind thing from the GitHub designers is that they don't allow me to attach SVG files as it would look like an atomic bomb that goes to blow up some servers... so, I attached a ZIP with them.
[najemcokulator.zip](https://github.com/RealFaviconGenerator/realfavicongenerator/files/226893/najemcokulator.zip)

**Comment by phbernard** [comment]
This vector technology can be so frightening. :)

So yep, #224 must have been the same issue because it looks good now:

![image](https://cloud.githubusercontent.com/assets/423852/14666174/51b32c6c-06d8-11e6-8aad-0e3db0c91f40.png)

Do you confirm?
