### ISSUE TITLE
Non-square SVG gets incorrect padding

### ISSUE THREAD

**Issue by oBusk** [RealFaviconGenerator/realfavicongenerator#224]
When giving http://realfavicongenerator.net/ a svg that is not square it seems like it get's too much padding. 

I have uploaded an example svg to show what i mean.
![](https://i.gyazo.com/096ab6787174196e943c2fb31dab3a11.png)
As you can see it is not completely square and realfavicon offers to add transparent margins. The preview looks fine (only adding margins to the right and left).

But the icons that this process generates are very weirdly marginalized, and as a result they end up way too small.

![](https://gyazo.com/fc7350d53a3329bac7e68a11e3913004.png)
![](https://gyazo.com/aa76fd30b18a73cb7a9a3b1a61d77755.png)

I can get around this by converting the svg to a proper sized png and then upload that. Also fiddling with the viewbox so that the svg becomes square outputs proper sized icons, so it seems to me that the problem is within the padding of non-square svgs.

**Comment by phbernard** [comment]
Could you send me your original SVG image for review?

**Comment by oBusk** [comment]
This is a file which causes the exact same problem as in my original description.

``` html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 210 242">
    <rect fill="hotpink" width="210" height="242"/>
</svg>
```

[Dropbox Link](https://www.dropbox.com/s/f4ldre4fqca95lb/favicon-cropping-example.svg)

**Comment by phbernard** [comment]
Thanks!

I think we have a fix! Could you retry to confirm the site now works for you too?

**Comment by oBusk** [comment]
![](https://i.gyazo.com/a702c71aa35f79d9d448a05e546e7d9c.png)

Looks good! Good job! :+1: Love the service, keep it up!

**Comment by phbernard** [comment]
Great! Thank you for the feedback!
