### ISSUE TITLE
Density descriptors in manifest.json should not be included

### ISSUE THREAD

**Issue by marcoscaceres** [RealFaviconGenerator/realfavicongenerator#228]
Hi, I edit the W3C Manifest specification and work on Firefox's implementation of W3C manifest. Firstly, thanks for adding W3C manifest support via this plugin! :heart: We see from our stats that many sites are including the manifest. 

I would like to point out a small, but significant, issue that's currently affecting users. The usage of the "density" member in your generated manifest is currently being used incorrectly and should be removed. 

The purpose of "density" is to say: "only ever use this icon when the density of the screen is at least X" (see [spec](https://w3c.github.io/manifest/#density-member)). Right now, almost none of the icons will match, because there are no screen that, for instance, have a density "4.0" and very few that have "3.0". 

I would kindly ask that you please remove the density member from the generated manifest.

Please let me know if you have any questions and if I can help fix this! I tried to track down the generator for this, but I had trouble finding it.

**Comment by marcoscaceres** [comment]
Oh, forgot to point out that "density": "1.0" is also implied - so you get that for free.

**Comment by kenchris** [comment]
Actually on phones densities like 3.0 and 4.0 are kind of standard today. My second gen Moto X has a density of 3.0, but newer ones like the Galaxy S6/S7 are 4.0:

http://www.canbike.org/CSSpixels/

**Comment by marcoscaceres** [comment]
Ok, but that's not the point: a 192x192px icon is fine to use at 1x (even if designed for 4x). You don't want to discriminate on density unless you absolutely need to. It might make more sense for us to drop density from the spec and implementations if people using it incorrectly. Discriminating on density is a bit of a corner case, specifically nowadays where 2x is the norm and 3x is also becoming normal.

**Comment by paulirish** [comment]
Agree. I was surprised to see these in the output.

**Comment by phbernard** [comment]
Thank you @marcoscaceres for your feedback. I'm glad the manifest is spreading and I hope RFG is a significant contributor :)

Okay, I understand. I'm going to remove the `density` member. This change will be part of the next release, which should happen in a couple of weeks. Before, I need to update the RFG's compatibility test to make sure the package still works everywhere (although this density thing doesn't sound disruptive; but there are other changes to test, too).

FYI, I generated the manifest as described in the [Android Chrome official doc](https://developer.chrome.com/multidevice/android/installtohomescreen#manifestmetadata). @paulirish I have no idea if that's up to you, but maybe you could give it a look?

**Comment by kenchris** [comment]
@PaulKinlan should be able to fix the docs, or know who can

**Comment by phbernard** [comment]
Implemented in branch `package_0_13`

**Comment by phbernard** [comment]
Deployed yesterday
