### ISSUE TITLE
Don't generate the 96x96 PNG icon for Google TV anymore

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#230]
Definitely not sure the 96x96 PNG icon is important. It's only for [Google TV](https://en.wikipedia.org/wiki/Google_TV), which was replaced by Android TV with no evidence that the 96x96 PNG icon is still useful.

Plus this icon is [wrongly loaded by Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=751712).

Supporting a confidential platform at the cost of hampering a mainstream one doesn't worth it. Better not support it at all.

**Comment by phbernard** [comment]
Implemented in branch `package_0_13`

**Comment by phbernard** [comment]
Deployed yesterday

**Comment by bartvanandel** [comment]
Is it correct behavior that #143 introduced using 'android-chrome-192x192.png' for the 192x192 _favicon_ and removes the 230x230 resolution? Judging by the filename this seems inappropriate or at least counterintuitive. I did not test this, but I guess this file is only generated when the right options are set, so this will cause invalid results when using `{android: false, favicons: true}`.

With the current version, the 230x230 file is no longer referenced anywhere in html or manifest files, but it's still being generated. If the file is not needed, it should probably not be generated.

**Comment by phbernard** [comment]
The sample configuration you give is for https://github.com/haydenbleasel/favicons , is that right? Is it really related to this issue?
