### ISSUE TITLE
Make the msapplication-TileImage tile icon for Windows 8.0 / IE 10 optional

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#231]
Windows 8.1 / IE 11 and Windows 10 / (IE 11 / Edge) rely on the `browserconfig.xml` file and a set of icons. But Windows 8.0 / IE 10 doesn't support it and expects the meta `msapplication-TileImage`, which should be a 144x144 image. Is it really useful now that [Windows 8.0 accounts for a little less than 2.5% market share](https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0)? (versus 24% for Win 8.1 & 10 combined)

The idea here is to make this icon optional. In other words, disabled by default, with an option to generate it again.

Of course, if we decide to go this route, we will first perform compatibility tests to check the outcome.

Note: last time I checked, Coast by Opera was using this icon when it couldn't find a dedicated PNG image.

**Comment by phbernard** [comment]
Why doing this?
- To save two markups. Not a big deal, but not a huge market share either. This is in line with the upcoming update, in particular #211.
- For clarity. Currently the `msapplication-TileImage` looks like it conflicts with `browserconfig.xml` (although that's not the case).

**Comment by ghost** [comment]
Hi,
I just created my favicons, I paste the code given by the site, just, I'd rather put a folder of favicon, so I modify each line, then I do the test and I have this error message, why
Some Windows 8 / IE11 tile(s) could not be found or are corrupted.
thank you

**Comment by phbernard** [comment]
Is you site live? Could you give me its URL?

**Comment by phbernard** [comment]
Implemented in branch `package_0_13`

**Comment by ghost** [comment]
Hi,
http://irondove.fr
my site
thank you

**Comment by phbernard** [comment]
When you created your icon with RealFaviconGenerator, you probably indicated you would place your icons in the root directory of your web site. Then, you changed your mind and edited the HTML code to indicate `/favicons` as a sub directory. Am I right?

The problem with this is that `browserconfig.xml` doesn't have to be declared... when it is in the root directory. But it needs to in the other cases.

My advice is to create your favicon again, and this time indicate the definitive location of your files. This is way safer than editing the generated code and files manually.

**Comment by phbernard** [comment]
Deployed yesterday
