### ISSUE TITLE
Progressive Web App Splash Screen requires higher res images (256px+)

### ISSUE THREAD

**Issue by paulirish** [RealFaviconGenerator/realfavicongenerator#234]
The [splash screen functionality described here](https://developers.google.com/web/updates/2015/10/splashscreen?hl=en) uses a pretty high res image. In order to use the native image without scaling it must be 128dp, which converts into some pretty hi-res images.

They start at 192px for older phones and go up to 512px. 

In all, these sizes should be generated with manifest icon entries created: `192, 256, 384, 512`

More details here: https://github.com/GoogleChrome/lighthouse/issues/291

**Comment by phbernard** [comment]
Implemented in branch `package_0_13`

**Comment by addyosmani** [comment]
Came here to file just this. Discovered @paulirish has already done so and it's been implemented. Wooo! 🎉

**Comment by paulirish** [comment]
Thanks phillipe!

**Comment by phbernard** [comment]
Soon!

![image](https://cloud.githubusercontent.com/assets/423852/15621146/259734ee-245f-11e6-8076-e2056285be65.png)

To be released next week. Well, I already said that a week ago, but this time this is true :)

**Comment by Tathanen** [comment]
Ooh can't wait.

**Comment by phbernard** [comment]
Deployed yesterday.
