### ISSUE TITLE
Option to make the color attribute optional in Safari's mask icon

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#239]
Apple introduced the mask icon and the new `color` attribute. However, this is non standard. Therefore, the users who run the W3C validator are reported an error and wonder how to get rid of it.

An option to omit the `color` attribute would be useful.

**Comment by andwhyisit** [comment]
Does anyone know how what happens when the color attribute is omitted?

**Comment by phbernard** [comment]
I was 99% sure Safari would use the icon and a default color. So I made some tests and... apparently, the `color` attribute is mandatory. When it's omitted, Safari behaves as if there was no mask icon at all and takes the first character of the domain name as the icon.

Conclusion: **as of today, this feature doesn't make any sense**. Removing the color alone is like removing the whole markup and icon.

As an aside, Safari and the mask icon suffer from the same universal caching issue that always comes with favicon: once Safari knows your icon, it's hard to make it reload it (eg. when you add the `color` attribute again to make sure the markup is back to normal).

**Comment by phbernard** [comment]
This issue won't be fixed in the end.

As a workaround, the UI allows the user to not generate the icon at all. In the next release, the message is: "No icon. Safari uses the first letter of your domain name to create a default icon. You should use this option if your site absolutely needs to be W3C compliant."
