### ISSUE TITLE
Doesn't render SVG correctly

### ISSUE THREAD

**Issue by matthewoates** [RealFaviconGenerator/realfavicongenerator#240]
Given:

<img width="540" alt="screen shot 2016-05-27 at 3 16 23 pm" src="https://cloud.githubusercontent.com/assets/3092315/15622489/fe9d5238-241d-11e6-995f-3c548edf588e.png">

This is rendered as:
<img width="489" alt="screen shot 2016-05-27 at 3 20 32 pm" src="https://cloud.githubusercontent.com/assets/3092315/15622550/a0458e34-241e-11e6-9d89-2c1399ee6ef2.png">

The border fails to render.

SVG file contents:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="152px" height="152px" viewBox="0 0 152 152" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 3.8.1 (29687) - http://www.bohemiancoding.com/sketch -->
    <title>Logo</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <rect id="path-1" x="0" y="0" width="152" height="152" rx="16"></rect>
        <mask id="mask-2" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="152" height="152" fill="white">
            <use xlink:href="#path-1"></use>
        </mask>
    </defs>
    <g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Logo">
            <rect id="Rectangle-6" fill="#3F51B5" x="0" y="0" width="152" height="152" rx="20"></rect>
            <path d="M113.932009,103.391933 C114.319174,108.266173 115.515859,119.141638 118.629961,122.144313 C122.682098,126.051458 125.4601,123.712252 128.090746,125.623832 C130.721392,127.535411 128.090746,132.231579 128.090746,132.231579 L110.629961,132.231579 L93.1691762,132.231579 C93.1691762,132.231579 90.5385298,127.535411 93.1691762,125.623832 C95.7998225,123.712252 98.5778245,126.051458 102.629961,122.144313 C105.746255,119.139525 106.942432,108.250858 107.32873,103.381649 C104.483322,102.128786 102.5,99.3118027 102.5,96.0375387 C102.5,91.5985286 106.145341,88 110.642098,88 C115.138854,88 118.784196,91.5985286 118.784196,96.0375387 C118.784196,99.3207927 116.789967,102.144251 113.932009,103.391933 Z M76,76 L145,76 L145,145 L76,145 L76,76 Z" id="Combined-Shape" fill="#A7AFDD"></path>
            <path d="M7,7 L76,7 L76,76 L7,76 L7,7 Z M41.3088235,62.6176471 C53.0773618,62.6176471 62.6176471,53.0773618 62.6176471,41.3088235 C62.6176471,29.5402853 53.0773618,20 41.3088235,20 C29.5402853,20 20,29.5402853 20,41.3088235 C20,53.0773618 29.5402853,62.6176471 41.3088235,62.6176471 Z" id="Combined-Shape" fill="#A7AFDD"></path>
            <use id="Combined-Shape" stroke="#A7AFDD" mask="url(#mask-2)" stroke-width="16" xlink:href="#path-1"></use>
        </g>
    </g>
</svg>
```

Of course, rendering to `png` fixes this. Great service!

**Comment by phbernard** [comment]
I have opened you SVG pic with Inkscape and I get this:

![image](https://cloud.githubusercontent.com/assets/423852/15772375/1277e310-2971-11e6-942c-a023d98917e8.png)

... which is not similar to your original picture.

I have not idea why we get something different but at least I can explain why RFG behaves as it does: it relies on Inkscape to process SVG pics.

**Comment by matthewoates** [comment]
If you open it with sketch you'll see it rendered in the same way as my screenshot. Also, if you open the file with every other major browser it will render as it does in my original post. I suspect Inkscape's SVG engine is nonconformant.

**Comment by phbernard** [comment]
You're right, Chrome and Firefox show "your" version.

I submitted https://bugs.launchpad.net/inkscape/+bug/1588996

**Comment by phbernard** [comment]
The issue was validated on Inkscape side.

This is the first time I'm reported an issue like this, so I'm rather going to wait for Inkscape's fix (instead of switching to another tool).

**Comment by matthewoates** [comment]
Yeah. This doesn't seem critical, since I was able to render to PNG just fine with the desired results.

**Comment by rugk** [comment]
So as this issue is not on the RFG side, I suspect this issue can be closed, can't it?

**Comment by phbernard** [comment]
Yup! Totally blame Inkscape here ;-p
