### ISSUE TITLE
responsive_favicons drupal module

### ISSUE THREAD

**Issue by graemearthur** [RealFaviconGenerator/realfavicongenerator#241]
Hey,
URL: http://elim-church.org.uk

Errors I get when checking the site after using the generator and uploading via the drupal module.

favicon.ico seems corrupted or not in ICO format.

Some picture(s) are missing in favicon.ico:

16x16 picture
32x32 picture
48x48 picture

**Comment by phbernard** [comment]
The Drupal module was not written here, sorry :) I really can't help, you should ask his author.
