### ISSUE TITLE
Safari mask icon resolution / viewBox

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#242]
Currently, the Safari mask icons created by RFG have a viewBox of 700x700:

```
<svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="700.000000pt" height="700.000000pt" viewBox="0 0 700.000000 700.000000" preserveAspectRatio="xMidYMid meet">
```

However, [it should be 16x16](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html).

Although RFG icons do work, it would be better to strictly follow Apple's recommendations.

**Comment by ghost** [comment]
Same here. SVG icon does not display well.

**Comment by phbernard** [comment]
Really? Although the viewBox is not correct, all my experiments were successful and the icon is always displayed correctly by Safari. 

Are you sure the mask icon is properly declared in your site? (you can run the [checker](http://realfavicongenerator.net/favicon_checker) for a quick review) Could you attach the SVG to this issue? (or please mail it to me if that's not possible).

**Comment by ghost** [comment]
It does not display neither in Safari, Safari Technology Preview nor Firefox Developper Edition.

Checker does not work as check never ends.

I've send the SVG file by mail.

**Comment by MoOx** [comment]
In latest macOS Sierra version, the produced svg file do not work on Safari when tab is pinned. I have just nothing.

I have double checked every parameters.

![screen shot 2016-09-08 at 16 42 37](https://cloud.githubusercontent.com/assets/157534/18353681/45fca306-75e3-11e6-821c-fef5b1a728d3.png)

**Comment by phbernard** [comment]
Damn! Thank you for reporting.

So I wanted to reproduce the issue, only to discover that I have to pay 99€ to download a beta product I'll have for free when it's ready. Procrastination suddenly became my best ally.

What you observe is unexpected because Safari usually doesn't behaves like this when there is a problem with the mask icon (eg. when the `color` attribute is absent). It usually falls back to its default behavior, which is to generate an icon with the first letter of the domain name (so pinning example.com creates a "E" icon). Two hypothesis:

1) Safari's behavior changes with Sierra. As simple as this.
2) Safari doesn't scale the icon anymore. If this hypothesis is true, then what you see is the 16x16 top left corner of your much larger icon (which would be empty in this example).

I updated the [compatibility test](https://realfavicongenerator.net/favicon_compatibility_test), and somehow hacked it to compare the "classic", buggy, high resolution icon and the expected, 16x16 icon. Could you run it?
- The first test has a 16x16 icon. You should see the expected result, which is:

![image](https://cloud.githubusercontent.com/assets/423852/18368044/2be9850c-761e-11e6-969c-91d558481240.png)

If you don't see this, it means that the resolution of the icon is not the culprit.
- The second test still has a high resolution icon, so this time the icon should be wrong. If hypothesis 2 is true, you should see an isosceles right triangle.

**Comment by phbernard** [comment]
I finally installed macos Sierra (which is available for free after all).

I don't reproduce the issue: the icon is displayed correctly, whatever the viewBox (16x16 or a lot more).

@MoOx Could you paste your master image and the parameter you used to generate the SVG icon for Safari? Or, as an alternative, could you send me your SVG by email?

**Comment by MoOx** [comment]
I can't find it again. Will reopen if I get this again.

**Comment by MoOx** [comment]
Oh I can't close this :/

**Comment by phbernard** [comment]
Fixed in branch `package_v0_14`

**Comment by phbernard** [comment]
Deployed a minute ago.
