### ISSUE TITLE
favicon.json not being generated when RoR is chosen

### ISSUE THREAD

**Issue by vital-edu** [RealFaviconGenerator/realfavicongenerator#244]
The loading is infinite or simples generates nothing.

![selection_001](https://cloud.githubusercontent.com/assets/5282301/15865550/9f3798a2-2cb1-11e6-9468-0530e12e06e8.png)

**Comment by phbernard** [comment]
I can't reproduce: the information are displayed after a few seconds on my station.

Do you have any JS issue in the console?

**Comment by vital-edu** [comment]
I tried again today and it is working.
I have no idea of what changed since the day I tried. (I used the exactly same machine, browser and logo)

But I am happy that it is everything okay now.
Maybe was a problem in the server connection.

**Comment by vital-edu** [comment]
For some reason the problem is back.

Console error:
favicon_package.php?file_id=p1akqljae0lp6188l17meriv3696&v=20160125:148 Uncaught TypeError: element.find(...).zclip is not a function

![selection_001](https://cloud.githubusercontent.com/assets/5282301/15931593/c95c6fe4-2e2e-11e6-8b10-8ba160861c3d.png)

I cannot reproduce the error, it is aleatory. Sometimes occurs, sometimes don't. I tried change nothing besides the Chrome App Name and  the error appears (using SVG or PNG images).

Try use a specific image in windows 8: it is the only case that always reproduced the error.

**Comment by phbernard** [comment]
Thanks for having taken the time to reproduce the issue.

This is because of ZClip, the component I use to copy text to the clipboard. I removed it and implemented a more classic behavior: the whole code snippet is selected when you click it. No more ZClip, so probably no more error like this.

The change will be deployed in a few days.

**Comment by vital-edu** [comment]
Great!
Thank you! You are doing a great work!

**Comment by phbernard** [comment]
Thank you for your feedback! :)
