### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by eatnabout** [RealFaviconGenerator/realfavicongenerator#25]
Hi, I've created a favicon using a large square image (472x472) via your site.  I've placed favicon.ico and all related png files in the root directory of my site, but when I run the checker I get these errors still:

Some recommended PNG favicons are missing (or their sizes attribute is not set):

```
16x16 picture
32x32 picture
96x96 picture
160x160 picture
196x196 picture
```

Some iOS pictures are not declared:

```
114x114 picture
72x72 picture
144x144 picture
60x60 picture
120x120 picture
76x76 picture
152x152 picture
```

Picture for Windows 8 / IE 10 tile is not declared.

**Comment by phbernard** [comment]
Weird. Is your site accessible, so I can review the code and pictures?

**Comment by eatnabout** [comment]
Yes it is, you can access it at http://eatnabout.com

Thanks!

Eat 'n About
http://eatnabout.com | eatnabout@gmail.com

[image: https://facebook.com/eatnabout] https://www.facebook.com/eatnabout|
[image: https://twitter.com/eatnabout] https://twitter.com/eatnabout
| [image:
https://plus.google.com/+Eatnabout1]
https://plus.google.com/+Eatnabout1| [image:
http://www.pinterest.com/eatnabout] http://www.pinterest.com/eatnabout

**Comment by phbernard** [comment]
I reviewed the code of the homepage of http://eatnabout.com/ and I couldn't find the code related to favicon. Did you copied/pasted it? However, the files are present: http://eatnabout.com/favicon.ico, http://eatnabout.com/browserconfig.xml, etc. , which is why the favicon should often work fine.

**Comment by eatnabout** [comment]
Wow, I don't know how I missed that!  Regenerated and pasted the code into
the <HEAD> section and everything tests fine now.  Sorry for the bother and
feel free to delete the support thread (or mark as resolved).  Thanks for
the support!

Eat 'n About
http://eatnabout.com | eatnabout@gmail.com

[image: https://facebook.com/eatnabout] https://www.facebook.com/eatnabout|
[image: https://twitter.com/eatnabout] https://twitter.com/eatnabout
| [image:
https://plus.google.com/+Eatnabout1]
https://plus.google.com/+Eatnabout1| [image:
http://www.pinterest.com/eatnabout] http://www.pinterest.com/eatnabout

**Comment by phbernard** [comment]
No problem, you're welcome!
