### ISSUE TITLE
Retina IPad not showing favicon in Chrome bookmark

### ISSUE THREAD

**Issue by BillMcK99** [RealFaviconGenerator/realfavicongenerator#251]
The bookmark for Chrome is not showing on the iPad but it is for Safari.  Works for the Mac and PC as well.

**Comment by phbernard** [comment]
Weird. Could you run the [compatibility test](http://realfavicongenerator.net/favicon_compatibility)? It would help understand which icon is picked (... or not).

**Comment by BillMcK99** [comment]
I just did the test and submitted. Thanks.

**Comment by phbernard** [comment]
What I observe is that Chrome takes the regular 32x32 PNG icon:

![image](https://cloud.githubusercontent.com/assets/423852/16592515/5c20da92-42e1-11e6-8a1b-f5a95d196fa6.png)

Actually this is not ideal: on my iPad Mini, the icon is 40x40, so it might be a bit blurred. But nothing critical. It's better than the Google icon.

**Comment by BillMcK99** [comment]
Thanks for looking but the bookmark is just the letter. It's not showing any picture in the bookmark manager.

**Comment by phbernard** [comment]
Could you give the the URL of the tested site? (you can drop me an email if you don't want to put it here).

**Comment by BillMcK99** [comment]
This is the site.  Thanks.
Bill

http://guysmovieblog.com/

From:  Philippe Bernard notifications@github.com
Reply-To:  RealFaviconGenerator/realfavicongenerator
<reply+0133d208a83f6a4784306fcb497c57e90966f84203377d6992cf00000001139727039
2a169ce09afff8e@reply.github.com>
Date:  Friday, July 8, 2016 at 4:32 AM
To:  RealFaviconGenerator/realfavicongenerator
realfavicongenerator@noreply.github.com
Cc:  BillMcK99 mrbillvu@gmail.com, Author author@noreply.github.com
Subject:  Re: [RealFaviconGenerator/realfavicongenerator] Retina IPad not
showing favicon in Chrome bookmark (#251)

Could you give the the URL of the tested site? (you can drop me an email if
you don't want to put it here).


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RealFaviconGenerator/realfavicongenerator/issues/251#iss
uecomment-231304764> , or mute the thread
<https://github.com/notifications/unsubscribe/ATPSCPgUdiFTk6OHFrGk4ISlgkQ-1f
RGks5qTgsDgaJpZM4I_bMi> .

**Comment by phbernard** [comment]
(FYI I've just sent you an email)

**Comment by phbernard** [comment]
The issue was discussed by email. I think we can close it. But don't hesitate to open it if there is still something wrong.
