### ISSUE TITLE
Android chrome theme-color gone

### ISSUE THREAD

**Issue by jessetinell** [RealFaviconGenerator/realfavicongenerator#253]
The meta-tag "theme-color" is not generated in this new version of RFG.

I read the blog post about "5 lines of code" and I wonder if it was meant to be removed? Either way it should not be possible to select color of the Switcher (or splash screen) if they are removed from the generated output.
The manifest does not contain these colors either.

Nice update though!

**Comment by phbernard** [comment]
Thank you for reporting. Someone told me about this issue already and it was fixed a few minutes ago: the manifest file now contains `theme_color`, which Android Chrome uses as expected.

**Comment by jessetinell** [comment]
Wow nice! :) Thanks!

**Comment by jessetinell** [comment]
hmm but the `<meta name="theme-color">` is still gone.
It was nice to have but I guess it's a line you would have to add manually from now on? :)

The `theme_color` in manifest does not change tab color on Chrome - Android. 
Custom tab color really enhances the mobile experience.

**Comment by phbernard** [comment]
Oh, got it. `theme_color` in the manifest is used only to color the title bar in task switcher when the site was displayed as an app (from a linked created from the home screen). Whereas the `theme-color` meta is used to color the upper bar during classic navigation.

Thus these two "theme colors" are not identical and both should be declared.

**Comment by phbernard** [comment]
Fixed (and [tested](https://github.com/RealFaviconGenerator/realfavicongenerator-api-test-suite/commit/d7279a16762db47eee4263c86760985bf4d3fd41)).

**Comment by rugk** [comment]
So I think this issue can be closed...

**Comment by jessetinell** [comment]
Great! :) @phbernard

**Comment by phbernard** [comment]
Good! I'm glad this one is over.
