### ISSUE TITLE
downloads favicon_code.php 

### ISSUE THREAD

**Issue by rugk** [RealFaviconGenerator/realfavicongenerator#254]
Clicking on https://realfavicongenerator.net/favicon_code.php?... to download the JSON with Base64 included downloads the correct file, but the filename is `favicon_code.php`, which is quite confusing. :smile:

**Comment by phbernard** [comment]
When are you offered to click this link? It's supposed to be accessed via Ajax requests. Unless you played with the dev console, you shouldn't know about it.

**Comment by rugk** [comment]
Above I shortened the URL. (showed by the `…` :wink: )

This is where to click to see this:
![rfgclick](https://cloud.githubusercontent.com/assets/11966684/16557784/0e20260e-41e2-11e6-9a91-93c8df0a4d73.png)

So the full link is e.g.: https://realfavicongenerator.net/favicon_code.php?file_id=50626a2114f48b30401eb78e64f945823d172a20&format=rfg_api&image_content=inline

And the file it downloads has a `php` file extension:
![rfgjsondownload](https://cloud.githubusercontent.com/assets/11966684/16557806/2b5a5d84-41e2-11e6-9825-da6ba8c1838e.png)

**Comment by phbernard** [comment]
Oh! I get it. It's fixed. `request.json` should make more sense :)

**Comment by rugk** [comment]
So as it is fixed, I am closing this issue.
