### ISSUE TITLE
JS errors when HTTPS site used 

### ISSUE THREAD

**Issue by rugk** [RealFaviconGenerator/realfavicongenerator#256]
Use https://realfavicongenerator.net/ to generate favicons. There are two issues:
1. It does not detect when the icon generation finished. It is always loading and I had to hit F5 to get it showing up correctly.
2. When I publish the icon, it does not redirect to the new page. (I saw that Firefox JS Debugger was triggered in that Console)

**Comment by phbernard** [comment]
1. Really? Any JS error about his? Most of the time I'm using HTTPS so at least I can say that this issue is not 100% reproducible.
2. You mean when you share it with the "Share it!" button? It's supposed to open a dialog. There is no redirection, but a link you can click to view the new page in another tab.

**Comment by rugk** [comment]
1. Just tried it again and now it works... Maybe I did not wait enough.
2. Here there really is a JS error. Don't know if it has to do something with HTTPS, but at least the URL the JS tries to redirect is a HTTP URL.
   So more details now:
3. Yes, it opens a dialog, but then nothing happens (except the display of a loading bar)
4. Firefox shows me there is a "Reference error". Here is a screenshot:
   ![sharefaviconjserror](https://cloud.githubusercontent.com/assets/11966684/16557566/f99fd54a-41e0-11e6-9873-90b3bb2efec2.png)
5. As a workaround I always copy the URL (`url` from the right) and paste it into the address bar, which opens the correct site.

**Comment by tostinni** [comment]
Not sure if this is related but I have a HTTP 500 error when checking a website with HTTPS on this URL using GET `http://realfavicongenerator.net/analyze_favicon?site=https://www.adb-solidatech.fr/&ignore_root_issues=on` and the process to check icons never stop.

**Comment by phbernard** [comment]
@rugk Ok. The reference error comes from the LinkedIn share button. Not normal, but that shouldn't be a big deal. I'm going to do more testing with the dialog and HTTP/HTTPS.

@tostinni This URL works for me, I get a report: https://realfavicongenerator.net/favicon_checker?site=https%3A%2F%2Fwww.adb-solidatech.fr&ignore_root_issues=on . Do you know if adb-solidatech changed during the last few hours?

**Comment by rugk** [comment]
> Not normal, but that shouldn't be a big deal.

Okay, but the site also does not redirect me. So in fact that's still important - not a big deal maybe, but bad if it does not work..

**Comment by rugk** [comment]
>  The reference error comes from the LinkedIn share button.

Maybe this is also blocked in my browser as I have some anti-tracking addons installed.

On the home page I also get this:
![hompagejsissue](https://cloud.githubusercontent.com/assets/11966684/16590707/e9a3e7aa-42d8-11e6-95cf-036f982ab6b7.png)

Seems to be from the AddThis button. However this error does not matter as everything works correctly anyway...

As for a first test you can try it with Firefox Tracking Protection (just open a new private window to test this).

**Comment by tostinni** [comment]
@phbernard it looks like it's working now. We were updating this website design but not in the last few hours of me noticing this error. Anyway for me it looks fine now.

Thanks a lot.

**Comment by phbernard** [comment]
@rugk AddThis issue fixed!

@tostinni Great!

**Comment by rugk** [comment]
> @rugk AddThis issue fixed!

Yes, that's working now.

But the JS error when sharing your icon is still not fixed.

**Comment by rugk** [comment]
So now I get this error when trying to share the favicon and I cannot get out the URL of the page now:
![faviconissue](https://cloud.githubusercontent.com/assets/11966684/16901766/f1f8bef8-4c4c-11e6-9e28-896bc0a20104.PNG)

**Comment by phbernard** [comment]
I definitely can't reproduce the error, neither with Chrome nor with Firefox.

The only way I can have this error is by removing the line in charge of loading the LinkedIn sharing lib (`//platform.linkedin.com/in.js`). Well, if you had a problem loading this file, I suppose you would have an explicit error in your console, so it must not be this. What might also happen is that LinkedIn lib is still not loaded when the sharing code is triggered. But this code is behind a `document.ready`, so that shouldn't happen either.

Just in case: what you do see in your network logs regarding `//platform.linkedin.com/in.js`? Do you see it loaded correctly?

**Comment by rugk** [comment]
> Well, if you had a problem loading this file, I suppose you would have an explicit error in your console, so it must not be this.

I have not screenshotted the whole console. I am quite sure it is this as I use Firefox Tracking Protection (as said: try it in a Firefox private window).
So consider it not being loaded. The main functionality of a website should not depend on social media buttons.

**Comment by phbernard** [comment]
Oh, sorry. NOW I see it. It's fixed. I let you confirm it's okay for you too, but now the LinkedIn button should just be invisible in your browser (along with the others FB and Twitter buttons if FF blocks everything, as mine does in incognito mode).

**Comment by rugk** [comment]
Yeah, it works now. Thanks for fixing it!
