### ISSUE TITLE
Safari icon display broken in "featured favicons"

### ISSUE THREAD

**Issue by rugk** [RealFaviconGenerator/realfavicongenerator#257]
This is the featured favicon: https://realfavicongenerator.net/featured_favicons/p1amqj59tu18ro55c1a7rik01tsc6

For reference, here the JSON to reproduce: https://gist.github.com/rugk/b402febcca6b233007b4fb0131c86fab

In the creation steps the favicon for Safari was however displayed correctly (the E was clearly visible), and also the SVG is a good one. (ZIP attached: [favicons.zip](https://github.com/RealFaviconGenerator/realfavicongenerator/files/346057/favicons.zip))

See https://github.com/audreyt/ethercalc/pull/393 for more information.

**Comment by phbernard** [comment]
Oh, that's right. Just to confirm, this is an issue with the presentation itself, not the generated icon you downloaded. So you can safely use the package you downloaded.

This is fixed: the Safari presentation now looks correct. This is for new icons only, so https://realfavicongenerator.net/featured_favicons/p1amqj59tu18ro55c1a7rik01tsc6 still shows an issue (and that won't change).

There is a difference between what I get on my dev VM and the prod server (which are supposed to host exactly the same libs and ImageMagick). I tried various versions of IM, without success. In the end, I changed the way the presentation is created (IM is full of opportunities :) )

**Comment by rugk** [comment]
> IM is full of opportunities :)

Yeah, and full of [vulnerabilities](https://imagetragick.com/)... 😑

So make sure to run a recent version and properly check image files to not let malicious files get to ImageMagick. More information here: http://www.openwall.com/lists/oss-security/2016/05/03/18
BTW as an alternative there is http://www.graphicsmagick.org/, but it supports less file types (< 200 as ImageMagick).

**Comment by rugk** [comment]
As this issue is fixed, can it be closed?
