### ISSUE TITLE
Cookie note linking to Google?

### ISSUE THREAD

**Issue by rugk** [RealFaviconGenerator/realfavicongenerator#258]
Do you think it is really such a good idea to "outsource" your privacy policy (which is also [very short](https://realfavicongenerator.net/privacy_policy)) and link to Google in your [cookie statement](https://realfavicongenerator.net/cookies)?

I mean this is Googles privacy policy you're linking to, which does not represent your whole site. If you use Google ads/analytics or something like this you naturally have to link to the Google Policy, but this should not be the only thing you say about this...

**Comment by phbernard** [comment]
That's right, the cookie policy is quite light and even not accurate. I've just updated it, thanks to http://cookiepolicygenerator.com/
