### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by rugk** [RealFaviconGenerator/realfavicongenerator#264]
I think in the last time you [have fixed some issues](https://github.com/RealFaviconGenerator/realfavicongenerator/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20created%3A%3E2016-05-17%20), but you have not updated your [change log](https://realfavicongenerator.net/change_log).

**Comment by phbernard** [comment]
The change log related only to the generated icons and code. It is used to trigger updates. For example, the WordPress plugin can automatically re-generate the icons when applicable.

The issues fixed recently are linked to the site itself, not the generated icons and code. So no change log update this time :)
