### ISSUE TITLE
Pick sizes for favicon.ico

### ISSUE THREAD

**Issue by gemedet** [RealFaviconGenerator/realfavicongenerator#266]
As a solution to #155, could we get an option to pick which image sizes are generated into the favicon.ico? Even [Google](http://www.google.com/favicon.ico) and [Apple](http://www.apple.com/favicon.ico) only have 16px and 32px in their favicons.

**Comment by phbernard** [comment]
This makes sense. After all you can already select the iOS, Android, etc. sizes you want. So why not `favicon.ico`?

I'm working (although very slowly) on a definitive "desktop" setup: what is the best set of icons for all browsers, from IE 6, 7 or 8 (not sure which one should be the older one to support yet) to all modern desktop browsers. That should provide informed defaults (in addition to a lot of checkboxes people don't want to deal with anyway).

**Comment by gemedet** [comment]
Great, glad to hear you're making progress!

**Comment by phbernard** [comment]
This issue will be addressed along with #221
