### ISSUE TITLE
Store configuration into a file

### ISSUE THREAD

**Issue by mitar** [RealFaviconGenerator/realfavicongenerator#268]
I really like how [Fontello](http://fontello.com/) allow you to create a JSON file with configuration you can then import to get to the previous state of working. I can then commit this file into a repository along the fonts and have it ready next time to continue working.

I would love if this generator would have something similar. So I could store configuration and regenerate icons importing that file.

**Comment by phbernard** [comment]
Yup! Actually this was already submitted (#263)
