### ISSUE TITLE
RealFaviconGenerator + favicons

### ISSUE THREAD

**Issue by alexander-akait** [RealFaviconGenerator/realfavicongenerator#269]
Ref: https://github.com/haydenbleasel/favicons.

I think if we will merge `RealFaviconGenerator` and `Favicons` everyone will win — users will get more features, and we will have more free time. We already have great examples of `ESLint` + `JSCS`, `Babel + esnext`, `Rails` + `Merb`, `CSSLint` + `Stylelint`.

@phbernard @phbernard what do you think?

Benefits for Users:
1. One open source package. You no longer have to monitor the difference between the packets (icons, manifests and etc).
2.One community. We will be able to quickly solve the problem.
3. We can rewrite on ES6 or above.
4. Support legacy node (4, 5, 6).
5. Fast generation using package.
6. We can add CLI for building throw `npm` scripts.
7. Support .*rc configuration.
8. One `gulp`, `grunt` and etc plugins.
9. And more enchantments.

**Comment by phbernard** [comment]
Actually @haydenbleasel and I have worked together. However, we were both very busy (and not available at the same time) and we couldn't achieve a single, unified plugin.

I would love to unify the plugins. Although I like the idea to have "real favicon" in the name of the plugin, that's not required to me. So I'm okay with switching to `favicons`.

I'm not willing to spend too much time working on this topic. To me, the situation is not ideal but okay as it is. I have much more important tasks to work on. However, I'm willing to make the change in RFG web site the day a unified plugin is ready. In other words, as soon as such plugin will be ready, I'll update the step-by-step instructions given by RFG to use `favicons`. And `gulp-real-favicon` will become somehow deprecated.

**Why**

My main concern is the apparent overlap of features, which is not that obvious after all. Currently, you have two (good) ways to generate favicons with Gulp:
- `favicons`: Basic options. Edit your configuration manually. Only JS dependencies, so this solution works everywhere and it does rely on an external service.
- `gulp-real-favicon`: Advanced options. Build your configuration with a UI. This solution relies on an external service, so you may fear about its availability.

With a unified plugin, what would become possible?
- Use RFG UI to build a configuration easily, then use `favicons` offline mode to generate the icons locally. That probably won't work: @haydenbleasel spent time on making `favicons` rely on JS libs only. And I doubt these libs can cover all RFG options. Or `favicons` could do best effort, supporting only some of RFG options. That sounds more frustrating than useful.
- Create a `favicons` config manually, then use RFG to generate the icons. This is technically possible and not very complex. But what for? Everything is already done for you locally in pure JS.

So in terms of features, `favicons` and `gulp-real-favicon` will look like "two plugins in one", merged by their common topic alone.

Plus, these plugins have very little behavior in common (eg. there is no image manipulation in `gulp-real-favicon`). So there is little opportunity for code sharing. The way the HTML is injected in the pages, but it's no big deal.

As I don't plan to work on the plugin itself, I have no strong feeling about this. But anyone wanting to spend hours on the topic should have answers to these remarks.

**How**

If you (or someone reading this post) wish to work on this topic and want it to replace  `gulp-real-favicon` in RFG, here is the process I propose:
- Write some sample instructions (similar to the one given in RFG result page, 'Gulp tab), so we can discuss them and make sure we agree on their format.
- Code. The easiest part, really :)
- Once it's ready, I update RFG so it gives instructions to use the new plugin.
