### ISSUE TITLE
Checker preview shows 'Window 8 and 10'

### ISSUE THREAD

**Issue by RaceProUK** [RealFaviconGenerator/realfavicongenerator#271]
![image](https://cloud.githubusercontent.com/assets/10373748/17671065/e2d3344a-630c-11e6-96b2-2e23b252902a.png)

Should read 'Window**s** 8 and 10' :wink:

**Comment by phbernard** [comment]
Wow! That's a good one :) Thanks for reporting it.

It's fixed, but I'll release the change next week (no routine deployment on holidays, it's bad for karma)

**Comment by phbernard** [comment]
Deployed some time ago.
