### ISSUE TITLE
Says files are missing except that they are there.

### ISSUE THREAD

**Issue by wormeyman** [RealFaviconGenerator/realfavicongenerator#28]
[http://gccpreschool.com/](http://gccpreschool.com/)
# Error Codes

**Some recommended PNG favicons are missing (or their sizes attribute is not set):**
- 16x16 picture
- 32x32 picture
- 96x96 picture
- 160x160 picture
- 196x196 picture

**Some iOS pictures are not declared:**
- 114x114 picture
- 72x72 picture
- 144x144 picture
- 60x60 picture
- 120x120 picture
- 76x76 picture
- 152x152 picture

**Picture for Windows 8 / IE 10 tile is not declared. Learn more.**
# My Question
- However I have all the proper files in the root of my website? Not sure what could be wrong here?
- I have a genesis WordPress theme if that matters. And used [this guide](http://www.wpstuffs.com/custom-favicon-genesis/) to change it manually.

**Comment by phbernard** [comment]
I've just run the checker against http://gccpreschool.com/ and it returned no error. Plus you closed the issue a few hours ago, so I suppose you figure this out by yourself.
