### ISSUE TITLE
Broken link / missing section on not declaring the favicon

### ISSUE THREAD

**Issue by dandv** [RealFaviconGenerator/realfavicongenerator#280]
> Granted: this is because we ask you to [not declare](http://realfavicongenerator.net/#why_ico_not_declared) `favicon.ico`.

![image](https://cloud.githubusercontent.com/assets/33569/19096990/e8601160-8a55-11e6-923b-98153826f0f9.png)

Should link to the /faq/.

Impacts https://github.com/dandv/imagecapture/issues/4

**Comment by phbernard** [comment]
Fixed and deployed.
