### ISSUE TITLE
Don't escape slashes in manifest.json

### ISSUE THREAD

**Issue by dandv** [RealFaviconGenerator/realfavicongenerator#282]
Here's the manifest.json I get for [my icon](https://github.com/dandv/imagecapture):

``` json
{
    "name": "ImageCapture polyfill demo",
    "icons": [
        {
            "src": "\/icons\/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image\/png"
        },
        {
            "src": "\/icons\/android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image\/png"
        }
    ],
    "theme_color": "#ffffff",
    "display": "standalone"
}
```

**Comment by phbernard** [comment]
As this [SO thread](http://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped) explains it, it's interesting when embedding JSON in a `script` tag, but it's pointless here. Slashes shouldn't be escaped in the manifest.

**Comment by phbernard** [comment]
Fixed in branch `package_v0_14`

**Comment by phbernard** [comment]
Deployed a minute ago.
