### ISSUE TITLE
Use uniform spacing and (LF-only) line endings

### ISSUE THREAD

**Issue by dandv** [RealFaviconGenerator/realfavicongenerator#283]
RFG uses a mix of spaces, tabs, LF, and CR+LF line separators:
- browser.config.xml is CRL+LF-separated. Arguably this is because it targets Windows, but the file likely won't be edited on Windows, and there are other text files in the package that Notepad will display in one lines. The XML uses spaces for indentation - great.
- manifest.json uses LF-only line separators, but tabs instead of spaces for indentation
- safari-pinned-tab uses LF line endings and wraps at 74 chars/line.

**Comment by phbernard** [comment]
Thanks. I never realized this.

So:
- `manifest.json` looks okay. This is what [`json_encode` and `JSON_PRETTY_PRINT`](http://php.net/manual/fr/function.json-encode.php) generate so I rather stick to it.
- `browserconfig.xml`: let's switch to LF-only and tabs, to match `manifest.json`. Plus it's (a little bit) more compact.
- Safari pinned tabs SVG icon: SVGO will decide, see #261.

**Comment by phbernard** [comment]
Fixed in branch `package_v0_14`

**Comment by phbernard** [comment]
Deployed a minute ago.

**Comment by XhmikosR** [comment]
@phbernard: nitpicking but manifest.json does not have the end of file line break like the browserconfig.xml has. :)

**Comment by phbernard** [comment]
Hex editor speaking :) Both `manifest.json` and `browserconfig.xml` have UNIX-style (ie. 0x0A) end of line.

Do you observe something else?

**Comment by XhmikosR** [comment]
Yeah. I tried it 3 times and the result is the same. The manifest doesn't
have the end of file line break while the xml does :)

**Comment by phbernard** [comment]
I've just tested it again. I clearly see 0x0a everywhere (and not 0x0d0a):

JSON

![image](https://cloud.githubusercontent.com/assets/423852/22098399/5872b466-de26-11e6-95d5-58203a36cb6e.png)

XML

![image](https://cloud.githubusercontent.com/assets/423852/22098419/7d7e2952-de26-11e6-9e7b-756a98fa3ba5.png)

Could you tell me how you check the end of line?

**Comment by XhmikosR** [comment]
It's obvious for me just by opening the files...

See the attached images.

![browserconfig](https://cloud.githubusercontent.com/assets/349621/22098591/d0bcef14-de2f-11e6-9406-03ff0f05787f.png)

![manifest](https://cloud.githubusercontent.com/assets/349621/22098594/d3ff10f8-de2f-11e6-967e-dcf46149a8dc.png)

As you can see manifest.json doesn't have the end of file line break.

**Comment by phbernard** [comment]
Oh, okay! The final line break at the end of the file! Sorry, I misread your first message, I thought you were talking about all ends of line.

I consider this as another issue, although it would have been good to fix everything at once. I just entered https://github.com/RealFaviconGenerator/realfavicongenerator/issues/304
