### ISSUE TITLE
leading slash in href path!?

### ISSUE THREAD

**Issue by empee1** [RealFaviconGenerator/realfavicongenerator#285]
I had to remove the leading slash in the href for Google Chrome and IE11 to get things working!

**Comment by phbernard** [comment]
In general, the leading slash works. Is your site live so I can review it and understand why this leading slash have failed in your case?

**Comment by empee1** [comment]
Hi Philippe,

 

The site is http://verzorgdevoet.nl

In the meantime I replaced the icons, generated with your tool, one level deeper, to the img folder:

               <link rel="apple-touch-icon" href="img/favicon_apple-touch.png?v=8jewNq84bp" sizes="180x180">

               <link rel="icon"                               href="img/favicon-32x32.png?v=8jewNq84bp"  type="image/png" sizes="32x32">

               <link rel="icon"                                href="img/favicon-16x16.png?v=8jewNq84bp"  type="image/png" sizes="16x16">

               <link rel="manifest"                        href="img/favicon_manifest.json?v=8jewNq84bp">

               <link rel="mask-icon"                     href="img/favicon_safari-pinned-tab.svg?v=8jewNq84bp" color="#5bbad5">

               <link rel="shortcut icon"                href="img/favicon.ico?v=8jewNq84bp">

Also here no leading slash for the hrefs, and this seems to works fine.

 

Regards 

Martin Pahlplatz

 

Van: Philippe Bernard [mailto:notifications@github.com] 
Verzonden: dinsdag 3 januari 2017 10:50
Aan: RealFaviconGenerator/realfavicongenerator
CC: empee1; Author
Onderwerp: Re: [RealFaviconGenerator/realfavicongenerator] leading slash in href path!? (#285)

 

In general, the leading slash works. Is your site live so I can review it and understand why this leading slash have failed in your case?

**Comment by phbernard** [comment]
I've checked your current version (eg. `img/favicon_apple-touch.png?v=8jewNq84bp`) and it works for me, too. I don't see how the "slashed version" (eg. `/img/favicon_apple-touch.png?v=8jewNq84bp`) wouldn't work.

**Comment by empee1** [comment]
The url is redirected from a domainname provider to another provider hosting the site.
Could the problem be caused by a training slash in the redirected url?
Then I will look further at the DNS redirection settings.

Thank you for your response, and as you might guess, your tool was of great help!

You may close the issue. 

Kindest regards,
Martin 😉

**Comment by phbernard** [comment]
Alright! Thank you!!

Please reopen if there is anything new
