### ISSUE TITLE
Receiving non-existant page error

### ISSUE THREAD

**Issue by harvesthosts** [RealFaviconGenerator/realfavicongenerator#286]
Non-existant page errors showing up at https://harvesthosts.com/apple-touch-icon-precomposed.png .  I've updated all the favicon files but still have the errors.  Any suggestions?

**Comment by phbernard** [comment]
This is the second time I encounter this question today, so I guess it deserves a FAQ entry :) I've just added http://realfavicongenerator.net/faq#ios-404-error
