### ISSUE TITLE
Rails install instructions incorrect

### ISSUE THREAD

**Issue by sambrannon** [RealFaviconGenerator/realfavicongenerator#287]
On the Rails favicon generator, one of the install steps is it set your favicon render path like so...

``` ruby
<%= render 'favicon' %>
```

However, the generator places that partial into `app/views/application/_favicon.html.erb`. In development environments it still works, but in production it has been [known to fail](https://github.com/RealFaviconGenerator/rails_real_favicon/issues/10).

I fixed this by just updating my render path to...

``` ruby
<%= render 'application/favicon' %>
```

... which makes things work in my dev, test and production environments.

**Comment by phbernard** [comment]
Thank you for reporting!

Fixed a minute ago.
