### ISSUE TITLE
Favicon checker doesn't recognize Camel Case URLs

### ISSUE THREAD

**Issue by Daquer** [RealFaviconGenerator/realfavicongenerator#288]
The URL of a site I've tested have letters in Upper Case and Lower Case and it doesn't recognize and show this error:

**We got a 404 (Not Found) error while accessing <URL>**

**Comment by phbernard** [comment]
You mean when you submit "http://RealFaviconGenerator.net" instead of the classic "http://realfavicongenerator.net" to the [checker](http://realfavicongenerator.net/favicon_checker)? I've tested this case and it works.

**Comment by Daquer** [comment]
No, I mean when I submit "http://realfavicongenerator.nethttp://realfavicongenerator.net//CamelCasePage" instead of the classic "http://realfavicongenerator.nethttp://realfavicongenerator.net//camelcasepage".

The problem is after the slash "/", the path part of the url.

Hope it helps.

---

De: Philippe Bernard notifications@github.com
Enviado: segunda-feira, 31 de outubro de 2016 15:37
Para: RealFaviconGenerator/realfavicongenerator
Cc: Daquer; Author
Assunto: Re: [RealFaviconGenerator/realfavicongenerator] Favicon checker doesn't recognize Camel Case URLs (#288)

You mean when you submit "http://RealFaviconGenerator.net" instead of the classic "http://realfavicongenerator.net" to the checkerhttp://realfavicongenerator.net/favicon_checker? I've tested this case and it works.

[http://realfavicongenerator.net/favicon_generator_og_image.png]http://realfavicongenerator.net/

Favicon Generator for all platforms: iOS, Android, PC/Mac...http://realfavicongenerator.net/
realfavicongenerator.net
Why RealFaviconGenerator No hard decision. With so many platforms and icons, it's hard to know exactly what you should do. What are the dimensions of favicon.ico?

[http://realfavicongenerator.net/favicon_generator_og_image.png]http://realfavicongenerator.net/

Favicon Generator for all platforms: iOS, Android, PC/Mac...http://realfavicongenerator.net/
realfavicongenerator.net
Why RealFaviconGenerator No hard decision. With so many platforms and icons, it's hard to know exactly what you should do. What are the dimensions of favicon.ico?

##

**Comment by phbernard** [comment]
Got it! Thank you for clarifying.

Fixed and deployed a minute ago.
