### ISSUE TITLE
Spelling error on home page: “Compeling”

### ISSUE THREAD

**Issue by roryokane** [RealFaviconGenerator/realfavicongenerator#290]
Near the bottom of http://realfavicongenerator.net/:

> ### Compeling design, a platform at a time
> 
> Each platform comes with its own design requirements. You can't just use the same picture everywhere. RealFaviconGenerator knows this and lets you craft your icons platform per platform. 

“Compeling” [should be](https://en.wiktionary.org/wiki/compelling) “Compelling”.

**Comment by phbernard** [comment]
Thank you for reporting! Fixed this morning. Now I nedd to understand why this issue is still opened whereas I'm certain to have closed it this morning. Nevermind.
