### ISSUE TITLE
MacBook Touch Bar preview 

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#291]
The new MacBook Touch Bar uses the mask icons of Safari pinned tabs. So RFG already creates this icon.

It would be great if RFG could also show how this icon looks like in the Touch Bar.

**Comment by phbernard** [comment]
Implemented, ready for deployment.

One last step: go to an Apple Store and find a demo MacBook Pro to make sure the preview actually  looks like the real Touch Bar.

My bet:

![image](https://cloud.githubusercontent.com/assets/423852/20340586/92123988-abe2-11e6-9830-f081b7676359.png)

**Comment by Haroenv** [comment]
AFAIK this is working correctly, so this issue can be closed 😄

**Comment by phbernard** [comment]
![walter white](https://cloud.githubusercontent.com/assets/423852/21478580/0b8ac292-cb4d-11e6-90dd-26d867e063b0.jpg)
