### ISSUE TITLE
Safari Mask Icon wrong units in SVG

### ISSUE THREAD

**Issue by an-tex** [RealFaviconGenerator/realfavicongenerator#311]
The generated SVG for the Safari Mask Icon sets the svg width and height to 16pT, instead of 16pX. 16pt translates in my safari to 21px so the icon is deemed invalid and nothing is shown in a pinned tab. Works when I change it to 16px.

So it should be:

`<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="16.000000px" height="16.000000px" viewBox="0 0 16.000000 16.000000"
 preserveAspectRatio="xMidYMid meet">`

instead of:

`<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="16.000000pt" height="16.000000pt" viewBox="0 0 16.000000 16.000000"
 preserveAspectRatio="xMidYMid meet">`

**Comment by phbernard** [comment]
Two things:

- I couldn't find any (good) way to make the unit right. As far as I understand, InkScape (used from the command line) cannot do this.
- I couldn't reliably check if the current icon (with wrong units) work or not. 

In doubt, I prefer to simply rollback the change of #242 .

**Comment by phbernard** [comment]
Deployed a minute ago.
