### ISSUE TITLE
Dedicated picture for small, browser tab favicon

### ISSUE THREAD

**Issue by Jab2870** [RealFaviconGenerator/realfavicongenerator#320]
Hi,
Firstly, thanks for making such a great tool.

A number of times I have used it and got to the final stage after setting up all of my touch icons, only to realise that I should have used a different image initially for the small icons that are shown in the bookmarks bar / tab.  

Could you add an option for a dedicated picture for the browser tabs and bookmarks.

**Comment by kevinvanrijn** [comment]
This is part of https://github.com/RealFaviconGenerator/realfavicongenerator/issues/53

**Comment by Jab2870** [comment]
Duplicate of #53
