### ISSUE TITLE
Preview small favicons when uploading an SVG

### ISSUE THREAD

**Issue by Jab2870** [RealFaviconGenerator/realfavicongenerator#322]
Currently, when you upload a png / jpg etc., we see a 16 px preview of the favicon in the scaling algorithm tab.

I understand why, when using an SVG, the scaling tab is unnecessary but it would be helpful to see a 16px preview somewhere.

I mentioned in #320 that it would also be nice to have a dedicated picture for the small favicons

**Comment by phbernard** [comment]
That's right. I even forgotten this behavior and had to submit an SVG to see it in action :-/

I think this preview will be better served by #323, which I just submitted.

**Comment by Jab2870** [comment]
Excellent!  I look forward to seeing #323 implemented then.  Thanks again for creating such an awesome service
