### ISSUE TITLE
Favicon editor for desktop browsers

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#323]
When RFG was initially written, the iOS and Windows 8 / Metro were the features that made a difference, whereas desktop icon was so mundane. So the proposal was something like "Create great icons for mobile! Oh, and here are desktop icons by the way".

Now RFG should address everything perfectly. And what is missing in here is a genuine desktop icon editor, just like the other editors for iOS, Android, etc.

In addition to the classic preview, such editor should display a magnified version of the tab, since many people have pixel-precise requirement for this particular platform and small icon. This feature might sound easy but is not. As browsers pick different icons for the job, the editor needs to take different scenarios into account. For example, FF pick a 16x16 icon:

![image](https://cloud.githubusercontent.com/assets/423852/25991911/3c2cb81e-3705-11e7-9431-631b2de2439e.png)

On the same PC and same site, Chrome picks the 32x32 icon:

![image](https://cloud.githubusercontent.com/assets/423852/25991932/57bfa6b8-3705-11e7-912f-6710c41f24df.png)

Same site and 4K screen? Chrome still picks the 32x32 icon... and displays it as a 40x40 icon:

![image](https://cloud.githubusercontent.com/assets/423852/25992048/ae20251e-3705-11e7-9df4-5b6babdcf94a.png)

RFG is in the process of being rewritten as [web components](https://realfavicongenerator.net/api/web_components). For now only the new [Facebook editor](https://realfavicongenerator.net/social) was written this way. Favicon editor for desktop browsers would be a great second candidate.

This feature clearly pairs with #53

**Comment by Jab2870** [comment]
Is there any idea on time for this re-write? I completely accept that it is a large amount of work but an idea of a time scale would be useful.  Are we talking Weeks? Months? Years?

Thanks for making such a great service btw.

**Comment by hudri** [comment]
Would be very interested in this feature. All modern favicons (>=57 px) work quite well with one single source, but the good old desktop icons (16px, 32px) suffer deeply from the downscaling. Also Google is now showing (the 16px desktop) fav icons in their search results, on mobile and desktop seach results. We need some love for old-school desktop icons :-)

**Comment by phbernard** [comment]
Done!

Well, not done as described initially. There is no magnifier. Although implementing a rough simulation would be easy, I don't think that would be interesting. A magnifier has to be pixel-precise to be useful. And such magnifier would be quite complex to implement. It would require a lot of experiments and could not rely of regular CSS/JS to be rendered.

Instead, the desktop editors comes with handy options to handle contrast issues, typically if your icon is too light.

**Comment by hudri** [comment]
Maybe a dedicated base image only for desktop browsers would be a better solution

see #53 Allow user to override any picture
