### ISSUE TITLE
Are all realfavicongenerator images loaded on every page request?

### ISSUE THREAD

**Issue by pxwise** [RealFaviconGenerator/realfavicongenerator#33]
Are all realfavicongenerator images loaded on every page request? Does this add file weight and http requests to every page load? Or do browsers download only the relevant favicon?

**Comment by phbernard** [comment]
Browsers do not load pictures on every page requests, which is the good point. So the weight of favicon is quite low.

However, you must know that Chrome and Firefox tend to load too much pictures. But only once: once they have downloaded the pictures, they do not re-load them again and again. See http://realfavicongenerator.net/faq#troubleshootings

**Comment by phbernard** [comment]
I guess this issue can be closed.
