### ISSUE TITLE
realfavicongenerator not working

### ISSUE THREAD

**Issue by kalinero** [RealFaviconGenerator/realfavicongenerator#337]
Just can't figure out what I do wrong as I foloved the steps.

1. Inserted favicon files on root directory
![2017-09-27_1216](https://user-images.githubusercontent.com/32327813/30908467-edc8478e-a37d-11e7-8ed5-1fa9b27450dc.png)

2. Inserted the codes into /head

![2017-09-27_1219](https://user-images.githubusercontent.com/32327813/30908549-2b4eacba-a37e-11e7-9d14-f3cbce261659.png)

But stil get  errors an all platforms: https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.kalinero.si#.Wctzd8gjFaQ

**Comment by smerriman** [comment]
The root directory is /, not /templates/kalinero/.

**Comment by kalinero** [comment]
Thanks!

I needed time to figure this out. It's working now.
