### ISSUE TITLE
missing newline in manifest.json and safari-pinned-tab.svg file

### ISSUE THREAD

**Issue by gemal** [RealFaviconGenerator/realfavicongenerator#341]
please add a trailing newline in the manifest.json and safari-pinned-tab.svg files. this will make it nicer when you checkin the files into git

**Comment by phbernard** [comment]
Manifest: Yup!

Safari icon: Really? The one I've just generated has its ending new line. Can you reproduce?

**Comment by phbernard** [comment]
Manifest: done and deployed a minute ago.

Safari icon: no news is good news :)
