### ISSUE TITLE
manifest file extension should be webmanifest not json

### ISSUE THREAD

**Issue by gemal** [RealFaviconGenerator/realfavicongenerator#342]
I believe the correct extension for the manifest file is webmanifest and not json

https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by MMB1983** [comment]
Hi, 
This is very confusing as different sources give different info:
https://developers.google.com/web/fundamentals/web-app-manifest/
https://www.w3.org/TR/appmanifest/
https://developer.chrome.com/multidevice/android/installtohomescreen

I haven't checked .webmanifest type but .json type work on android just fine :-)

**Comment by alrra** [comment]
> This is very confusing as different sources give different info:
>
> I haven't checked .webmanifest type but .json type work on android just fine :-)

@mastakilla1983: @gemal Most probably opened this issue because of the [`sonarwhal` project](https://sonarwhal.com/), that recommends the `.webmanifest` file extension, and the reasoning behind it is:

> While the [`.webmanifest`](https://w3c.github.io/manifest/#media-type-registration) file extension is not enforced by the specification, nor is it required by browsers, using it makes it:
>
>   * [easier to set custom server configurations](https://github.com/w3c/manifest/issues/346) for the web app manifest file
>   * possible to benefit from [existing configurations](https://github.com/jshttp/mime-db/blob/67a4d013c31e73c47b5d975062f0088aea6cd5cd/src/custom-types.json#L85-L92)

(from: https://sonarwhal.com/docs/user-guide/rules/rule-manifest-file-extension/#why-is-this-important)

**Comment by phbernard** [comment]
I get the point, thank you for reporting.

@alrra You seem to be [involved in this question](https://github.com/w3c/manifest/issues/346). Quick question for you: as most web servers are not configured for the `.webmanifest` extension, they don't send this file with the proper `Content-Type`. Do we know how browsers that support the manifest (eg. Chrome) react to this situation? While I value standards and best practices, I want to make sure this change won't generate regressions.

**Comment by phbernard** [comment]
[Successfully tested against Windows Chrome and Android Chrome](https://realfavicongenerator.net/favicon_compatibility).

Deployed a minute ago.

**Comment by alrra** [comment]
@phbernard Sorry for the delayed answer.

> as most web servers are not configured for the .webmanifest extension, they don't send this file with the proper Content-Type. Do we know how browsers that support the manifest (eg. Chrome) react to this situation?

Browsers (e.g.: Chrome, Samsung Internet) that have support for the web app manifest file don't actually care about what media type the file is served with, they just download it and parse it as JSON.

> Deployed a minute ago.

:+1:

**Comment by phbernard** [comment]
@alrra That's what I observed with Chrome. Thanks for the confirmation!

**Comment by shoulders** [comment]
The post https://github.com/OneSignal/OneSignal-Website-SDK/issues/332 has some useful information on this subject.

For easier content searching: site.manifest manifest.json
