### ISSUE TITLE
Example JSON at https://realfavicongenerator.net/api/non_interactive_api doesn't parse

### ISSUE THREAD

**Issue by darthwalsh** [RealFaviconGenerator/realfavicongenerator#346]
The [JSON example](https://realfavicongenerator.net/api/non_interactive_api#generate_favicon) isn't valid JSON, and returns "JSON could not be parsed. Check your syntax."

There are a couple trailing commas in JSON objects.

**Comment by phbernard** [comment]
Fixed a minute ago.
