### ISSUE TITLE
Vectorize pictures for better scaling results

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#35]
Issue #31 is about offering several algorithms.

Vectorizing bitmap pictures may generate better results... if the vectorization works well. This should be investigated.

**Comment by jacksonj04** [comment]
Related to this, if vectorization proves feasible could there be an option to upload a vector source (ie an SVG or even EPS)?

**Comment by phbernard** [comment]
Soon! This is... issue #34 :)

**Comment by phbernard** [comment]
Safari pinned tabs ( #169 ) was the occasion to work on vectorization. My conclusion: this feature will be quite complicated. Vectorization works well on black and white pictures (really B&W, not grayscale). As soon as we leave this very small niche, things get complicated. So this feature concerns only a particular set of image and is probably not worth the efforts.
