### ISSUE TITLE
<head>.txt Invisible/missing in Zip file on Windows

### ISSUE THREAD

**Issue by jamieburchell** [RealFaviconGenerator/realfavicongenerator#350]
The <head>.txt file included in the Zip file when browsed directly in Windows (10) is missing. The file is only available when extracting the archive using 7Zip, where the file name is changed.

I suspect the issue might be the greater than and less than characters in the file name?

**Comment by phbernard** [comment]
Sorry, which .txt file are we talking about? The favicon package doesn't contain such file (just .xml and .json).

**Comment by jamieburchell** [comment]
Interesting. It appears the zip I was sent contains a "`<head>.txt`" so I'll assume this was (badly) added to the archive after.
