### ISSUE TITLE
the web app manifiest link - add to FAQ

### ISSUE THREAD

**Issue by shoulders** [RealFaviconGenerator/realfavicongenerator#358]
this page from google describes the manifest quitte well and might make a good addition to the FAQ page

https://developers.google.com/web/fundamentals/web-app-manifest/

**Comment by jan-dh** [comment]
+1 for this, maybe expand the generator to create all these options

**Comment by phbernard** [comment]
Done! https://realfavicongenerator.net/faq#manifest
