### ISSUE TITLE
JPG pictures are not supported

### ISSUE THREAD

**Issue by Dvaeer** [RealFaviconGenerator/realfavicongenerator#36]
After selecting an image for upload at http://realfavicongenerator.net/, I see a progress bar but then nothing happens. I tried in Chrome and Firefox on Windows 8 and Windows 7 with a square jpg at different sizes (150px, 260px, 400px).

**Comment by phbernard** [comment]
Oops :( Thank you for reporting.

I'm using Chrome and FF on Windows 8 too, but I can't observe the issue. Could you send me your pictures at philippe@realfavicongenerator.net so I can try to reproduce?

**Comment by phbernard** [comment]
(you sent me the picture by email and I was able to reproduce and fix; thanks!)

The JPG pictures were not supported. It's fixed.

**Comment by Dvaeer** [comment]
Yes, now it works perfectly. Big thank you :)
