### ISSUE TITLE
Favicon does not show for bookmarks

### ISSUE THREAD

**Issue by TobAlt96** [RealFaviconGenerator/realfavicongenerator#374]
Hello,

I tried everything to solve this problem but nothing seems to work...

The Favicons are displayed correctly in every situation including "Adding to Homescreen" but not for bookmarks. As you can see the google favicon is displayed but not the favicon of my site. 
And yes, I already cleared the cache.

![image-1](https://user-images.githubusercontent.com/38104986/38367506-2e49abae-38e3-11e8-8a40-b915beacc1e0.jpg)

**Comment by phbernard** [comment]
Have you cleared the ca... Oh you did :)

Please retry, seriously. Often is works on second try or more. I have observed this a lot of times when running the [compatibility test](https://realfavicongenerator.net/favicon_compatibility_test).

**Comment by TobAlt96** [comment]
Thank you for your fast reply.
I solved the problem. You need to open the website via www.

https://g-talk.de -> still no favicon for bookmarks

https://www.g-talk.de -> works perfect

I‘ve got no clue why Safari does this but it has nothing to do with the generator.

Awesome tool btw :)
