### ISSUE TITLE
Make https the default option in favicon checker

### ISSUE THREAD

**Issue by hipwelljo** [RealFaviconGenerator/realfavicongenerator#389]
http is selected by default currently. Nowadays all sites should be https so it'd be nice to select that by default. Or perhaps even better, can you remove it altogether? Fall back to http if https fails, if it's not included when the url is pasted into the text field?

**Comment by phbernard** [comment]
Having HTTPS by default makes sense. However, if a site does not support it, checking https://example.com fails. But if HTTPS is supported, then HTTP should be supported, too. Either http://example.com is accessible, or a 301 redirection automatically takes place.

In the end, I would say HTTP is a good default. In addition, when you paste `https://example.com` in the Check Favicon mini-form, the protocol is automatically set. So I'm afraid I won't change anything :)
