### ISSUE TITLE
Windows 8 favicon errors still shown by checker

### ISSUE THREAD

**Issue by oldchestnut** [RealFaviconGenerator/realfavicongenerator#40]
After putting all the generated files into the root I still get the following errors when I run the domain through the checker again...

"Some recommended pictures for Windows 8 / IE 11 are missing:
70x70 picture
150x150 picture
310x310 picture
310x150 picture

browserconfig.xml is not present."

broswerconfig.xml is in the root.

As are the following files which were generated. The images listed above were not generated automatically. 
favicon-196x196.png
favicon-160x160.png
favicon-96x96.png
favicon-16x16.png
favicon-32x32.png

**Comment by phbernard** [comment]
Is the web site live, so I can check by myself?

**Comment by oldchestnut** [comment]
yes, is there some way i can private message the address to you?

**Comment by phbernard** [comment]
Sure! Drop me an email at philippe@realfavicongenerator.net

**Comment by phbernard** [comment]
(private exchange summary: http://somesitehere.com/browserconfig.xml is not accessible)

Same observation here. I don't know what's wrong with this file, but at this point the behavior of the checker is normal: browserconfig.xml is not accessible and a Windows 8 device won't present the tiles it declares.

**Comment by oldchestnut** [comment]
I have a very complex .htaccess which could still be causing the problem. I have fixed one part of the htaccess which was blocking browserconfig.xml earlier, but I can see no issues in the htaccess now.

Should I assume that the browserconfig.xml file definitely works and that there is a problem somewhere in my setup?

**Comment by phbernard** [comment]
A regular Windows 8 device (such as the Surface 2) will try to load /browserconfig.xml to discover the tile pictures, and more. If it can't load it... The checker reflects this behavior and it gives the correct diagnosis: browserconfig.xml appears to be missing.

The content of your browserconfig.xml looks correct, and the referenced pictures are accessible. So I think everything will be alright as soon as browserconfig.xml becomes accessible too.

**Comment by oldchestnut** [comment]
OK. I'll continue looking for the issue on my side. 

What is the user agent presented by the checker?

**Comment by phbernard** [comment]
It uses the UA of a Surface 2: "Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0; Touch; rv:11.0) like Gecko". 

However, although filtering by UA will cause no harm today, I advice you to let anyone access this file. For example, surprisingly, Coast (iOS browser made by Opera) uses the 144x144 tile picture. Granted: this picture is not declared in browserconfig.xml. But this is the sign that other browsers and platforms might someday use this file for unforeseen purposes.

**Comment by oldchestnut** [comment]
I found the problem! :)  I had a RedirectMatch 403 (......|config.xml)

This blocked browserconfig.xml, after modifying the rule slightly it now works and all the checks now pass.

Thanks.

**Comment by phbernard** [comment]
Good! You're welcome.
