### ISSUE TITLE
Favicon checker issue

### ISSUE THREAD

**Issue by LightningBlox** [RealFaviconGenerator/realfavicongenerator#403]
It says:
 Favicon checker
Oops! There was a problem :(

Maybe this is just a temporary issue, or maybe we just can't process this site. Anyway we have been notified about this issue and we are going to investigate it.
My website is: https://friv432.weebly.com 
And favicon.ico is located at my other website: https://lain123.neocities.org/favicon.ico
When I visit my website it shows the favicon but when I check it it doesn’t work please help

**Comment by phbernard** [comment]
Thank you for reporting.

This error is because https://friv432.weebly.com/apple-touch-icon.png returns a 410 error.  Clearly the checker is too sensitive here, this is very close to a 404.

**Comment by LightningBlox** [comment]
No but my my apple touch icon is at https://lain123.neocities.org/apple-touch-icon.png
