### ISSUE TITLE
SVG that renders fine in InkScape renders incorrectly

### ISSUE THREAD

**Issue by JadedBlueEyes** [RealFaviconGenerator/realfavicongenerator#406]
<details>
  <summary>SVG source</summary><pre>&lt;?<span class="pl-ent">xml</span><span class="pl-e"> version</span>=<span class="pl-s"><span class="pl-pds">"</span>1.0<span class="pl-pds">"</span></span><span class="pl-e"> encoding</span>=<span class="pl-s"><span class="pl-pds">"</span>UTF-8<span class="pl-pds">"</span></span><span class="pl-e"> standalone</span>=<span class="pl-s"><span class="pl-pds">"</span>no<span class="pl-pds">"</span></span>?&gt;
&lt;<span class="pl-ent">svg</span> <span class="pl-e">xmlns</span>=<span class="pl-s"><span class="pl-pds">"</span>http://www.w3.org/2000/svg<span class="pl-pds">"</span></span> <span class="pl-e">viewBox</span>=<span class="pl-s"><span class="pl-pds">"</span>0 0 256 256<span class="pl-pds">"</span></span>&gt;
  &lt;<span class="pl-ent">path</span> <span class="pl-e">paint-order</span>=<span class="pl-s"><span class="pl-pds">"</span>stroke markers fill<span class="pl-pds">"</span></span> <span class="pl-e">stroke-width</span>=<span class="pl-s"><span class="pl-pds">"</span>8.95518494<span class="pl-pds">"</span></span> <span class="pl-e">stroke</span>=<span class="pl-s"><span class="pl-pds">"</span>currentColor<span class="pl-pds">"</span></span> <span class="pl-e">fill</span>=<span class="pl-s"><span class="pl-pds">"</span>none<span class="pl-pds">"</span></span> <span class="pl-e">d</span>=<span class="pl-s"><span class="pl-pds">"</span>M5.0000035 5H251v246H5.0000035z<span class="pl-pds">"</span></span> <span class="pl-e">stroke-miterlimit</span>=<span class="pl-s"><span class="pl-pds">"</span>8.60000038<span class="pl-pds">"</span></span>/&gt;
  &lt;path d="M116.13867 10.533203c-.0542 0-.25651.166168-.42187.349609-.05964.066644-.11189.143705-.1543.230469-.21203.433821-.20682 1.120943.01758 2.06836.08976.378966.21438.7986.375 1.261718.14684.431491.28847.924964.41406 1.425782.12559.500817.23543 1.009504.32031 1.470703.08489.461198.14325.874867.16797 1.1875.01236.156316.0161.287971.00977.386718-.00633.098748-.02138.165799-.04883.19336-.05987.059641-.12762.061085-.20508.001953s-.16506-.179309-.26367-.365234c-.09861-.185926-.20871-.437075-.33203-.757813-.12332-.320738-.26052-.712211-.41211-1.175781-.33073-.972323-.78738-2.091609-1.04492-2.476563-.31176-.449563-1.08714-1.261176-1.82813-1.960937-.55574-.524821-1.09333-.985595-1.40039-1.183594-.10235-.066-.17905-.103515-.22265-.103515-.04587 0-.09087.009806-.13477.029296-.04391.019491-.08666.048439-.12695.083985-.0806.071091-.15274.170449-.20899.285156-.05625.114707-.09654.244155-.11523.375-.0187.130845-.0145.263305.01758.382813.01377.054896.06149.147247.13867.265624.23152.355133.71379.951072 1.23633 1.515626l1.28515 1.375.4961 2.05664c.27471 1.137691.45941 2.109495.40429 2.183594-.05964.05964-.12654.076276-.20312.042969-.22976-.099924-.55929-.654241-1.13672-1.878907-.16514-.339545-.31411-.628817-.46094-.888672-.29365-.519709-.57924-.917713-.96484-1.345703-.1928-.213994-.41088-.435768-.66797-.683593-.69762-.678638-1.39373-1.228516-1.54102-1.228516-.11013 0-.20043.020889-.27343.060547-.07301.039658-.12871.098072-.16602.171875-.07462.147605-.07912.358274-.01953.609375.05958.251101.18288.543028.36523.853515.18236.310488.42312.63908.7168.964844.551.59234.85495 1.027929 1.11914 1.666016.08806.212696.17061.448108.25781.71875.11928.385857.23012.762231.31055 1.060547.08043.298316.13086.520103.13086.59375 0 .123799-.01777.201114-.05078.236328-.09904.105642-.33931-.181684-.6836-.841797-.0619-.117022-.14876-.248156-.2539-.384766-.10514-.136609-.22905-.279771-.36524-.425781-.81713-.876057-2.08323-1.828894-2.48242-1.759765-.03908.006777-.07525.022875-.10937.046874-.17061.119999-.27475.440382-.26758.8125.00287.148848.02311.305059.06445.460938.01378.050604.04742.113062.09766.181641.05023.068578.11643.143836.19336.220703.15385.153733.35272.31459.55468.443359.10088.059641.20015.128497.29688.207031.09673.078535.19009.16666.28125.261719.18232.190119.35249.410336.50391.652344.15141.242008.28356.506301.39257.78125.10902.274948.19488.560668.25.849609.0366.174404.09528.693543.16407 1.388672.06879.69513.1475 1.566211.2207 2.447266.10336 1.294134.17878 2.129569.29883 2.707031.20008.962436.52459 1.209227 1.3164 1.679687.4952.293685.4961.312383.4961 2.332032 0 1.10064-.05479 2.697504-.12891 3.523437l-.10937 1.523438h-.75391c-.422 0-1.30184.054808-1.98047.128906l-1.24805.109375v2.771484c0 1.523547.09146 4.09312.1836 5.707032.0913 1.615719.25499 4.716772.36523 6.882812.05513 1.115099.09528 1.936733.14258 2.613281.1419 2.029646.3493 2.746617 1.2168 6.105469.47712 1.830787.89276 3.380366 1.26758 4.71875.37481 1.338385.70795 2.464518 1.02343 3.445313.63098 1.961589 1.18637 3.343486 1.83789 4.683593.67909 1.412851 1.62382 3.150915 2.70899 5 1.08517 1.849086 2.31188 3.80828 3.55078 5.66211.00039.000581-.00039.001372 0 .001953.00167.001822.00223.004037.00391.005859.3961.591791.69518 1.040605.91797 1.388672.22394.34988.37193.60077.46484.802734.04645.100983.07958.188992.10156.271485.00014.000518-.00014.001435 0 .001953.02163.081724.03411.156712.03711.232422.00003.00062-.00002.001332 0 .001953.00579.152081-.02213.304661-.05859.505859-.00014.000766.00014.001187 0 .001954-.09244.441339-.58756 3.028182-1.10157 5.761718-1.1386 5.983944-1.55852 8.222764-2.01757 10.644534-.18344 1.01028-.51528 2.69827-.7168 3.76367a249.52378 249.52378 0 0 1-1.19141 5.68945c-.93618 4.29503-3.24856 14.79251-3.83593 17.50977l-.38672 1.8164.42187 1.19336c.15136.4315.37139.96813.62695 1.54493.00028.00062-.00027.00132 0 .00195.76665 1.73007 1.85111 3.80695 2.34571 4.39844.00022.00026-.00023.00168 0 .00195.2345.28939.52129.53681.74219.64258.07363.03525.14041.05468.19531.05468.30272 0 .68383-.13365 1.15429-.40429.23524-.13532.492-.30509.77344-.50977.28145-.20467.58746-.44359.91797-.71875l1.24609-1.04687.99219.60547c.55032.33073 1.08361.68021 1.17578.77148.02674.02821.03026.10799.01368.23633-.01651.12966-.05348.30642-.11133.52734-.11477.43827-.30737 1.04286-.56446 1.76758-.00025.00073.00026.00123 0 .00195-.47696 1.32122-.98667 2.82112-1.55078 4.56641-.00021.00067.00022.00128 0 .00195-.56419 1.74559-1.18345 3.73635-1.88086 6.03907-.26612.85349-.8915 2.73883-1.6875 5.08593-.00027.00081.00028.00114 0 .00196-.79589 2.34679-1.76276 5.15387-2.71679 7.85156-.00022.0006.00021.00135 0 .00195-1.09645 3.12359-1.96802 5.61656-2.66797 7.65039-.70012 2.03429-1.23038 3.61075-1.64453 4.90235-.82831 2.58318-1.19416 4.02861-1.54297 5.72656-.1744.84897-.35908 1.68124-.56641 2.55273-.20733.8715-.43752 1.78149-.70703 2.78516-.26951 1.00367-.5785 2.10021-.93945 3.3457-.0002.00068.00019.00128 0 .00196-.36084 1.24509-.77442 2.63808-1.25586 4.23437-.00021.00068.0002.00128 0 .00195-.54819 1.81633-1.06468 3.55832-1.54492 5.21875-.00017.00058.00016.00139 0 .00196-.4802 1.6603-.92654 3.23866-1.33594 4.73047-.00016.00057.00016.00138 0 .00195-.40935 1.49165-.78149 2.89646-1.11719 4.20703-.67189 2.623-1.19302 4.86943-1.552733 6.69141-.17982.91079-.320453 1.71455-.417969 2.40625-.000077.00054.000077.0014 0 .00195-.097471.69179-.151848 1.27065-.164062 1.73047-.01235.45997.018069.79999.09375 1.01562.032079.09195.014984.20529-.105469.40039-.000403.00066.000405.0013 0 .00196-.120567.19506-.344282.46967-.724609.88672-.000503.00055.000502.0014 0 .00195-.761806.83528-2.153996 2.23334-4.603516 4.67383-.000408.0004.000407.00154 0 .00195-2.298426 2.29843-4.359538 4.38958-5.308594 5.40039-.31683.33743-.510023.55471-.546875.61914-.173952.26612-.319467.72898-.404297 1.18555-.042415.22828-.07091.4549-.078125.65429-.007215.1994.006371.37073.042969.49024.000143.00047-.000144.00148 0 .00195.032305.09624.082607.18249.181641.27735.297101.28456 1.029345.64043 3.011718 1.52148.761548.3348 1.413101.59234 1.996094.7793.291497.09348.564822.16877.828125.22656.263303.05779.515645.09814.761719.12109.246074.02296.486754.02861.726562.01758.479618-.02205.958178-.11079 1.478516-.26367.260169-.07644.529612-.16752.816406-.27539.674724-.25463 1.330808-.69958 1.929688-1.2832.199536-.19438.392877-.40325.578121-.62696.37085-.44783.70995-.95038 1.00586-1.49414.14758-.27108.28364-.55223.40821-.84179.00023-.00056-.00024-.0014 0-.00196.12476-.29013.23721-.58748.33593-.89258.06868-.22026.13114-.39106.19532-.51757.06387-.12593.13145-.20737.20898-.25.039-.02124.08106-.03311.12695-.03516.13767-.00614.3118.0721.55274.2168.08494.05049.19215.09041.3164.12304.12426.03264.26443.05648.41602.07227.90952.09471 2.20489-.10461 2.58984-.49024.05739-.05738.11064-.13061.16211-.21874.15458-.2647.28221-.66414.37696-1.17774.06304-.3413.11152-.73236.14453-1.16797.00004-.00059-.00005-.00136 0-.00195.03296-.43588.05073-.91594.05078-1.4336v-.00195c0-.44505-.0008-.77799.00781-1.0332.00861-.25521.0261-.43176.06055-.5625.01722-.06537.03949-.1195.0664-.16602.02692-.04651.0589-.08526.09766-.12109.07752-.07166.18055-.13105.31836-.20898.09656-.05522.19743-.14068.30469-.25782.10693-.11664.21833-.26309.33594-.4414.11782-.17866.24056-.38822.36914-.62891.1283-.2401.26329-.5105.40234-.8125.83443-1.81223 1.86211-4.73844 3.08789-8.79297.40835-1.35067.83865-2.82647 1.29102-4.42773.00015-.00056-.00016-.00139 0-.00196.4524-1.60145.92712-3.32871 1.42382-5.18164.00016-.00057-.00015-.00138 0-.00195.49675-1.8531 1.01531-3.83205 1.55664-5.9375v-.00195l1.28516-4.95313v-.00195l8.55469-18.05859c4.69896-9.94824 8.56932-18.09717 8.60547-18.11524.0181-.0181.73606.09052 1.58007.25586.90817.17892 1.33177.29563 1.54102.4668.06975.05705.11441.11993.14648.19336.00021.00047-.0002.00148 0 .00195.03675.11114.13924.5681.26758 1.21875.0002.00099-.00019.00096 0 .00195.12849.65143.28492 1.4951.43164 2.375.31176 1.76211 1.92528 10.97567 3.61328 20.46485.83588 4.74459 1.5943 9.1718 2.14258 12.48242.00009.0005-.00008.00145 0 .00195.54806 3.30931.88672 5.5018.88672 5.77735v.00195c-.00907.7575-.07202 2.44755-.16601 4.57226-.00004.00091.00004.00105 0 .00196-.09403 2.12527-.21915 4.68421-.34766 7.17968-.00003.00068.00003.00128 0 .00196-.12851 2.4954-.26247 4.92681-.375 6.79492-.11261 1.8695-.2039 3.17482-.25 3.41797-.12786.74325-.15023 1.35395-.04687 1.91601.02583.14052.05965.27628.10156.41211.00018.00061-.00019.00135 0 .00196.04179.13524.09202.26911.15039.40234.00025.00057-.00025.00139 0 .00195.11714.2671.26941.53371.45703.8086.14232.211.25163.37673.33594.53906.08465.16278.14384.32072.1875.51172.04354.1905.06981.41348.08984.70898.02004.29551.0331.66328.04688 1.14063.01852.46763.03446.83013.05859 1.13281.00004.00052-.00004.00143 0 .00195.02411.30163.05711.5433.10742.76758.00013.00056-.00012.00139 0 .00195.0504.22416.11962.43057.2168.66407.00026.00062-.00026.00133 0 .00195.09736.23376.22385.49435.38867.82422.20197.40822.38056.73809.55664 1.00391.08804.1329.17457.24835.26367.35156.08941.10367.17986.19378.27539.27148.28558.2323.61024.35661 1.04102.42774.14359.02371.29898.04297.46875.05664l.97265.07422.07422.8789v.00196c.02299.2287.06787.46119.13282.69531.00017.00063-.00018.00132 0 .00195.13028.46895.34215.94303.61718 1.40234.00031.00051-.0003.00145 0 .00196.13748.22947.29127.45459.45899.67383.33632.43982.72777.85353 1.16211 1.2207.4339.36681.90998.68711 1.41015.93945.64249.32125 1.90759.73877 3.14649 1.07617.61945.1687 1.23358.31739 1.75781.42383.26211.05323.50122.09563.70899.125.20776.02938.38256.04688.51562.04688.22049 0 .50648-.04273.79102-.10938.28453-.06664.56902-.15855.78906-.25976.11013-.05038.21224-.10612.30859-.16797.09636-.06186.18696-.12988.26953-.20313.08258-.07325.15776-.15176.22657-.23633.06916-.085.13029-.17513.18554-.27148.22015-.38315.33008-.85471.33008-1.41406 0-.91797-.89658-2.94739-2.15625-5.08008-.25157-.42597-.51863-.85508-.79492-1.28125-.00029-.00045.00029-.0015 0-.00195-.55324-.85326-1.1469-1.69001-1.74805-2.44727-.69643-.88071-1.77919-2.27403-2.38476-3.08203v-.00195l-1.13868-1.48633.34961-.66016c.05049-.09409.10121-.22619.15235-.40234.05099-.17567.10333-.39647.15625-.66406.00009-.00046-.00009-.0015 0-.00196.10613-.53722.21629-1.26889.33789-2.23828.12159-.96938.25302-2.17546.40039-3.66015.14731-1.48416.31078-3.24794.49414-5.33008.00006-.00066-.00006-.0013 0-.00196.30272-3.44108.52422-6.78454.65039-9.82226.06312-1.51967.10262-2.96142.11719-4.30078.01458-1.33877.00362-2.57385-.03321-3.67969-.15116-4.68079-.17858-7.28475-.07421-10.08399.03473-.93222.08411-1.8864.14843-2.94531.00003-.00054-.00003-.00141 0-.00195.12829-2.27574.25532-5.92613.27344-8.11133v-.00195c.00452-.88024.0109-1.57054.02149-2.11719.00001-.00085-.00002-.0011 0-.00195.0318-1.64067.10784-1.97713.32812-2.21094.07608-.083.14259-.16078.19922-.25.11264-.17693.18662-.3954.21875-.77148.00004-.00053-.00005-.00143 0-.00196.08005-.9436-.10242-2.87995-.58399-7.63867-.00011-.00111.00011-.00085 0-.00195-.082-.82616-.09084-1.07316.0254-1.03711.03874.01201.09124.05693.16015.12109.00009-.00095-.00009-.001 0-.00195.78844-8.49408.00527-4.2657.78906-8.49609l.69727-.10938v-.00195l1.44922-4.27539 4.24023-12.62696v-.00195l2.78907-8.34961.1289-4.2207c.00003-.00102-.00003-.00094 0-.00196.16489-5.95491.25306-9.27587.27149-11.40039 0-.00084-.00001-.00111 0-.00195.00919-1.06139.00059-1.82411-.02344-2.4668-.00003-.00071.00002-.00124 0-.00195-.02408-.643-.06402-1.16519-.11914-1.74805-.24331-2.54647-.47243-4.85663-.6836-6.91015-.21109-2.05279-.40377-3.849615-.57812-5.369143-.00009-.000788.00009-.001165 0-.001953-.34864-3.038255-.62096-4.968919-.79492-5.63086-.00012-.000447.00011-.001505 0-.001953-.03671-.144583-.12094-.311916-.25196-.503906-.13101-.19199-.30852-.407442-.5332-.646484-.22468-.239043-.49479-.501367-.8125-.78711-.31771-.285743-.68366-.595644-1.09375-.927734-.41009-.33209-.86536-.686369-1.36719-1.064453-.50182-.378084-1.04966-.7794-1.64257-1.203125-1.18584-.847451-2.55325-1.786556-4.09961-2.814453-1.0279-.683609-1.86887-1.230157-2.56836-1.664063-1.39899-.867811-2.23277-1.282308-2.86524-1.429687-.31623-.07369-.58041-.079793-.84179-.042969l-.8086.109375-.5332-1.210938c-.1238-.275612-.28881-.697168-.4668-1.179687-.35598-.965038-.76391-2.175886-.99609-2.957031-.11581-.389633-.18716-.671254-.1875-.763672 0-.09127.1276-.110713.29297-.054688.05964.022593.10706.035255.14257.035156.10654-.000297.10947-.112953.04102-.402343a16.852999 16.852999 0 0 1 0-.001953 16.852999 16.852999 0 0 1-.23828-1.025391v-.001953l-.11133-.53125.7168.294922c.92239.41274 1.82391.680484 2.48047.765625.21885.02838.4103.037218.5664.023437l.60547-.05664-1.00976-.679688c-.68859-.467637-1.37674-1.161593-1.67774-1.658203-.09983-.16471-.15763-.308489-.1582-.414063 0-.022817.0138-.032257.03906-.027343.07578.01474.2563.146687.47656.339843.46764.454082 1.22339.845532 2.27735 1.183594.35132.112688.73681.21933 1.15429.320313.71569.165367 1.39422.34967 1.52344.386719.05541.018319.10898.016695.15039 0 .04123-.016041.06836-.047666.06836-.09375 0-.045245-.04189-.100145-.10742-.150391-.06667-.051114-.1562-.097203-.25781-.125-.07568-.02293-.17122-.080848-.28125-.167969-.11004-.087121-.23522-.204315-.36914-.341797-.26785-.274962-.57248-.635872-.87305-1.029297-.30096-.393923-.59791-.819008-.84766-1.220703-.12477-.200623-.23767-.394338-.33398-.576172s-.17504-.350785-.23242-.5c-.0549-.158251-.0762-.251922-.01758-.263671.09769-.019583.41704.188869 1.17383.705078.71569.495198 1.3408.863222 1.37695.826172.00014-.000137-.00013-.00181 0-.001954.01722-.019027-.0154-.104833-.08398-.228515-.06868-.124025-.17247-.283852-.30079-.449219-.15101-.201394-.2868-.390821-.40429-.576172-.00032-.0005.00031-.001452 0-.001953-.23504-.370979-.40534-.729414-.52149-1.152344-.00015-.000575.00016-.001378 0-.001953-.05792-.211289-.10265-.43817-.13476-.691406-.00008-.000581.00007-.001372 0-.001953-.03206-.253485-.05175-.532842-.06055-.847657-.00002-.000579.00002-.001373 0-.001953-.00875-.315119-.0061-.66663.00586-1.0625.00002-.000514-.00002-.001438 0-.001953.02403-.793528.08601-1.767572.17773-3.001953.14695-2.066338.20226-3.391782.13086-4.355469-.01773-.240174-.0422-.457261-.07617-.658203-.00011-.000666.00011-.001287 0-.001953-.06811-.402164-.1709-.737607-.31054-1.052734-.00024-.000524.00023-.00143 0-.001953-.07001-.157803-.15066-.309271-.24024-.462891-.18344-.330734-.34766-.661179-.34766-.734375 0-.025302.0228-.023765.06446 0 .12497.071294.41803.343243.76562.701172.46346.477238 1.0228 1.106642 1.40821 1.611328.20196.266124.39582.499227.54492.662109.14951.163419.25364.254886.28125.236328.05065-.054942-.04252-.424512-.22461-.972656-.36344-1.094371-1.08192-2.900303-1.72071-4.330078-.00029-.000653.0003-.0013 0-.001953-.31948-.71501-.61896-1.33446-.84374-1.724609-.12855-.220264-.29235-.436505-.49024-.648438-.59365-.6358-1.49222-1.229303-2.64844-1.738281-.5693-.248051-1.02844-.384242-1.45508-.414063-.21331-.01491-.41799-.003644-.625.035157-.207.0388-.41645.103366-.63671.195312-.15137.064159-.26611.113252-.36329.136719-.09717.023466-.17637.022733-.25781-.011719-.08144-.034451-.16536-.103295-.26953-.212891-.10392-.109327-.22976-.259712-.39453-.460937-.00035-.000409.00035-.001544 0-.001953-.14197-.164506-.26755-.299861-.39258-.416016-.25099-.233176-.49761-.385747-.86328-.527344-.18261-.07071-.39548-.139243-.65234-.21289-.52773-.155879-1.02375-.283896-1.48633-.384766-.92517-.201739-1.71484-.293689-2.3418-.27539-.31348.009149-.58688.045216-.8164.109375l-.80274.220703-.0039.001953.67968.126953c.32079.055122.86096.30737 1.32227.578125.34598.203066.64853.418062.77734.566406.04196.048671.06641.091247.06641.123047 0 .05422-1.04656.10888-2.34961.126953-1.28499 0-3.32141.146638-4.5332.330078-1.88613.289393-3.80441.331516-5.13282.132813-.2214-.033117-.42547-.072725-.61133-.119141-.18585-.046416-.35346-.100515-.49804-.160156l-.73242-.292969.60546.513672c.33074.293685 1.24683.882191 2.05469 1.322266.39444.229526.74797.439405.99805.597656.25008.158251.39743.264679.37891.283203-.05512.055122-.37996-.023063-.95118-.222656-.57121-.199593-1.38884-.521634-2.42578-.953125-.78481-.34429-1.4875-.605461-1.82031-.691406-.11094-.028649-.18092-.037218-.19922-.023438-.01377.013555.01475.065344.07617.148438.00063.000852-.00063.001094 0 .001953.06145.083015.15612.19517.27735.330078.00042.000468-.00042.001484 0 .001953.24327.27066.59423.62791.98828 1.003906.39444.385405.74283.738395.98828 1 .2443.260372.38367.429363.36719.449219-.09664.107933-1.81725-.551185-3.02735-1.173828-.64159-.311757-1.15625-.514106-1.15625-.458985 0 .091834.03324.199678.09571.320313.06246.120635.15392.252835.26953.394531.00039.000477-.00039.001476 0 .001953.11544.141403.25501.290662.41406.445313.1597.155358.33883.31559.5332.476562.19392.160595.40201.322036.6211.480469.43818.316866.91745.621041 1.40039.882813.24147.130885.48398.251921.72265.357422.19248.087201.33825.153702.44141.207031.15474.079994.21402.129986.19336.175781-.00689.015265-.02277.029722-.04688.044922-.0482.030399-.12999.062173-.24023.103516-.2799.1055-.66141.221758-1.09961.33789-.4382.116133-.93153.233157-1.43164.339844-1.00022.213373-2.02961.386284-2.69922.441406l-.10156.007813c-.63635.031719-1.02903.049951-1.17578.089843l-.18946.013672.19532.103516c.12489.106447.51802.277939 1.17968.630859.61494.325765 1.12971.590439 1.57422.804688.44451.214249.81969.377217 1.15235.5.66531.245566 1.16507.328125 1.73437.328125.28465 0 .54611.009769.73633.023437.18905.013585.30518.032374.30664.050781-.00133.019939-.16365.276294-.36523.550782-.06653.089461-.12953.196003-.19141.318359-.00028.000549.00028.001403 0 .001953-.06161.121983-.12203.258044-.17773.40625-.00023.000598.00022.001355 0 .001953-.11161.297243-.21085.639826-.29102 1.003907-.00014.000653.00014.001299 0 .001953-.08011.364189-.14132.749253-.17969 1.128906-.00006.000641.00007.001312 0 .001953-.03828.379601-.05477.753978-.04101 1.097656.00002.000611-.00003.001343 0 .001954l.05664 1.173828.88086-1.009766c.23818-.275173.45333-.512805.60937-.675781.15611-.162995.25195-.250218.25195-.222657-.00047.056535-.20265.734012-.45898 1.503907-.16988.518467-.29451.911553-.37109 1.201172-.00012.000429.00011.001523 0 .001953-.07613.28833-.10479.473198-.07617.576172.00012.000464-.00013.001492 0 .001953.01449.050576.04351.080907.08593.09375.12822.040341.38844-.080972.80274-.294922.64272-.344515.95445-.452977 1.03125-.310547.01536.028486.02225.066635.01953.115234-.00545.097199-.04656.235141-.11524.414063-.05049.137693-.09168.275272-.12304.417969-.00014.000611.00013.001342 0 .001953-.03114.142121-.05182.288579-.0625.443359-.01087.156045-.01145.319389 0 .496094.03418.527844.17139 1.163818.43164 2.015625.00022.00072-.00022.001233 0 .001953.17344.567544.40076 1.23088.68945 2.019531.68813 1.908501 1.11197 3.110154 1.34375 3.853516.23179.743362.27286 1.027915.19922 1.101562-.0542.05422-.82597-.128684-1.70703-.404297-.23856-.077939-.45545-.151805-.65625-.230468-1.4056-.550642-2.08304-1.304898-4.8125-4.853516-.89484-1.160959-1.58778-2.065623-2.125-2.794922-.53722-.729299-.9188-1.282537-1.19531-1.740234-.13826-.228848-.25055-.434041-.3418-.625-.18251-.381918-.28243-.708191-.34961-1.058594-.03359-.175201-.0591-.355401-.08203-.552734-.11928-.936177-.34439-3.272216-.58985-6.052735-.24545-2.780519-.51092-6.006296-.71289-8.722656-.18344-2.399858-.31909-4.185594-.42578-5.519531-.10668-1.333937-.185-2.217054-.2539-2.8125-.03446-.297723-.0673-.522772-.09961-.697266-.03232-.174493-.06457-.298432-.09961-.390625-.07009-.184386-.14952-.244946-.25977-.345703-.34791-.311758-.3666-.457775-.23828-3.541016l.14649-3.21289 1.70703-1.796875c1.55969-1.652769 1.83444-2.038544 2.88086-4.222656.31198-.642493.61697-1.213222.91406-1.714844.59418-1.003245 1.16067-1.72833 1.70898-2.185547.13708-.114304.27328-.211882.40821-.292969.13492-.081086.26928-.145127.40234-.193359.52321-.178922.65361-.307083.36914-.59961-.09482-.097508-.23587-.213144-.42383-.355468-.29617-.227041-.64177-.373432-1.0039-.439453-.24143-.044014-.49116-.051659-.73829-.023438-.24713.028221-.49066.092367-.7246.193359-.11698.050497-.23167.110898-.3418.179688-.33073.201514-.99212.9338-1.45117 1.650391-.19722.293685-.37426.543803-.53711.751953-.16286.208149-.31153.375169-.44922.505859-.13769.13069-.26498.22385-.38672.285156-.12174.061307-.23658.089844-.35156.089844-.0732 0-.16782-.135294-.26953-.363281-.10172-.227987-.21204-.548142-.31641-.914063-.10437-.36592-.20205-.777607-.2832-1.191406-.08116-.413799-.14566-.829548-.17774-1.201172-.03208-.417484-.08034-.857462-.14258-1.308593-.1865-1.353394-.49913-2.811674-.88476-4.105469-.18344-.642492-.58201-1.629146-.96289-2.455078-.19045-.412967-.37726-.787072-.5293-1.056641-.07602-.134784-.14182-.243081-.19727-.318359-.05544-.075278-.09939-.117188-.12695-.117188z"/&gt;
&lt;/<span class="pl-ent">svg</span>&gt;</pre>
</details> 

I have an SVG that should look like this:
![logo-square-border-black-transparent](https://user-images.githubusercontent.com/28905212/55195727-648e1e80-51a5-11e9-9222-7e0ab55aa40d.png)
and renders fine in inkscape:
![image](https://user-images.githubusercontent.com/28905212/55195810-91423600-51a5-11e9-9083-838c60e3d3ca.png)
However, renders wrong in RFG.
![image](https://user-images.githubusercontent.com/28905212/55195890-cd759680-51a5-11e9-8d9d-ce6bd1bd568b.png)

This consistently happens with all versions of my SVG, including the original full-width logo.
![image](https://user-images.githubusercontent.com/28905212/55196162-77edb980-51a6-11e9-91cd-63256d9b1b6d.png)

**Comment by JadedBlueEyes** [comment]
This might be caused by a outdated version of inkscape?
May I add, I designed this logo and all variants in inkscape!

**Comment by phbernard** [comment]
Hi @derpmarine168,

As you may have noticed from #396, the issue should be fixed (it is with your image).

I leave the issue open for now and will close it by the end of the week if everything goes well.

**Comment by JadedBlueEyes** [comment]
@phbernard It renders correctly now! Thanks for your time!

**Comment by phbernard** [comment]
Great! Thanks!!!
