### ISSUE TITLE
apple-touch-icon-precomposed.png is ill-formed is always reported by checker ...

### ISSUE THREAD

**Issue by bdcoder2** [RealFaviconGenerator/realfavicongenerator#418]
The RealFavicon checker page at:
[https://realfavicongenerator.net/favicon_checker](https://realfavicongenerator.net/favicon_checker)

Always reports the following:

> https://.../apple-touch-icon-precomposed.png is ill-formed

Please provide a link to some utility or tool that can create a properly formed "apple-touch-icon-precomposed.png" file -- no matter what I have tried, this message is always reported.

**Comment by tigt** [comment]
Can you provide the URL you’re checking?

**Comment by bdcoder2** [comment]
@tigt - Apologies - the problem was the file was missing...

The checker was requesting:
`/apple-touch-icon-precomposed.png`

The file on the web site was:
`/apple-icon-precomposed.png`

Hence, the website was returning a 404 error (file not found) -- but the checker was displaying the message:

> https://.../apple-touch-icon-precomposed.png is ill-formed

Renaming the file solved the problem.

**HOWEVER:**
It might be better to report the actual HTTP status code, which would have provided a much more useful error message, because the "real" issue was the image file was missing NOT that it was "ill-formed".

Thanks in advance.

**Comment by uhlhosting** [comment]
This issue is still not solved...

**Comment by phbernard** [comment]
The checker is supposed to support 404 errors and doesn't report them as ill-formed images. However, this can happen when the tested server returns a "not found" page with a 200 status. I added a hint in the report so users have a clue about what might going on.

Maybe this is what happened to you?
