### ISSUE TITLE
Generated color for favicon.ico is wrong

### ISSUE THREAD

**Issue by thomasaull** [RealFaviconGenerator/realfavicongenerator#429]
To reproduct:
1. Uplod the attached image (it's white so just right-click on the empty space beneath and save as… or click here: https://user-images.githubusercontent.com/227756/76624994-a17a2f00-6536-11ea-9042-b3ad6090920f.png
2. Klick "Add margins and a plain background" in the section "Favicon for Desktop Browsers and Google Result Pages". Use the color `#0078C8`
3. Generate and download the package

Result: The color is way off:

![grafik](https://user-images.githubusercontent.com/227756/76625234-18172c80-6537-11ea-869f-80c343e4dd29.png)

![favicon](https://user-images.githubusercontent.com/227756/76624994-a17a2f00-6536-11ea-9042-b3ad6090920f.png)

**Comment by phbernard** [comment]
Thank you for reporting!

That was due to a color space issue. Different softwares could actually render different colors for the same image:

![image](https://user-images.githubusercontent.com/423852/76628877-bdcd9a00-653d-11ea-8514-cbdaa911b6fd.png)

Fixed a minute ago.

**Comment by thomasaull** [comment]
Had somethink like this in mind, but opening the image in several programs always showed the same color for me. Anyway, thanks for fixing it that fast 👍
