### ISSUE TITLE
Social generator not working

### ISSUE THREAD

**Issue by PellegattaSimone** [RealFaviconGenerator/realfavicongenerator#436]
Even if I fill every field, the website stucks on a page like this:

![image](https://user-images.githubusercontent.com/43515100/80758931-bd618080-8b36-11ea-9a3b-ae2d3d3160f6.png)
 I tried to clear my cache, use incognito mode or even change device but nothing changes... Please solve this.

Meanwhile can I find somewhere a list of the tags you use (as you do for favicons)?

**Comment by JavierCanon** [comment]
![Annotation 2020-05-03 145653](https://user-images.githubusercontent.com/6878607/80924416-5fa78100-8d4e-11ea-976b-08afc0735560.png)

Same here...

**Comment by epexa** [comment]
#439 
#442

**Comment by phbernard** [comment]
Social generator is finally back. Alert system setup so I'm warned immediately when it happens again. Sorry for the long wait :(
