### ISSUE TITLE
Typo on windows 8

### ISSUE THREAD

**Issue by wormeyman** [RealFaviconGenerator/realfavicongenerator#44]
Use a dedicated picture. This is a picture you have designed specifically for **Windowd** 8 tiles.

Should be:

Use a dedicated picture. This is a picture you have designed specifically for **Windows** 8 tiles.

**Comment by phbernard** [comment]
Fixed and deployed a minute ago.

Thank for reporting. Dozens of people must have notice this, but you're the one who took time to warn me.
