### ISSUE TITLE
Social generator 500 server error

### ISSUE THREAD

**Issue by epexa** [RealFaviconGenerator/realfavicongenerator#442]
Social generator give an error "500 Internal Server Error"

Example URL:
https://realfavicongenerator.net/social/generate_social_package?file_id=p1ecohbl0t1ed71resuf51msmkfm3

Example screenshot:
![image](https://user-images.githubusercontent.com/2198826/86985243-65dd3200-c1c3-11ea-82e0-f134e6718b6a.png)

**Comment by epexa** [comment]
#436
#439

**Comment by phbernard** [comment]
Social generator is finally back. Alert system setup so I'm warned immediately when it happens again.
