### ISSUE TITLE
Gulp 'generate-favicon' doesn't adhere to 'desktopBrowser' settings

### ISSUE THREAD

**Issue by bskibinski** [RealFaviconGenerator/realfavicongenerator#449]
The icons generated through the gulp task: favicon.icon file and favicon-16/32.png files always generate with a white background, and no rounding of the corners, or scaling of the image.

with the following settings:
`
      desktopBrowser: {
        design: 'background',
        backgroundColor: '#000000',
        backgroundRadius: 0.45,
        imageScale: 0.9
      },
`
it gets a white background-color, no rounding, and no scaling.

Icons generated through the website (HTML5 tab) are done correctly.

I'm using the latest gulp-real-favicon: 0.3.2, package.

**Comment by craighutch** [comment]
I'm experiencing the exact same issue, but I'm using `cli-real-favicon` and similar settings in my `faviconDescription.json` file:
```json
"desktopBrowser": {
  "design": "background",
  "backgroundColor": "#ffffff",
  "backgroundRadius": 1,
  "imageScale": 1
}
```
