### ISSUE TITLE
Prevent user from using a transparent picture for iOS

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#46]
Currently, when a user uploads a transparent picture, the default choice is "Use the original favicon as is. The Web Clip will be transparent.". In fact, this is a false promise, the icon won't be transparent once added to the home screen, see http://realfavicongenerator.net/blog/apple-touch-icon-turns-black/.

As a consequence, this option should be removed. The default choice should be "Add a solid, plain background to fill the transparent regions".

**Comment by rileypaulsen** [comment]
The quick solution here would to change the wording of the option to say: "Use the original favicon as is. The Web Clip will be transparent on Android, but will have a black background auto-generated on iOS."

**Comment by phbernard** [comment]
... and apply a black background to the preview so the user knows what to expect. Yes, I like this one. Thank you for the suggestion.

**Comment by phbernard** [comment]
Fixed and deployed a minute ago.
