### ISSUE TITLE
shortcut icon not visible in android default browser for samsung galaxy

### ISSUE THREAD

**Issue by shwetachalke** [RealFaviconGenerator/realfavicongenerator#47]
Hi Friends, 
I am facing a issue for shortcut icon in default browser of android Samsung galaxy phone.
i have place the same code generated through real favicon generator. but not getting the icon while add to home screen in android. Can someone please help me with this.

regards, 
Shweta Chalke

**Comment by phbernard** [comment]
Hi Shweta,

Thank you for reporting.

I've just made the test on a Samsung Galaxy S5. You are right, the default browser uses a default icon. I don't think there is any workaround. Even bookmarking Samsung.com gives the same result. The Galaxy S (yep, S1) already had a similar issue. Yet, Chrome on an S5 is correct: it uses the 152x152 touch icon.

I have just updated the compatibility page to reflect this: http://realfavicongenerator.net/favicon_compatibility

Regards,
Philippe
