### ISSUE TITLE
Checker reporting errors, not any of the cases mentioned in FAQ

### ISSUE THREAD

**Issue by shortstrokes** [RealFaviconGenerator/realfavicongenerator#48]
As requested in the FAQ, I'm reporting this issue. I generated my icons, uploaded them to the root of my website, added the code to the <head>.  Then tried the checker. My website passes most tests but a few errors are reported. 
FAQ mentions two possible causes. 
1) images not placed in root. Mine are.
2) starting image not big enough. Mine was a 1,983 x 1,983 square png.
For investigation purposes my site is http://kenblackman.com, and I've attached the original image used for icon generation.
Thanks for the help.
--Ken
![logo](https://cloud.githubusercontent.com/assets/789887/3283930/46fa5f18-f521-11e3-9e95-b5e777419f6d.png)

**Comment by phbernard** [comment]
Hi Ken,

I've just run the checker: everything is green (http://realfavicongenerator.net/favicon_checker?site=kenblackman.com). Strange. Did you change something? Maybe there was a temporary issue I was not aware of. Could you run it again?

Regards,
Philippe

**Comment by shortstrokes** [comment]
You're right, I ran it again and everything checks out, no errors. Maybe
some kind of caching issue. Anyways, glad it's all cleared up.
--Ken

**Comment by phbernard** [comment]
Great! I don't know what went wrong, but if it works...

Thank you for the feedback.

Regards,
Philippe
