### ISSUE TITLE
Option to let the user set the default home screen icon title

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#49]
When adding a page to the home screen, the browser takes the page's title as the default caption. In some cases, the author of the web site may want to override this default value.

The feature depends on the platform:
- iOS: <meta name="apple-mobile-web-app-title" content="App name">
- Windows 8: <meta name="application-name" content="App name">
- Android: Not possible (https://developer.chrome.com/multidevice/android/installtohomescreen)

RealFaviconGenerator should offer this feature as an option.

This issue was first reported in the WordPress support section: http://wordpress.org/support/topic/how-to-customize-text-under-icon

**Comment by phbernard** [comment]
Implemented and deployed a few hours ago.

**Comment by Nerdsusan** [comment]
thanks, should i see a request to update from my dashboard, or download and install again?

**Comment by phbernard** [comment]
Yes, go to Appearance > Favicon and generate the favicon again. Once on RealFaviconGenerator, you will have the opportunity to set the app name.
