### ISSUE TITLE
Uploaded SVG image does not respect fill

### ISSUE THREAD

**Issue by toolforger** [RealFaviconGenerator/realfavicongenerator#499]
I have an SVG image with a filled path, but the preview image complaining about the image's non-squareness still displays the transparency checkerboard. (The image is intentionally non-square, this aspect is being handled fine.)

The affected SVG is attached.
![toolforger-logo](https://github.com/user-attachments/assets/91d3bc05-7ebd-4fe2-8c34-07615e7e6f98)

**Comment by phbernard** [comment]
For the record, here is your image, as shown by Chrome when accessed directly:

![image](https://github.com/user-attachments/assets/f4c3863a-52d8-4033-9ee8-ebbee411f56b)

And this is how Chrome shows your issue above:

![image](https://github.com/user-attachments/assets/cfe420e5-ea12-4c9c-abf4-092bc5845fba)

I reproduce the issue with the current version of RealFaviconGenerator. However, I more interested in the next version, expected to be released during August (currently hosted at https://next.realfavicongenerator.net/). Here, your icon is just transparent:

![image](https://github.com/user-attachments/assets/6cefc768-9926-468c-b7ba-020a7fe0ff19)

**Comment by toolforger** [comment]
Hm. Weird. Opening the SVG directly in Firefox also shows the anvil with a black interior, but it should be white.

**Comment by toolforger** [comment]
Actually Firefox is inconsistent.
Sometimes it shows just a white page, sometimes the interior of the anvil is white, sometimes it is black.

**Comment by toolforger** [comment]
Here's a slightly updated SVG, just for the record.
It shows okay in the preview when I tried it.

![toolforger-logo](https://github.com/user-attachments/assets/dde9004f-2ad7-45d5-af1d-55bac169cc9c)

It shows okay in the GitHub issue (white fill in the anvil).
Clicking on the image in the Github issue gives me the file but with a black anvil.
Loading the image directly from disk into Firefox gives me the white fill though.

("Okay" means "as I intended it to be displayed", not that this SVG is well-formed or error-free.)

**Comment by toolforger** [comment]
Retrying with the `xmlns="http://www.w3.org/2000/svg"` right after `<svg`.

![toolforger-logo](https://github.com/user-attachments/assets/33fe4be0-c28a-456c-8956-33b799a46c4a)

**Comment by toolforger** [comment]
Here's the same SVG validated through https://validator.w3.org/check:

![toolforger-logo](https://github.com/user-attachments/assets/433f7372-cbac-44a0-944a-234a009fc62c)

This is getting even weirder.
Display is correct in the issue.
Display as an individual file is incorrect, but not just black interior, but also smaller. Except there is nothing in the SVG that would make it merely smaller.
Display when downloading the very same file and opening in the browser directly is correct again.

**Comment by toolforger** [comment]
I just shoved the SVG through Inkscape, which is as official as you can get.
Effects:

* There is a lot of useless cruft in the file.
* It still displays correctly inside the GitHub issue (see below).
* Clicking the file as displayed in the GitHub issue gives an anvil filled in black.
* Opening the file directly gives a correct display.

Which pretty much duplicates the results from all previous attempts, but since the issue is reproducible without any involvement of RealFaviconGenerator, I conclude that this is an issue with SVG support in browsers, so I'm taking the issue there and closing it here.

![toolforger-logo](https://github.com/user-attachments/assets/cb0b0a82-a11f-42e9-968f-c20a82ddec92)


... ooohh.
Console shows `Content-Security-Policy: Couldn’t process unknown directive ‘noscript-marker’`; switching off NoScript for GitHub makes that vanish.
There's also multiple messages of `Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). Source: fill:#ffffff;fill-opacity:1;stroke:#ffff…`, which is just hilarious since `style` tags aren't external resources; this is a true browser problem, or maybe GitHub setting a response header of `content-security-policy: default-src 'none'; script-src 'none'; img-src 'self'; media-src 'self'; sandbox;` is incorrect.

Since the issue happens without any involvement of RealFaviconGenerator, I am closing it.
