### ISSUE TITLE
Check for website results in: Oops! There was a problem :(

### ISSUE THREAD

**Issue by nupis-ChristophS** [RealFaviconGenerator/realfavicongenerator#502]
If we check our website **https://plattform-dev.nupis-rz.de/nupis/qs-test/web/** with the Favicon Checker, we get the following message in the browser: 

_Oops! There was a problem :(

Maybe this is just a temporary issue, or maybe we just can't process this site. Anyway we have been notified about this issue and we are going to investigate it._

Unfortunately, there is no further information on how we can fix the problem. Can someone help us or give us a hint?

**Comment by phbernard** [comment]
It works now!
