### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by joaowall88** [RealFaviconGenerator/realfavicongenerator#504]
I can no longer upload icons in svg format in the new version of the site. When I select an image, nothing happens.

**Comment by phbernard** [comment]
Which browser do you use? Could you post the content of the SVG content?

**Comment by joaowall88** [comment]
I use Google Chrome, but I tested it on Edge and Firefox and it didn't work either.

I did some tests again and apparently the problem occurs when the svg has a special character in one of its attributes.

Example: `<rect data-name="Retângulo"/>`

I removed the special character and it worked perfectly.

**Comment by phbernard** [comment]
Thank you for investigating! That's right, there was an issue with UTF-8 when extracting the color palette of the input image.
