### ISSUE TITLE
Include the HTML snippet in the downloadable archive

### ISSUE THREAD

**Issue by stof** [RealFaviconGenerator/realfavicongenerator#51]
it would be great if the archive could include the HTML snippet as well. This would make things easier when keeping the archive around as the page does not stay around

**Comment by phbernard** [comment]
Good idea! Thank you for the suggestion.

Currently, the whole archive must be extracted somewhere in the web site (typically in the root directory). Easy. If the archive also contains a README file, the procedure is a bit more complex. Therefore, I plan to make this feature an option: "Do you want the package to contain the install procedure?" (well something like this).

**Comment by phbernard** [comment]
See #73
