### ISSUE TITLE
Bug when putting favicon in the root instead of subfolder

### ISSUE THREAD

**Issue by bckasper3** [RealFaviconGenerator/realfavicongenerator#510]
Hello,
Thanks for the website! Please ignore me if I am ignorant here, but I had an issue with the site.
The autogenerated code didn't automatically work for me.
Example:
href="/favicon.ico"
needed to be
href="favicon.ico" 
I think this is because I put the favicon at the root instead of a sub-folder?
Thanks again,
Ben

**Comment by phbernard** [comment]
Hi Ben,

This is normal. `"/favicon.ico"` is an absolute path which targets the file `favicon.ico` located in the root folder. Whereas just `"favicon.ico"` is a relative path and points to the file `favicon.ico` located in the same folder as the resource using this URL. So the page `https://example.com/some/page.html` would try to load `https://example.com/some/favicon.ico` (note the extra `some/` subpath).
