### ISSUE TITLE
generated .ico file is corrupted

### ISSUE THREAD

**Issue by CitrineWeb** [RealFaviconGenerator/realfavicongenerator#511]
Hi there, 
it seems the generated .ico file is corrupted and cannot be read by any program.
just reporting the issue.
Thanks for your good website.

**Comment by phbernard** [comment]
Thank Michael you for reporting!

This is issue #503 . Actually the .ico can be opened by some browsers, such as Chrome, but not by Firefox. Well it's safe to say it's corrupted in a way or another. The fix should be ready in a few days.
