### ISSUE TITLE
Format error decoding Ico: Entry(48, 48) and BMP(16, 16) dimensions do not match! for the favicon.ico 

### ISSUE THREAD

**Issue by haroldjeshua** [RealFaviconGenerator/realfavicongenerator#517]
I have used this for generating my brand logos into favicon for the last ~6 years, my most previous use was maybe a few weeks ago and it worked fine. But just now, I got this error now for the `favicon.ico` that I generated from the downloaded package zip. I only use `favicon.ico` because it's short and concise and it works just fine.

I use next.js and got this error when I placed the favicon.ico to app folder.

```
 ⨯ ./app/favicon.ico
Processing image failed
unable to decode image data

Caused by:
- Format error decoding Ico: Entry(48, 48) and BMP(16, 16) dimensions do not match!
- Entry(48, 48) and BMP(16, 16) dimensions do not match!
```

![image](https://github.com/user-attachments/assets/1c8cc864-afa0-4ab1-b5c0-36a27eec7794)

Thanks!

**Comment by phbernard** [comment]
Thank you for reporting. Probably related with #503. Yet it's interesting to know that the error can be detected by Next, which is what I'm using too.

**Comment by phbernard** [comment]
For the record, this message is from Next 15. Prior versions apparently don't perform this check.

**Comment by phbernard** [comment]
Fixed in `@realfavicongenerator/generate-favicon`.
