### ISSUE TITLE
SVG doesn't work anymore

### ISSUE THREAD

**Issue by jcubic** [RealFaviconGenerator/realfavicongenerator#518]
I always use this project to generate favicons, but now it doesn't work. I've tried two SVG files with 250x250px and one 32x32px both looks like this:

![Przechwycenie obrazu ekranu_2024-11-28_20-00-53](https://github.com/user-attachments/assets/28ed14bf-3691-4d9b-ae74-2eaa5eeccc5d)

This is the icon:

![favicon](https://github.com/user-attachments/assets/0acfb839-f233-41ab-ad75-3977aef5e109)

**Comment by phbernard** [comment]
I clicked your icon above, expecting to right-click it to view the source. Here is what Chrome shows:

![image](https://github.com/user-attachments/assets/dafdf2e7-3004-4621-a3e9-bce8200c5eab)

I don't know what's wrong, I didn't inspect the source any further, but at least it seems that your icon has something unusual. I can successfully view it with Edge and Firefox. Can you reproduce the issue in Chrome or another viewer?

**Comment by jcubic** [comment]
I can open that SVG in Firefox, Chrome, Brave and standard Linux image browser. It was created in Inkscape. I don't see anything wrong with this file. The only thing is that the width and height of the svg use size in `mm` not pixels.

**Comment by jcubic** [comment]
I've also asked on an [Inkscape forum](https://inkscape.org/forums/other/recent-changes-of-svg-output/), maybe something is off with SVG output.

**Comment by phbernard** [comment]
In the screenshot below, the left (working) icon is what I get when I save the icon to a local file and open if with Firefox. The right (full block) is what I get when I click your icon in your initial post above, still in Firefox. I'm totally clueless here 🥲

![image](https://github.com/user-attachments/assets/0222e24d-4148-4d09-ab0b-0b48b045cda4)

**Comment by jcubic** [comment]
That's really weird, when I click the icon I also have the same output in Brave.
But the issue with real favicon generator is the input image s cropped, not full black. If you open my screenshot, a bit of yellow is visible in dark theme browser. That's why I thought that the issue may be with mm size instead of pixels. Or maybe something with viewbox.

**Comment by jcubic** [comment]
I just checked some old SVG file that I used, so maybe the generator was never working with SVG files (or at least those generated with Inkscape).

**Comment by Nalci** [comment]
Hello, 

I copy paste your svg code into Affinity Designer 2 and I can see that your letter is totally in black and therefore not visible somehow

![grafik](https://github.com/user-attachments/assets/92d078a1-177d-4641-a1ba-b0d7b3cb3d17)
![grafik](https://github.com/user-attachments/assets/b8deef72-a677-4968-af5d-31a4640d0710)

**Comment by jcubic** [comment]
I see the same when I click and open the file I upload in Chrome. But when I open it directly, it works fine. This is really odd.

I'm closing since this is probably not related to RealFaviconGenerator.
