### ISSUE TITLE
Marilyn's Treats

### ISSUE THREAD

**Issue by marilyn1998** [RealFaviconGenerator/realfavicongenerator#54]
Every day I create a favicon(exact same one) and says it is perfect.  When I log in the next day I find numerous. Errors in my Permalink checker.when I return to your program it returns all kinds of what it says are serious issues.  I regenerate the same favicon and returns as perfect for another day.  This has been going on for 3-4 days, since I installed your plugin. I run the latest version of Wp Genesis.  http://www.marilynstreats.com

**Comment by phbernard** [comment]
Hi Marilyn,

I've just run the checker against your site (http://realfavicongenerator.net/favicon_checker?site=www.marilynstreats.com): there is no error, it's full green! Did I miss something?

**Comment by phbernard** [comment]
This issue was somehow moved to #56, so I close this one.
