### ISSUE TITLE
My favicon again

### ISSUE THREAD

**Issue by marilyn1998** [RealFaviconGenerator/realfavicongenerator#56]
I wrote a day or so ago with this problem. It was fixed upon reinstall and when you checked it was still working.  Today, the bug is back. I am pasting the screen as I can't do a screenshot.

Favicon checker
We checked the favicon of http://www.marilynstreats.com. Here is our report:

Overview

Desktop (PC, Mac...)
The favicon has serious issues or there is no favicon at all.

Android
The favicon is not well-designed for Android.

iOS
Although your favicon looks fine in some cases, there are some missing points, like the highest resolution devices (eg. latest iPad with Retina screen). See below.

Windows 8
Although the favicon looks fine in some cases, there are some missing points. See below.

The goal of these simulations is to give of an idea of the apparence of the favicon on major platforms. Yet, they may not be 100% accurate. For example, the size of the text may differ slightly on a real device. Also keep in mind that different devices produce different outcomes. This is especially true with Android.

Generic Favicon
The favicon.ico file is not present. Learn more.
favicon.ico seems corrupted or not in ICO format.
Picture(s) contained in favicon.ico have correct dimensions.
Some picture(s) are missing in favicon.ico:

16x16 picture
32x32 picture
48x48 picture
Learn more

favicon.ico is not declared in the HTML code. Learn more.
All recommended PNG favicons are declared.
All PNG favicon(s) have a type attribute.
All PNG favicon(s) have a sizes attribute.
Some PNG favicon(s) could not be found or are corrupted.
All PNG favicon(s) dimensions match the sizes attribute.
iOS Favicon
The apple-touch-icon.png file is not present. Learn more
Some iOS pictures are missing:

114x114 picture
72x72 picture
144x144 picture
60x60 picture
120x120 picture
76x76 picture
152x152 picture
Learn more about these files and why they should be in the root of the web site.

All iOS pictures are declared.
The apple-touch-icon-precomposed.png file is not present. Even if it was deprecated since the release of iOS7, it is still a good idea to have it. Learn more.
Windows 8 Favicon
Picture for Windows 8 / IE 10 tile is declared.
Background color for Windows 8 tile is defined.
Background color for Windows 8 tile is well-formed.
Some recommended pictures for Windows 8 / IE 11 are missing:

70x70 picture
150x150 picture
310x310 picture
310x150 picture
Learn more

browserconfig.xml is not present. Learn more.
Act now!
Your favicon is not perfect? No problem. As simple as it may sound, favicon is a complex topic with a lot of untold stories and misleading information.

Generate your favicon again and fix all errors at once.

Share on facebookShare on google_plusone_shareShare on twitterShare on stumbleuponShare on scoopitShare on linkedinShare on tumblrShare on bloggerShare on flattr.comShare on redditShare on wordpressMore Sharing Services
120
Favicon Generator 
Favicon Checker FAQ 
Blog 
Change Log 
Compatibility Extensions 
API 
Compatibility Test 
Report bug Contact us 
Donate 
Terms of service 
Privacy policy 
RealFaviconGenerator.net © 2013-2014

I am awaiting your answer to see what may be wrong.  Thx so much!

Marilyn lesniak
http://www.marilynstreats.com
Marilyn1998@comcast.net

**Comment by phbernard** [comment]
Hi Marilyn,

I really don't know what goes wrong. I checked your site again (http://realfavicongenerator.net/favicon_checker?site=www.marilynstreats.com) and it went "full green" as expected.

Yet, I note one thing: when I run the checker against your site, it takes a while to display the results. My first hypothesis was that your site may be slow (... to the point of generating timeouts). But when I visit it manually, I don't see anything special, it seems to load normally. And when I run the checker against another web site, the results are displayed much faster. These observations somehow conflict. Hard to figure out.

The next step is for me to run the checker manually directly from the server, to trace what's going on. And in particular where so much time is spent. I don't have the time to do it right-here-right-now but I expect to do this in the next few days.

At least, your favicon is okay: despite of what the checker sometimes says, everything works.

**Comment by phbernard** [comment]
Were there any news regarding this issue? Can it be closed?

**Comment by marilyn1998** [comment]
No news.  Now it won't let me even choose a new favicon without saying it wasn't suitable. All were 260x260 one color with white background.  I gave up and deleted the plugin and decided to continue getting permalink 404 errors.Marilyn Lesniakhttp://www.marilynstreats.com------ Original Message ------From: Philippe BernardTo: RealFaviconGenerator/realfavicongeneratorCc: Marilyn LesniakSent: July 9, 2014 at 4:50 AMSubject: Re: [realfavicongenerator] My favicon again (#56)Were there any news regarding this issue? Can it be closed?

**Comment by phbernard** [comment]
:-/

Could you pass me the picture so I can try to reproduce the issue? Not sure you can do this via Github. You can also mail it to me: philippe@realfavicongenerator.net

**Comment by phbernard** [comment]
I tried to use the picture you sent me: it worked fine.

I don't understand what happens on your side. You say the plugin told you the picture was not suitable. What was the exact message? "Picture too small" or "Picture not square"?

**Comment by marilyn1998** [comment]
I believe one said not square. I didn't send that one. The cupcake was resized to 260x260, it said not suitable to try another picture. The brown one that had my blog name I had used many times when it would give me a 404 error on my report. I thought maybe I tried too many times. I also tried a red stand mixer,  not square and my avatar pic that had been resized to 260x260. I use an ipad mini, mobile and that could very well be the reason things aren't going well. I just decided to forgo the apple icon.Marilyn Lesniakhttp://www.marilynstreats.com------ Original Message ------From: Philippe BernardTo: RealFaviconGenerator/realfavicongeneratorCc: Marilyn LesniakSent: July 15, 2014 at 4:21 PMSubject: Re: [realfavicongenerator] My favicon again (#56)I tried to use the picture you sent me: it worked fine.

I don't understand what happens on your side. You say the plugin told you the picture was not suitable. What was the exact message? "Picture too small" or "Picture not square"?

**Comment by phbernard** [comment]
Hi Marilyn,

I browse the issues to do some clean up and... realize I completely drop yours :-(

I hope you found a solution by the time. If you still want to investigate the issue, could you mail me your picture at philippe@realfavicongenerator.net?

**Comment by marilyn1998** [comment]
Thx for following up! I have since redesigned my site, which included a favicon. Thank you so much! I do believe my problems were related to cache.Sent from XFINITY Connect Mobile App------ Original Message ------From: Philippe BernardTo: RealFaviconGenerator/realfavicongeneratorCc: Marilyn LesniakSent: February 28, 2015 at 9:42 AMSubject: Re: [realfavicongenerator] My favicon again (#56)Hi Marilyn,

I browse the issues to do some clean up and... realize I completely drop yours :-(

I hope you found a solution by the time. If you still want to investigate the issue, could you mail me your picture at philippe@realfavicongenerator.net?

**Comment by phbernard** [comment]
I'm glad you fixed! Thanks for reporting so fast, not waiting 6 months as I did :-/
