### ISSUE TITLE
Windows 8 ignoring <meta name="application-name" content="Whatever"> ?

### ISSUE THREAD

**Issue by iDGS** [RealFaviconGenerator/realfavicongenerator#57]
Windows 8 seems to be ignoring {meta name="application-name" content="Whatever"} (I don't know how to type less-than, greater-than angle brackets here--forgive me?) and is just giving me the default of the page's title tag.  Or is it just me?

**Comment by iDGS** [comment]
[update] Um, could be I'm partly having a vocabulary problem. Specifically, what I'm talking about here is I what "Whatever" to be used in place of the text of the label that appears on the "Favorites", er, tile, when I press the `circled star-+ button` to add a favorite in Windows 8.1 IE11. It's presently displaying the page title instead of "Whatever."

**Comment by phbernard** [comment]
Oooh... You spotted something. I basically tested this code on a Surface 2:

```
<title>My web site</title>
<meta name="application-name" content="My App">
```

When I pin the page (the circled "pin" button), I get "My App" as the default, as expected. But when I follow your procedure to create a classic bookmark, I get "My web site".

I think Microsoft wanted to allow web sites to appear as native apps. By the way, `browserconfig.xml` is quite rich. So the `application-name` meta seems to be here only for this scenario.

Thank you for reporting. Although I mostly advertise the "home screen" title, I though it would work for bookmarks, too.

I also checked on iOS: same behavior. App name when adding to home screen, but classic title for classic bookmarks.

**Comment by iDGS** [comment]
Thanks much for your answer. Perhaps you can tell I'm an alien in the Windows universe? I have to go slow to make sure I understand stuff. So, what I _think_ you're saying is that the behavior--where "save to desktop" gives you one result, but "save as bookmark" gives you another--is (*cough *) "OK" per published specifications. Yes?

I could certainly live with that. 

However, you offer what I (see above confession of ignorance) interpret as a tantalizing hint: " browserconfig.xml is quite rich. " Does that mean there _might_ be a way to have the "save as bookmark" behavior conform to the "save to desktop" behavior?

Again, no urgency to this. I can accept what's happening as OK. But I don't know enough to follow up on your hint, if that's what it was, and yet I'm intrigued... :-)

**Comment by phbernard** [comment]
That's right: "save to desktop" and "save as bookmark", which are very similar, nonetheless offer different default title.

I'm definitely not a specialist of `browserconfig.xml`, but I know that you can customize notifications that appear in the tiles themselves (... when the site was saved to desktop). The CNN web site uses them for example. So it goes way beyond the Apple touch icon and its few settings. But I don't think `browserconfig.xml` can do anything special regarding the default title of bookmarks.

**Comment by iDGS** [comment]
OK. Many thanks again!
