### ISSUE TITLE
Generated URLs link from root and fail in HTML code

### ISSUE THREAD

**Issue by DotFreelance** [RealFaviconGenerator/realfavicongenerator#61]
On my unix system the URLs are taken incorrectly I believe – Removing the root reference at the beginning of the URL made the icons show up in all tested desktop browsers.

**Comment by phbernard** [comment]
Sorry, I don't get it. What did you choose as the directory? Root or something else? And what is the issue in the generated HTML?

**Comment by DotFreelance** [comment]
I chose the default option: root of website, but it generates URLs with a forward slash. This wouldn't work in any browser I tested – I assume because a forward slash makes the directory "unix root" on a localhost. It's literally the most minor bug ever, but I thought I'd report it. Maybe we could add an option for localhost to generate a relative URL? :)

**Comment by phbernard** [comment]
Oh, ok, you are coding your site and you access it directly (file://) and not via HTTP (http://).

You can generate a relative path by selecting "I cannot or I do not want to place favicon files at the root of my web site". And then enter the relative path (eg. `./`). Does this address the issue?

**Comment by DotFreelance** [comment]
It does overall, yes!

I'm accessing it via HTTP through Apache 2.2.

**Comment by phbernard** [comment]
Issue solved, great!

Yet I don't understand the issue if you are using a web server. When you load `http://localhost/index.html` and `index.html` contains `<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">`, then `apple-touch-icon-57x57.png` is looked up by you web server in the web docs root, for example `/var/www/`. In fact if `apple-touch-icon-57x57.png` is placed in the same directory as `index.html`, then everything should work and your Unix box certainly won't look for `/apple-touch-icon-57x57.png`. Do I miss something?

**Comment by phbernard** [comment]
I guess this issue should have already been be closed.

**Comment by jacksonj04** [comment]
What I think is the most likely culprit here (for reference to those who come looking) is that a `/` at the beginning of a relative path refers to "the root of the domain". If you have a web page at `http://localhost/mysite/index.html` containing `<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">` then what will actually happen is the browser will look for the image at `http://localhost/apple-touch-icon-57x57.png`. The way around this (if you need web sites to live in subfolders) is to use the [`<base>` tag](http://www.w3schools.com/tags/tag_base.asp).

This _does not_ have anything to do with local filesystem or the Unix concept of the root folder (except for historically explaining why browsers do that in the first place).

**Comment by phbernard** [comment]
`<base>`?! Wow, I didn't knew that one! Certainly useful in case of refactoring, when moving a bunch of files to a subdirectory...
