### ISSUE TITLE
HTML snippet tags not closed

### ISSUE THREAD

**Issue by Hiblet** [RealFaviconGenerator/realfavicongenerator#62]
Generated favicons today (donated - yay me), and downloaded the HTML snippet via the 'Copy to Clipboard' button.  Visual Studio 2010 showed the link tags as unclosed, missing a terminating slash.  No big deal to fix, just thought I should bring to your attention, apologies if already spotted, or if it's something that I did.  Details: OS=Win7, Browser=Firefox 31.0.

**Comment by phbernard** [comment]
Hi Hiblet,

Thank you for reporting. The first version of the code was as you describe: `<stuf here... />`. However, against all odds, this is not correct except in XHTML (somehow deprecated). Please have a look to #11 and the reference listed here and tell me what you think.

**Comment by Hiblet** [comment]
Interesting, I do work with strict XHTML on by default, which is why it probably came up.  You might try explicitly closing the tags in the old style ie <link>blah blah blah</link>, which should be correct in all variants, but I could well be wrong, just an idea.

**Comment by jacksonj04** [comment]
My view would be that you should go without the self-closing slash, since it's not required in HTML5 (which is where most people will be) and those working in Strict will have browsers or editors throw a warning which they should know how to fix. At the most all it needs is a line explaining that people using XHTML will need to self-close the tags.

**Comment by onebitrocket** [comment]
While It's not required in html 5, isn't it still valid?

Surely if that's the case, couldn't adding a closing slash be seen "backwards compatibility". 

Thanks

Matt

w: www.matttunney.co.uk
e: mtunney@me.com

**Comment by phbernard** [comment]
Thank you all for your feedback.

XHTML needs self-closing markups, HTML5 doesn't.

All this will end with an option, with "no self-closing slash" as the default. As you said Nick, most people do HTML5. Steve, don't forget to check it (well, when it's done :) ).

**Comment by Hiblet** [comment]
No problem.  I can see HTML4 vs 5 vs XHTML thing is a story that will run and run.  I have no strong feelings either way, but I like Matt's view of maximising compatibility.

**Comment by phbernard** [comment]
Done and deployed a minute ago.
