### ISSUE TITLE
FAQ Inconsistency, Need Clearification

### ISSUE THREAD

**Issue by Soundvessel** [RealFaviconGenerator/realfavicongenerator#66]
First off love this. Going to try and get our company to make a donation since this saves a TON of headaches.

In the FAQ you say that the favicon.ico declaration is not present in generated code but it is http://screencast.com/t/GaKgRCkJ

Just want to be clear we can forgo the <link etc declaration as long as it is placed in root of site.

Thanks!

**Comment by phbernard** [comment]
Thank you for the feedback!

That's right. I updated the FAQ.
