### ISSUE TITLE
Wrong look

### ISSUE THREAD

**Issue by shohruh** [RealFaviconGenerator/realfavicongenerator#70]
I generated favicon for site https://shohruh.uz at http://realfavicongenerator. But On IE 11 looking smaller, how i can fix it. On Chrome, Firefox looking pretty. Google.com On IE 11 looking pretty. Capture pasted.
![img1](https://cloud.githubusercontent.com/assets/7037088/4060058/592d755e-2dec-11e4-8531-a3be1b1f0a04.JPG)
![img2](https://cloud.githubusercontent.com/assets/7037088/4060059/59309aae-2dec-11e4-8d1e-799fff6b3b60.JPG)
![img3](https://cloud.githubusercontent.com/assets/7037088/4060061/5965f9f6-2dec-11e4-9484-046b0a4dd68f.JPG)
![img4](https://cloud.githubusercontent.com/assets/7037088/4060062/599ef350-2dec-11e4-9f85-6d7929663d97.JPG)

**Comment by phbernard** [comment]
Hum... I see. Although I don't know your original picture, I guess this is related to issue #26 . It should be fixed in a week or two.

**Comment by shohruh** [comment]
My original picture: uploaded

27.08.2014, 18:24, "Philippe Bernard" notifications@github.com:

**Comment by phbernard** [comment]
Did you really upload your picture? I can't see it, it's just written "uploaded".

**Comment by phbernard** [comment]
Alright. I confirm the issue. This is because what you see in IE11 is the icon you designed for iOS.

A week or two and that should be fixed. Sorry for the inconvenience.

**Comment by shohruh** [comment]
I will delete real favicon image, are you agree ?

**Comment by phbernard** [comment]
Yes, you can delete the 196x196 icon file _and_ the corresponding declaration in the HTML code.

**Comment by shohruh** [comment]
No, may i delete uploaded favicon on Github, do not need it you ?

**Comment by phbernard** [comment]
Oh, sorry. Yes, sure, you can delete it.

**Comment by shohruh** [comment]
When issue will be fixed. Can you notify me ?

**Comment by phbernard** [comment]
Sure! Yet, forgetful as I am, it would be safer for your to "Watch" (button at the top of this page) the project :)

**Comment by shohruh** [comment]
Thanks. I'll wait for fixing issue.

**Comment by phbernard** [comment]
Just to let you know that things are going on... http://realfavicongenerator.net/blog/android-chrome-and-its-favicon/

**Comment by phbernard** [comment]
Fixed!

**Comment by shohruh** [comment]
Thanks. No problems.
