### ISSUE TITLE
Autocrop non-square SVG pictures

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#71]
Submitted by @chaoaretasty, see issue #65:

I noticed a couple of annoyances while using SVG images that I think can easily be worked around.

I think it could be possible to turn off the requirement for an exactly square image, especially as an SVG may well be sized to the edge of the image and contain transparency. In such cases it could be centred and have the rest padded with transparency. Perhaps highlight when uploading an non-square image that this has happened.

**Comment by chaoaretasty** [comment]
Not sure what you use for processing the SVGs but you should be able to do something like this as a preprocessing step:
- Get ViewBox attribute from SVG tag
- If X and Y differ then adjust the smaller of the two dimensions by padding out the difference in the viewbox
- Save the change and use this file for the SVG processing

As long as your pipeline properly recognises viewBox this should be all you need, if it doesn't recognise viewBox you'd need something that can transform the file, which I agree could be a lot of hassle.

**Comment by phbernard** [comment]
I'm using ImageMagick. Apparently, it has some SVG manipulation capabilities. Not sure I can manipulate the ViewBox. Well, Google will surely come with a solution :)

**Comment by chaoaretasty** [comment]
As long as ImageMagick honours viewBox you should be able to edit the attribute in the XML before putting it through.

**Comment by phbernard** [comment]
Done along with #173

**Comment by saruman** [comment]
So, will be possible to use SVG file too? Let us know.
