### ISSUE TITLE
Installation instructions in the favicon package

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/realfavicongenerator#73]
Currently, when a favicon is generated, the user is presented two resources:
- A favicon package (ie. a ZIP file) which contains the files to be copied in the web site. No less no more.
- Instructions to install the favicon, including HTML code to copy/paste.

Therefore, the package is not standalone. If the user downloads it and closes his browser, he loses the instructions and HTML code.

The package should contain the instructions, for example as an `install.txt` file. However, when doing this, the installation procedure itself becomes more complex, since the `install.txt` file is not part of the files to be copied to the web site.

Possible solutions:
- Include `install.txt` and update the installation instructions accordingly ("Copy all files except `install.txt`"). I don't like this one so much. Given the feedback I received, there is not a huge demand for `install.txt`, so this updated procedure sounds like unnecessary hassle.
- Make `ìnstall.txt` an option, selected during favicon generation. When the option is checked, the package contains `install.txt` at the root and a `favicon_files` directory which contain anything else. This is my favorite solution.

**Comment by scotepi** [comment]
The 2nd option would work. I would love this as I need to work with CRM's where I don't have direct access to and need to email the zip's to support to make changes, having a install.txt or favicon.htm would help a lot.

Doing favicon.htm would allow for people that do SSI's to just include a file into the head and not need to worry about copy and pasting the code in if they ever update the icons. Not that anything other then the tile ever changes but still.

**Comment by phbernard** [comment]
Implemented, to be deployed.

![image](https://user-images.githubusercontent.com/423852/35319811-c2371ffc-00e1-11e8-9abf-13d99552cd27.png)

**Comment by phbernard** [comment]
Deployed a minute ago.

**Comment by JonathanPlasse** [comment]
I have check both option, but README.md and html_code.html does not appear in the favicon package
