### ISSUE TITLE
Favicon is not transparent in IE 11

### ISSUE THREAD

**Issue by XHotSniperX** [RealFaviconGenerator/realfavicongenerator#78]
Hello

When you choose the "opaque" Option you have to mention that this will effect not only Apple web sticks but also IE 11 and other Browsers which use 196x196 png. Maybe you shouldn't make the 196 picture opaque at all.

**Comment by phbernard** [comment]
Absolutely. This is misleading and that should be fixed quite soon, I hope next week. This is issue #26.

**Comment by phbernard** [comment]
Fixed!
