### ISSUE TITLE
Windows7 problems

### ISSUE THREAD

**Issue by natkaratkova** [RealFaviconGenerator/realfavicongenerator#80]
Hi, but what about Windows7?
I have a problem with Win7 IE10 from your table Compatibility - OK
![image 2014-09-10 at 4 22 45](https://cloud.githubusercontent.com/assets/2752193/4218059/1a38869c-38ee-11e4-9537-d0e155db0639.png)

And really there are no solutions for Win7 Chrome?

Website https://www.promarket.pro/

**Comment by phbernard** [comment]
I think there is a problem with your pictures. Looking at the source of your homepage, I expect to find pictures such as https://www.promarket.pro/favicon-160x160.png . But it leads to a 404 error. Maybe you put the pictures in a subdirectory?

**Comment by phbernard** [comment]
Oh, and about the issue in the compatibility list: this is only when pictures are put behind 301 redirection. A very specific setting. In the classic case (pictures are placed along with the rest of the site), there is no such issue.

**Comment by natkaratkova** [comment]
Oh, thank you very much for your reply!
you are right, I will try to solve it
