### ISSUE TITLE
Android uses the favicon rather than the App Icon

### ISSUE THREAD

**Issue by AlexKeySmith** [RealFaviconGenerator/realfavicongenerator#82]
I'm finding that when adding a bookmark to the home screen in recent Android versions that it will use the favicon rather than one defined for the homescreen/

I presume because it prefers now the icon rather than apple-touch-icon.

But is there a way to have a separate favicon to a home-screen bookmark icon for Android?

If not, perhaps adding a little note on compatibility? Saying that a dedicated app icon will only work on earlier Android versions.

Keep up the awesome work.

**Comment by AlexKeySmith** [comment]
Reading http://realfavicongenerator.net/blog/android-chrome-and-its-favicon/ it looks like it's mentioned in https://github.com/RealFaviconGenerator/realfavicongenerator/issues/26

Thanks for pointing it out on http://stackoverflow.com/questions/25863616/separate-favicon-and-android-homescreen-icon/25871693#25871693 :-)

**Comment by phbernard** [comment]
Didn't we meet on SO today? ;)

Issue #26 was fixed today. You might even have been misled by the fix because it was published more or less when you made your experiments.

Regarding the Android specific designed, it will be addressed by issue #83.

**Comment by AlexKeySmith** [comment]
We did indeed @phbernard  :-) Thanks!
