### ISSUE TITLE
Favicon 16x16

### ISSUE THREAD

**Issue by shohruh** [RealFaviconGenerator/realfavicongenerator#84]
http://favicon.yandex.ru/favicon/shohruh.uz not showing 16x16 favicon ico fo site shohruh.uz.
For other site showing favicon:
http://favicon.yandex.ru/favicon/yandex.ru
http://favicon.yandex.ru/favicon/google.com
Also showing for site realfavicongenerator.net: http://favicon.yandex.ru/favicon/realfavicongenerator.net
My favicon was generated by realfavicongenerator.net

**Comment by phbernard** [comment]
I observe the same thing...

As first, I though that might be because your `favicon.ico` file was not at the root of your web site. But it actually is, wrong hypothesis.

http://shohruh.uz/favicon.ico is present and well-formed... no problem...

Is your favicon new? (eg. less than a few hours or days)? Maybe Yandex needs a few days to index it.

**Comment by shohruh** [comment]
I have read on the Internet, Yandex uses 16x16 favicon.ico for http://favicon.yandex.ru/favicon/shohruh.uz
But realfavicongenerator.net not creates a 16x16 favicon.ico, and creates a favicon-16x16.png. Created favicon.ico by realfavicongenerator.net is 48x48 favico.ico. Please, help.

**Comment by phbernard** [comment]
In fact, <a href="http://realfavicongenerator.net/faq#why_ico_so_big">the `favicon.ico`file generated by RFG contains three pictures: 16x16, 32x32 and 48x48</a>. http://favicon.yandex.ru/favicon/realfavicongenerator.net works, and this site was only equiped with a `favicon.ico` from RFG. This proves that Yandex is able to process such picture.

Again, it might take a few days to Yandex to process the favicon of your site and show it. It is somehow the same with Google: change the title of a page, Google reflects the change only a few days later, after it has visited the site.

**Comment by phbernard** [comment]
Did you check Yandex results again?

**Comment by shohruh** [comment]
Site http://favicon.yandex.ru/ not working... When it works, i give results.

**Comment by phbernard** [comment]
I didn't realized I could check by myself :( Yep, site down, let's wait...

**Comment by phbernard** [comment]
<a href="https://help.yandex.com/webmaster/search-results/favicon.xml">Yandex is supposed to update the favicon three weeks at most</a>. Your favicon should appear by now, but this is still not the case.

I think there is something else to investigate. Your site is always-on SSL. So when I access `http://shohruh.uz/favicon.ico` (no SSL), I am redirected to `https://shohruh.uz/favicon.ico` (SSL). The redirection maybe trouble Yandex. You might want to deactivate the redirection only for `/favicon.ico` so the URL works as is.

**Comment by phbernard** [comment]
Did you have the opportunity to investigate the last point about SSL?

**Comment by shohruh** [comment]
How I can deactivate the redirection only for /favicon.ico ?

**Comment by phbernard** [comment]
It depends on your web server. If you use Apache, you should find interesting material here: http://stackoverflow.com/questions/2079015/htaccess-301-redirect-for-all-https-to-http-except-one-page

**Comment by shohruh** [comment]
Please check, http://favicon.yandex.ru/favicon/shohruh.uz displaying wrong black favicon. Also check http://favicon.yandex.ru/favicon/kinobox.uz. Both favicons was generated by realfavicongenerator. Favicon for kinobox.uz displaying normally. How I can solve problem ?

**Comment by phbernard** [comment]
Looking at http://favicon.yandex.ru/favicon/shohruh.uz , I notice the icon is similar to the expected result but somehow corrupted. The background is black instead of white.

![image](https://cloud.githubusercontent.com/assets/423852/4874955/07dda4b2-627b-11e4-9c70-b847e61e8373.png)

However, files http://kinobox.uz/favicon.ico and https://shohruh.uz/favicon.ico are identical. I really don't see why they are not processed the same way.

Did you update something recently? Maybe there is a pending change to be processed by Yandex?

**Comment by phbernard** [comment]
Any news about this issue? Now http://favicon.yandex.ru/favicon/shohruh.uz returns an empty PNG picture. Did you change anything?

**Comment by phbernard** [comment]
I visited http://favicon.yandex.ru/favicon/shohruh.uz: the result looks correct now.

This issue was opened long ago, I close it now. But feel free to post again if you still want to investigate this.

**Comment by shohruh** [comment]
Thank you. Issue fixed. I think, Yandex fixed their own bug. No problem.

**Comment by phbernard** [comment]
Excellent way of fixing things ;-)

**Comment by shohruh** [comment]
:)
