### ISSUE TITLE
New format 180x180 for iPhone 6 Plus

### ISSUE THREAD

**Issue by kukulich** [RealFaviconGenerator/realfavicongenerator#85]
http://www.mobilexweb.com/blog/safari-ios8-iphone6-web-developers-designers

**Comment by phbernard** [comment]
Great!

Looking for similar information, I find an <a href="http://stackoverflow.com/questions/25779215/app-icon-sizes-as-of-ios-8">answer on SO</a>. It talks about 3 icons: 87x87, 120x120 and 180x180. I'm not familiar with the iOS terminology, what are these sizes for? Do you know if the 180x180 icon is the only icon to declare by web sites?

**Comment by kukulich** [comment]
I find this:

1) https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW3
2) https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27-SW2

**Comment by phbernard** [comment]
The first page is ma favorite reference from Apple, and it was not updated yet. But the second page gives  exactly what I need. In addition to the existing 76x76, 120x120 and 152x152 icons, iOS8 adds the 180x180 icon. Perfect! 

Thank you for the issue and links! I guess there will be a new release tomorrow!

**Comment by kukulich** [comment]
You're welcome :)

**Comment by phbernard** [comment]
Implemented and deployed a few minutes ago. This is <a href="http://realfavicongenerator.net/change_log">v0.9</a>.

**Comment by alrra** [comment]
@phbernard Note: In practice, it seems that the iPhone 6 Plus doesn't really use the `180×180px` touch icon (see: https://github.com/h5bp/html5-boilerplate/pull/1599).

**Comment by phbernard** [comment]
Thank you for the feedback. Interesting thread. Although the idea of a 180x180 icon is good, I realize it is for the iPad, not the iPhone 6 Plus... I wish I have more Apple fan friends to figure this out :)
