### ISSUE TITLE
"Compression" tab

### ISSUE THREAD

**Issue by shohruh** [RealFaviconGenerator/realfavicongenerator#86]
"Compression" tab not working, always loading but now showing result. S
![screen1](https://cloud.githubusercontent.com/assets/7037088/4333861/0e2a0746-3fe6-11e4-9088-ceb6c38ac752.JPG)
creen attached.

**Comment by phbernard** [comment]
Oops :-/

I don't reproduce this issue. Maybe it comes from your particular picture. Could you post it (or send it to me at philipperealfavicongenerator.net) so I can give it a try?

**Comment by shohruh** [comment]
shows nothing, only loading. I cann't post it. What i must post ?

**Comment by phbernard** [comment]
I would need your original icon picture to reproduce the issue. Maybe there is something unusual with its format, maybe it's quite big...

**Comment by shohruh** [comment]
Sent email to you.

**Comment by phbernard** [comment]
Thanks! I reproduced the issue: it actually works... but it takes nearly two minutes to generate the thumbnails. Oh.

Your picture is quite large (2400x2400), yet it should not be that hard to generate thumbnails in a moderate delay.

**Comment by phbernard** [comment]
Fixed and deployed a minute ago. With your picture, the preview is now displayed after a few seconds.

**Comment by shohruh** [comment]
Confirm. Issued fixed.
