### ISSUE TITLE
Currently Getting a Console Error

### ISSUE THREAD

**Issue by meowsus** [RealFaviconGenerator/realfavicongenerator#89]
http://note.io/1vAET6w

Seems to be happening regardless of what is uploaded. Happens on the Compression tab.

**Comment by phbernard** [comment]
Oops... Thanks for reporting! You found two issues:
- No error reporting when the compression tab fails.
- The compression tab does not work with SVG pictures.

Everything was fixed and deployed a minute ago. The picture you sent me by email now works.
