### ISSUE TITLE
Compression error

### ISSUE THREAD

**Issue by trhall** [RealFaviconGenerator/realfavicongenerator#91]
Cannot get this particular image to compress. Get the following error every time I click on the "Compression" tab (haven't even chosen any compression options):

> Something went wrong with the compression. Sorry for this :-/

Was able to generate a Favicon earlier (with and without compression) from the same machine/browser on another image. OS X 10.9.5 with Chrome version 38.0.2125.101.

![penucopia_logo_favicon_300](https://cloud.githubusercontent.com/assets/14863/4605894/7cba625e-5202-11e4-9e15-e47283724d1d.png)

**Comment by phbernard** [comment]
Thank you for reporting!

That was due to the way PNGQuant was invoked, combined with a detailed master picture. Fixed and deployed a minute ago. The compression preview is now displayed with your picture, and the compression of the final package works, too.

**Comment by trhall** [comment]
@phbernard I wondered if it was due to the complexity of the image... Thanks for the fix. I'll try it tonight and see how things go.

Thanks again for the help! Site is great. I'll be telling others about it. Donating as well. Keep up the great work.

**Comment by trhall** [comment]
@phbernard Worked great. Thank you again.

**Comment by phbernard** [comment]
Great! Thanks for the feedback :)
