### ISSUE TITLE
Compression Error - Favicon Install Fails

### ISSUE THREAD

**Issue by sirouk** [RealFaviconGenerator/realfavicongenerator#92]
Compression Error on generation page, I can continue to install but that fails as well with no error message.
![aim_high_favicon](https://cloud.githubusercontent.com/assets/8901571/4607320/c679ebba-524a-11e4-94ce-069120c967c5.gif)

**Comment by phbernard** [comment]
Thank you for reporting.

There was an issue with GIF pictures when creating the compression preview. Fixed and deployed a minute ago. Your master picture is now processed correctly.
