### ISSUE TITLE
More detailed explanation

### ISSUE THREAD

**Issue by ingria** [RealFaviconGenerator/realfavicongenerator#95]
Example error message:
![screen](https://cloud.githubusercontent.com/assets/2178368/4652460/1ea1448a-54a5-11e4-9799-ad7e692d2324.png)
I cannot get what exact icon is incorrect, because everything seems OK. Especially taking into account the previous green message, which says that all icons are correct.

I suggest removing the green message (in my case, when some icons are incorrect) and altering the red message in order to provide more information:

![screen2](https://cloud.githubusercontent.com/assets/2178368/4652544/c20f9f36-54a5-11e4-9bf0-3b3602648b50.png)

**Comment by phbernard** [comment]
Yeah I admit the messages can be misleading. PNG pics and `favicon.ico` suffer from the same symptoms.

**Comment by phbernard** [comment]
The checker was rewritten since then. It could certainly be more verbose, but at least the screenshots above are out of date.
